const languageNameTranslations = {
  "English": {
    "Nahuatl": "Nahuatl",
    "Quechua": "Quechua",
    "Kwak'wala": "Kwak'wala",
    "Navajo": "Navajo",
    "Yucatec Mayan": "Yucatec Mayan",
    "Nivkh": "Nivkh",
    "Tagalog": "Tagalog", 
    "Cherokee": "Cherokee",
    "Mohawk": "Mohawk",
    "Mapudungun": "Mapudungun",
    "Hawaiian": "Hawaiian",
    "Kildin Sami": "Kildin Sami",
    "Tlingit": "Tlingit",
    "Abkhaz": "Abkhaz",
    "Tsez": "Tsez",
    "Tabasaran": "Tabasaran",
    "Nenets": "Nenets",
    "Ket": "Ket",
    "Abenaki": "Abenaki",
    "Ainu": "Ainu",
    "Aymara": "Aymara",
    "Shoshone": "Shoshone",
    "O'odham": "O'odham",
    "Pitjantjatjara": "Pitjantjatjara",
    "Djambarrpuyngu": "Djambarrpuyngu",
    "Siberian Yupik": "Siberian Yupik",
    "Jeju": "Jeju",
    "Kikuyu": "Kikuyu",
    "Kumeyaay": "Kumeyaay",
    "Guugu Yimithirr": "Guugu Yimithirr",
    "Mi'kmaq": "Mi'kmaq",
    "Aleut": "Aleut",
    "Maasai": "Maasai",
    "Nuu-Chah-Nulth": "Nuu-Chah-Nulth",
    "Nez Perce": "Nez Perce",
    "ǃKung": "ǃKung",
    "Xavante": "Xavante",
    "Uyghur": "Uyghur",
    "Sumerian": "Sumerian",
    "Rusyn": "Rusyn",
    "Zuni": "Zuni",
    "Basque": "Basque",
    "Welsh": "Welsh",
    "Quapaw": "Quapaw",
    "Nheengatu": "Nheengatu",
    "Powhatan": "Powhatan",
    "Samogitian": "Samogitian",
    "Yaqui": "Yaqui",
    "Tsimshian": "Tsimshian",
    "Passamaquoddy": "Passamaquoddy",
    "Mohave": "Mohave",
    "Lushootseed": "Lushootseed",
    "Maori": "Maori",
    "Lhasa Tibetan": "Lhasa Tibetan",
    "Khoekhoe": "Khoekhoe",
    "Katu": "Katu",
    "Itelmen": "Itelmen",
    "Icelandic": "Icelandic",
    "Haida": "Haida",
    "Elfdalian": "Elfdalian",
    "Deg Xinag": "Deg Xinag",
    "Chukchi": "Chukchi",
    "Chulym": "Chulym",
    "Comanche": "Comanche",
    "Beothuk": "Beothuk",
    "Bashkir": "Bashkir",
    "Selkup": "Selkup",
    "Djeoromitxí": "Djeoromitxí",
    "Yakut": "Yakut",
    "Kokborok": "Kokborok",
    "Kabardian": "Kabardian",
    "Quileute": "Quileute",
    "Cree": "Cree",
    "Inuktitut": "Inuktitut",
    "Dënesųłiné": "Dënesųłiné",
    "Tsakhur": "Tsakhur",
    "Belarusian": "Belarusian",
    "Kolyma Yukaghir": "Kolyma Yukaghir",
    "Yokuts": "Yokuts",
    "Kutenai": "Kutenai",
    "Adyghe": "Adyghe",
    "Arapaho": "Arapaho",
    "Blackfoot": "Blackfoot",
    "Buryat": "Buryat",
    "Chamorro": "Chamorro",
    "Dakota": "Dakota",
    "Evenki": "Evenki",
    "Fijian": "Fijian",
    "Gwich'in": "Gwich'in",
    "Hopi": "Hopi",
    "Igbo": "Igbo",
    "Jingpo": "Jingpo",
    "Kalaallisut": "Kalaallisut",
    "Lakota": "Lakota",
    "Mansi": "Mansi",
    "Naxi": "Naxi",
    "Ojibwe": "Ojibwe",
    "Pawnee": "Pawnee",
    "Rapanui": "Rapanui",
    "Sandawe": "Sandawe",
    "Tuvan": "Tuvan",
    "Udmurt": "Udmurt",
    "Veps": "Veps",
    "Warlpiri": "Warlpiri",
    "Xhosa": "Xhosa",
    "Yoruba": "Yoruba",
    "Zhuang": "Zhuang",
    "Zulu": "Zulu",
    "Hadza": "Hadza",
    "Khanty": "Khanty",
    "Rohingya": "Rohingya",
    "Scots Gaelic": "Scots Gaelic",
    "Koryak": "Koryak",
    "Nganasan": "Nganasan",
    "Kalmyk": "Kalmyk",
    "Komi": "Komi",
    "Yurok": "Yurok",
    "Chinook": "Chinook",
    "Guarani": "Guarani",
    "Caddo": "Caddo",
    "Wichita": "Wichita",
    "Keres": "Keres",
    "Muscogee": "Muscogee",
    "Kiliwa": "Kiliwa",
    "Pirahã": "Pirahã",
    "Chechen": "Chechen",
    "Alyutor": "Alyutor",
    "Sirenik": "Sirenik",
  },
  "French": {
    "Nahuatl": "Nahuatl",
    "Quechua": "Quechua",
    "Kwak'wala": "Kwak'wala", 
    "Navajo": "Navajo",
    "Yucatec Mayan": "Maya yucatèque",
    "Inuktitut": "Inuktitut",
    "Mohawk": "Mohawk",
    "Cree": "Cri",
    "Abenaki": "Abénaki",
    "Mi'kmaq": "Mi'kmaq",
    "Zuni": "Zuni",
    "Mapudungun": "Mapudungun",
    "Nivkh": "Nivkhe",
    "Haida": "Haïda",
    "Cherokee": "Cherokee",
    "Nheengatu": "Nheengatu",
    "Powhatan": "Powhatan",
    "Samogitian": "Samogitien",
    "Yaqui": "Yaqui",
    "Tsimshian": "Tsimshian",
    "Passamaquoddy": "Passamaquoddy",
    "Mohave": "Mohave",
    "Lushootseed": "Lushootseed",
    "Maori": "Maori",
    "Lhasa Tibetan": "Tibétain de Lhassa",
    "Khoekhoe": "Khoekhoe",
    "Katu": "Katu",
    "Itelmen": "Itelmène",
    "Icelandic": "Islandais",
    "Elfdalian": "Elfdalien",
    "Deg Xinag": "Deg Xinag",
    "Chukchi": "Tchouktche",
    "Chulym": "Tchoulyme",
    "Comanche": "Comanche",
    "Beothuk": "Béothuk",
    "Bashkir": "Bachkir",
    "Selkup": "Selkoupe",
    "Djeoromitxí": "Djéoromitxí",
    "Yakut": "Yakoute",
    "Kokborok": "Kokborok",
    "Kabardian": "Kabarde",
    "Quileute": "Quileute",
    "Tagalog": "Tagalog",
    "Pitjantjatjara": "Pitjantjatjara",
    "Djambarrpuyngu": "Djambarrpuyngu",
    "Siberian Yupik": "Yupik sibérien",
    "Jeju": "Jeju",
    "Kikuyu": "Kikuyu",
    "Kumeyaay": "Kumeyaay",
    "Guugu Yimithirr": "Guugu Yimithirr",
    "Aleut": "Aléoute",
    "Maasai": "Maasaï",
    "Nuu-Chah-Nulth": "Nuu-chah-nulth",
    "Nez Perce": "Nez-percé",
    "ǃKung": "ǃKung",
    "Xavante": "Xavante",
    "Uyghur": "Ouïghour",
    "Sumerian": "Sumérien",
    "Rusyn": "Ruthène",
    "Basque": "Basque",
    "Welsh": "Gallois",
    "Quapaw": "Quapaw",
    "O'odham": "O'odham",
    "Tsez": "Tsez",
    "Tabasaran": "Tabassaran",
    "Nenets": "Nénètse",
    "Ket": "Ket",
    "Hawaiian": "Hawaïen",
    "Kildin Sami": "Same de Kildin",
    "Tlingit": "Tlingit",
    "Abkhaz": "Abkhaze",
    "Shoshone": "Shoshone",
    "Ainu": "Aïnou",
    "Aymara": "Aymara",
    "Dënesųłiné": "Déné",
    "Tsakhur": "Tsakhour",
    "Belarusian": "Biélorusse",
    "Kolyma Yukaghir": "Youkaghir de Kolyma",
    "Yokuts": "Yokuts",
    "Kutenai": "Kootenai",
    "Adyghe": "Adyguéen",
    "Arapaho": "Arapaho",
    "Blackfoot": "Pied-noir",
    "Buryat": "Bouriate",
    "Chamorro": "Chamorro",
    "Dakota": "Dakota",
    "Evenki": "Evenk",
    "Fijian": "Fidjien",
    "Gwich'in": "Gwich'in",
    "Hopi": "Hopi",
    "Igbo": "Igbo",
    "Jingpo": "Jingpo",
    "Kalaallisut": "Kalaallisut",
    "Lakota": "Lakota",
    "Mansi": "Mansi",
    "Naxi": "Naxi",
    "Ojibwe": "Ojibwé",
    "Pawnee": "Pawnee",
    "Rapanui": "Rapanui",
    "Sandawe": "Sandawe",
    "Tuvan": "Touva",
    "Udmurt": "Oudmourte",
    "Veps": "Vepse",
    "Warlpiri": "Warlpiri",
    "Xhosa": "Xhosa",
    "Yoruba": "Yoruba",
    "Zhuang": "Zhuang",
    "Zulu": "Zoulou",
    "Hadza": "Hadza",
    "Khanty": "Khanty",
    "Rohingya": "Rohingya",
    "Scots Gaelic": "Gaélique écossais",
    "Koryak": "Koriak",
    "Nganasan": "Nganassane",
    "Kalmyk": "Kalmouk",
    "Komi": "Komi",
    "Yurok": "Yurok",
    "Chinook": "Chinook",
    "Guarani": "Guarani",
    "Caddo": "Caddo",
    "Wichita": "Wichita",
    "Keres": "Keres",
    "Muscogee": "Muscogee",
    "Kiliwa": "Kiliwa",
    "Pirahã": "Pirahã",
    "Chechen": "Tchétchène",
    "Alyutor": "Aliouteur",
    "Sirenik": "Sireniki",
  },
  "Ukrainian": {
    "Nahuatl": "Науатль",
    "Quechua": "Кечуа",
    "Kwak'wala": "Квак'вала",
    "Navajo": "Навахо",
    "Yucatec Mayan": "Юкатекська мая",
    "Inuktitut": "Інуктитут",
    "Mohawk": "Могавк",
    "Cree": "Крі",
    "Abenaki": "Абенакі",
    "Mi'kmaq": "Мі'кмак",
    "Zuni": "Зуні",
    "Mapudungun": "Мапудунґун",
    "Nivkh": "Нівхська",
    "Haida": "Хайда",
    "Cherokee": "Черокі",
    "Nheengatu": "Ньєнґату",
    "Powhatan": "Поухатан",
    "Samogitian": "Жемайтська",
    "Yaqui": "Які",
    "Tsimshian": "Цимшиан",
    "Passamaquoddy": "Пассамакводді",
    "Mohave": "Могаве",
    "Lushootseed": "Лушуцід",
    "Maori": "Маорі",
    "Lhasa Tibetan": "Лхаська тибетська",
    "Khoekhoe": "Кхоекхое",
    "Katu": "Кату",
    "Itelmen": "Ітельменська",
    "Icelandic": "Ісландська",
    "Elfdalian": "Ельвдальська",
    "Deg Xinag": "Деґ Хінаґ",
    "Chukchi": "Чукотська",
    "Chulym": "Чулимська",
    "Comanche": "Команчська",
    "Beothuk": "Беотук",
    "Bashkir": "Башкирська",
    "Selkup": "Селькупська",
    "Djeoromitxí": "Джеоромітші",
    "Yakut": "Якутська",
    "Kokborok": "Кокборок",
    "Kabardian": "Кабардинська",
    "Quileute": "Квілеут",
    "Tagalog": "Таґалоґ",
    "Pitjantjatjara": "Пітьянтьятьяра",
    "Djambarrpuyngu": "Дьямбарпуйнґу",
    "Siberian Yupik": "Сибірська юпікська",
    "Jeju": "Чеджу",
    "Kikuyu": "Кікуйю",
    "Kumeyaay": "Кумеяай",
    "Guugu Yimithirr": "Ґууґу їмітір",
    "Aleut": "Алеутська",
    "Maasai": "Масаї",
    "Nuu-Chah-Nulth": "Нуу-ча-нулт",
    "Nez Perce": "Нез-перс",
    "ǃKung": "!Кунґ",
    "Xavante": "Шаванте",
    "Uyghur": "Уйґурська",
    "Sumerian": "Шумерська",
    "Rusyn": "Русинська",
    "Basque": "Баскська",
    "Welsh": "Валлійська",
    "Tsez": "Цезька",
    "Tabasaran": "Табасаранська",
    "Nenets": "Ненецька",
    "Ket": "Кетська",
    "O'odham": "О'одгам",
    "Hawaiian": "Гавайська",
    "Kildin Sami": "Кільдін-саамська",
    "Tlingit": "Тлінґітська",
    "Abkhaz": "Абхазька",
    "Shoshone": "Шошонська",
    "Ainu": "Айнська",
    "Aymara": "Аймарська",
    "Quapaw": "Квапо",
    "Dënesųłiné": "Денесюліне",
    "Tsakhur": "Цахурська",
    "Belarusian": "Білоруська",
    "Kolyma Yukaghir": "Колимська юкаґірська",
    "Yokuts": "Йокутська",
    "Kutenai": "Кутенай",
    "Adyghe": "Адиґейська",
    "Arapaho": "Арапаго",
    "Blackfoot": "Мова чорноногих",
    "Buryat": "Бурятська",
    "Chamorro": "Чаморро",
    "Dakota": "Дакота",
    "Evenki": "Евенкійська",
    "Fijian": "Фіджійська",
    "Gwich'in": "Ґвічин",
    "Hopi": "Гопі",
    "Igbo": "Іґбо",
    "Jingpo": "Цзінпо",
    "Kalaallisut": "Ґренландська",
    "Lakota": "Лакота",
    "Mansi": "Мансійська",
    "Naxi": "Насі",
    "Ojibwe": "Оджибве",
    "Pawnee": "Пауні",
    "Rapanui": "Рапануї",
    "Sandawe": "Сандаве",
    "Tuvan": "Тувинська",
    "Udmurt": "Удмуртська",
    "Veps": "Вепська",
    "Warlpiri": "Варлпірі",
    "Xhosa": "Коса",
    "Yoruba": "Йоруба",
    "Zhuang": "Чжуанська",
    "Zulu": "Зулу",
    "Hadza": "Хадза",
    "Khanty": "Хантийська",
    "Rohingya": "Рогінджа",
    "Scots Gaelic": "Шотландська ґельська",
    "Koryak": "Коряцька",
    "Nganasan": "Нґанасанська",
    "Kalmyk": "Калмицька",
    "Komi": "Комі",
    "Yurok": "Юрок",
    "Chinook": "Чинук",
    "Guarani": "Ґуарані",
    "Caddo": "Каддо",
    "Wichita": "Вічита",
    "Keres": "Керес",
    "Muscogee": "Маскоґі",
    "Kiliwa": "Кіліва",
    "Pirahã": "Піраган",
    "Chechen": "Чеченська",
    "Alyutor": "Алюторська",
    "Sirenik": "Сиреніцька юпікська",
  },
  "Mongolian": {
    "Nahuatl": "Науатл",
    "Quechua": "Кечуа",
    "Kwak'wala": "Квакʼвала",
    "Navajo": "Навахо",
    "Yucatec Mayan": "Юкатекийн майя",
    "Inuktitut": "Инуктитут",
    "Mohawk": "Мохаук",
    "Cree": "Кри",
    "Abenaki": "Абенаки",
    "Mi'kmaq": "Микмак",
    "Zuni": "Зуни",
    "Mapudungun": "Мапудунгун",
    "Nivkh": "Нивх",
    "Haida": "Хайда",
    "Cherokee": "Чероки",
    "Nheengatu": "Нхеенгату",
    "Powhatan": "Поухатан",
    "Samogitian": "Жемайт",
    "Yaqui": "Яки",
    "Tsimshian": "Цимшиан",
    "Passamaquoddy": "Пассамакводди",
    "Mohave": "Мохаве",
    "Lushootseed": "Лушуцид",
    "Maori": "Маори",
    "Lhasa Tibetan": "Лхасын төвд",
    "Khoekhoe": "Хойхой",
    "Katu": "Кату",
    "Itelmen": "Ительмен",
    "Icelandic": "Исланд",
    "Elfdalian": "Эльвдалын",
    "Deg Xinag": "Дег Хинаг",
    "Chukchi": "Чукч",
    "Chulym": "Чулым",
    "Comanche": "Команч",
    "Beothuk": "Беотук",
    "Bashkir": "Башкир",
    "Selkup": "Селькуп",
    "Djeoromitxí": "Джеоромитши",
    "Yakut": "Якут",
    "Kokborok": "Кокборок",
    "Kabardian": "Кабардин",
    "Quileute": "Квилеут",
    "Tagalog": "Тагалог",
    "Pitjantjatjara": "Питжантжатжара",
    "Djambarrpuyngu": "Джамбарпуйнгу",
    "Siberian Yupik": "Сибирийн юпик",
    "Jeju": "Чежү",
    "Kikuyu": "Кикуюү",
    "Kumeyaay": "Кумеяай",
    "Guugu Yimithirr": "Гүүгү Йимитирр",
    "Aleut": "Алеут",
    "Maasai": "Масай",
    "Nuu-Chah-Nulth": "Нуу-Ча-Нулт",
    "Nez Perce": "Нез Перс",
    "ǃKung": "ǃКунг",
    "Xavante": "Шаванте",
    "Uyghur": "Уйгур",
    "Sumerian": "Шумер",
    "Rusyn": "Русин",
    "Basque": "Баск",
    "Welsh": "Уэльс",
    "Quapaw": "Квапау",
    "Tsez": "Цез",
    "Tabasaran": "Табасаран",
    "Nenets": "Ненец",
    "Ket": "Кет",
    "O'odham": "О'одхам",
    "Hawaiian": "Хавай",
    "Kildin Sami": "Килдин саам",
    "Tlingit": "Тлингит",
    "Abkhaz": "Абхаз",
    "Shoshone": "Шошон",
    "Ainu": "Айну",
    "Aymara": "Аймара",
    "Dënesųłiné": "Денесулине",
    "Tsakhur": "Цахур",
    "Belarusian": "Беларусь",
    "Kolyma Yukaghir": "Колымын юкагир",
    "Yokuts": "Йокутс",
    "Kutenai": "Кутенай",
    "Adyghe": "Адыгэ",
    "Arapaho": "Арапахо",
    "Blackfoot": "Блэкфүт",
    "Buryat": "Буриад",
    "Chamorro": "Чаморро",
    "Dakota": "Дакота",
    "Evenki": "Эвенк",
    "Fijian": "Фижи",
    "Gwich'in": "Гвичин",
    "Hopi": "Хопи",
    "Igbo": "Игбо",
    "Jingpo": "Жингпо",
    "Kalaallisut": "Калааллисут",
    "Lakota": "Лакота",
    "Mansi": "Манси",
    "Naxi": "Накси",
    "Ojibwe": "Ожибве",
    "Pawnee": "Пауни",
    "Rapanui": "Рапануи",
    "Sandawe": "Сандаве",
    "Tuvan": "Тува",
    "Udmurt": "Удмурт",
    "Veps": "Вепс",
    "Warlpiri": "Варлпири",
    "Xhosa": "Коса",
    "Yoruba": "Йоруба",
    "Zhuang": "Жуан",
    "Zulu": "Зулу",
    "Hadza": "Хадза",
    "Khanty": "Ханты",
    "Rohingya": "Рохинжа",
    "Scots Gaelic": "Шотланд гаэл",
    "Koryak": "Коряк",
    "Nganasan": "Нганасан",
    "Kalmyk": "Хальмг",
    "Komi": "Коми",
    "Yurok": "Юрок",
    "Chinook": "Чинук",
    "Guarani": "Гуарани",
    "Caddo": "Каддо",
    "Wichita": "Вичита",
    "Keres": "Керес",
    "Muscogee": "Маскоги",
    "Kiliwa": "Килива",
    "Pirahã": "Пираха",
    "Chechen": "Чечен",
    "Alyutor": "Алютор",
    "Sirenik": "Сирэникийн юпик",
  },
  "Japanese": {
      "Nahuatl": "ナワトル語",
      "Quechua": "ケチュア語",
      "Kwak'wala": "クワクワラ語",
      "Navajo": "ナバホ語",
      "Yucatec Mayan": "ユカタン・マヤ語",
      "Inuktitut": "イヌクティトゥット語",
      "Mohawk": "モホーク語",
      "Cree": "クリー語",
      "Abenaki": "アベナキ語",
      "Mi'kmaq": "ミクマク語",
      "Zuni": "ズニ語",
      "Mapudungun": "マプドゥングン語",
      "Nivkh": "ニヴフ語",
      "Haida": "ハイダ語",
      "Cherokee": "チェロキー語",
      "Nheengatu": "ニェエンガトゥ語",
      "Powhatan": "パウハタン語",
      "Samogitian": "サモギティア語",
      "Yaqui": "ヤキ語",
      "Tsimshian": "ツィムシアン語",
      "Passamaquoddy": "パサマコディ語",
      "Mohave": "モハーベ語",
      "Lushootseed": "ルショーツィード語",
      "Maori": "マオリ語",
      "Lhasa Tibetan": "ラサ・チベット語",
      "Khoekhoe": "コイコイ語",
      "Katu": "カトゥ語",
      "Itelmen": "イテリメン語",
      "Icelandic": "アイスランド語",
      "Elfdalian": "エルヴダーレン語",
      "Deg Xinag": "デグ・ヒナグ語",
      "Chukchi": "チュクチ語",
      "Chulym": "チュルィム語",
      "Comanche": "コマンチ語",
      "Beothuk": "ベオサク語",
      "Bashkir": "バシキール語",
      "Selkup": "セリクプ語",
      "Djeoromitxí": "ジェオロミチ語",
      "Yakut": "ヤクート語",
      "Kokborok": "コクボロク語",
      "Kabardian": "カバルダ語",
      "Quileute": "クィレウテ語",
      "Tagalog": "タガログ語",
      "Pitjantjatjara": "ピチャンチャチャラ語",
      "Djambarrpuyngu": "ジャンバルプユング語",
      "Siberian Yupik": "シベリア・ユピック語",
      "Jeju": "チェジュ語",
      "Kikuyu": "キクユ語",
      "Kumeyaay": "クメヤイ語",
      "Guugu Yimithirr": "ググ・イミディル語",
      "Aleut": "アリュート語",
      "Maasai": "マサイ語",
      "Nuu-Chah-Nulth": "ヌーチャーヌルス語",
      "Nez Perce": "ネズパース語",
      "ǃKung": "クン語",
      "Xavante": "シャバンテ語",
      "Uyghur": "ウイグル語",
      "Sumerian": "シュメール語",
      "Rusyn": "ルシン語",
      "Zuni": "ズニ語",
      "Basque": "バスク語",
      "Welsh": "ウェールズ語",
      "Quapaw": "クアポー語",
      "Tsez": "ツェズ語",
      "Tabasaran": "タバサラン語",
      "Nenets": "ネネツ語",
      "Ket": "ケット語",
      "O'odham": "オオダム語",
      "Hawaiian": "ハワイ語",
      "Kildin Sami": "キルディン・サーミ語",
      "Tlingit": "トリンギット語",
      "Abkhaz": "アブハズ語",
      "Shoshone": "ショショニ語",
      "Ainu": "アイヌ語",
      "Aymara": "アイマラ語",
      "Dënesųłiné": "デネスリネ語",
      "Tsakhur": "ツァフル語",
      "Belarusian": "ベラルーシ語",
      "Kolyma Yukaghir": "コリマ・ユカギル語",
      "Yokuts": "ヨクーツ語",
      "Kutenai": "クテナイ語",
      "Adyghe": "アディゲ語",
      "Arapaho": "アラパホ語",
      "Blackfoot": "ブラックフット語",
      "Buryat": "ブリヤート語",
      "Chamorro": "チャモロ語",
      "Dakota": "ダコタ語",
      "Evenki": "エヴェンキ語",
      "Fijian": "フィジー語",
      "Gwich'in": "グウィッチン語",
      "Hopi": "ホピ語",
      "Igbo": "イボ語",
      "Jingpo": "ジンポー語",
      "Kalaallisut": "グリーンランド語",
      "Lakota": "ラコタ語",
      "Mansi": "マンシ語",
      "Naxi": "ナシ語",
      "Ojibwe": "オジブワ語",
      "Pawnee": "ポーニー語",
      "Rapanui": "ラパヌイ語",
      "Sandawe": "サンダウェ語",
      "Tuvan": "トゥバ語",
      "Udmurt": "ウドムルト語",
      "Veps": "ヴェプス語",
      "Warlpiri": "ワルピリ語",
      "Xhosa": "コサ語",
      "Yoruba": "ヨルバ語",
      "Zhuang": "チワン語",
      "Zulu": "ズールー語",
      "Hadza": "ハッザ語",
      "Khanty": "ハンティ語",
      "Rohingya": "ロヒンギャ語",
      "Scots Gaelic": "スコットランド・ゲール語",
      "Koryak": "コリャーク語",
      "Nganasan": "ガナサン語",
      "Kalmyk": "カルムイク語",
      "Komi": "コミ語",
      "Yurok": "ユロク語",
      "Chinook": "チヌーク語",
      "Guarani": "グアラニー語",
      "Caddo": "キャド語",
      "Wichita": "ウィチタ語",
      "Keres": "ケレス語",
      "Muscogee": "マスコギー語",
      "Kiliwa": "キリワ語",
      "Pirahã": "ピラハン語",
      "Chechen": "チェチェン語",
      "Alyutor": "アリュートル語",
      "Sirenik": "シレニク語",
    },
    "Spanish": {
        "Nahuatl": "Náhuatl",
        "Quechua": "Quechua",
        "Kwak'wala": "Kwak'wala",
        "Navajo": "Navajo",
        "Yucatec Mayan": "Maya Yucateco",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Cree",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mi'kmaq",
        "Zuni": "Zuñi",
        "Mapudungun": "Mapudungún",
        "Nivkh": "Nivkh",
        "Haida": "Haida",
        "Cherokee": "Cherokee",
        "Nheengatu": "Ñeengatú",
        "Powhatan": "Powhatan",
        "Samogitian": "Samogitiano",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy",
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maorí",
        "Lhasa Tibetan": "Tibetano de Lhasa",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmen",
        "Icelandic": "Islandés",
        "Elfdalian": "Elfdaliano",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Chukchi",
        "Chulym": "Chulym",
        "Comanche": "Comanche",
        "Beothuk": "Beothuk",
        "Bashkir": "Bashkir",
        "Selkup": "Selkup",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Yakuto",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabardiano",
        "Quileute": "Quileute",
        "Tagalog": "Tagalo",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Yupik Siberiano",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuyu",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleutiano",
        "Maasai": "Masái",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez Perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Uigur",
        "Sumerian": "Sumerio",
        "Rusyn": "Rusino",
        "Basque": "Euskera",
        "Welsh": "Galés",
        "Quapaw": "Quapaw",
        "Tsez": "Tsez",
        "Tabasaran": "Tabasarano",
        "Nenets": "Nenets",
        "Ket": "Ket",
        "O'odham": "O'odham",
        "Hawaiian": "Hawaiano",
        "Kildin Sami": "Sami de Kildin",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abjasio",
        "Shoshone": "Shoshone",
        "Ainu": "Ainu",
        "Aymara": "Aimara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Tsajur",
        "Belarusian": "Bielorruso",
        "Kolyma Yukaghir": "Yukagir de Kolyma",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adigué",
        "Arapaho": "Arapaho",
        "Blackfoot": "Pies Negros",
        "Buryat": "Buriato",
        "Chamorro": "Chamorro",
        "Dakota": "Dakota",
        "Evenki": "Evenki",
        "Fijian": "Fiyiano",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Jingpo",
        "Kalaallisut": "Groenlandés",
        "Lakota": "Lakota",
        "Mansi": "Mansi",
        "Naxi": "Naxi",
        "Ojibwe": "Ojibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuvano",
        "Udmurt": "Udmurto",
        "Veps": "Vepsio",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Yoruba",
        "Zhuang": "Zhuang",
        "Zulu": "Zulú",
        "Hadza": "Hadza",
        "Khanty": "Khanty",
        "Rohingya": "Rohinyá",
        "Scots Gaelic": "Gaélico escocés",
        "Koryak": "Koriako",
        "Nganasan": "Nganasán",
        "Kalmyk": "Kalmuko",
        "Komi": "Komi",
        "Yurok": "Yurok",
        "Chinook": "Chinook",
        "Guarani": "Guaraní",
        "Caddo": "Caddo",
        "Wichita": "Wichita",
        "Keres": "Keres",
        "Muscogee": "Muscogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Chechen": "Checheno",
        "Alyutor": "Aliutor",
        "Sirenik": "Sirenik",
      },
    "Chinese": {
        "Nahuatl": "纳瓦特尔语",
        "Quechua": "克丘亚语",
        "Kwak'wala": "夸夸瓦拉语",
        "Navajo": "纳瓦霍语",
        "Yucatec Mayan": "尤卡坦玛雅语",
        "Inuktitut": "因纽特语",
        "Mohawk": "莫霍克语",
        "Cree": "克里语",
        "Abenaki": "阿贝纳基语",
        "Mi'kmaq": "米克马克语",
        "Zuni": "祖尼语",
        "Mapudungun": "马普切语",
        "Nivkh": "尼夫赫语",
        "Haida": "海达语",
        "Cherokee": "切罗基语",
        "Nheengatu": "涅恩加图语",
        "Powhatan": "波瓦坦语",
        "Samogitian": "萨莫吉提亚语",
        "Yaqui": "雅基语",
        "Tsimshian": "特西姆希安语",
        "Passamaquoddy": "帕萨马科迪语",
        "Mohave": "莫哈维语",
        "Lushootseed": "卢舒特希德语",
        "Maori": "毛利语",
        "Lhasa Tibetan": "拉萨藏语",
        "Khoekhoe": "科伊科伊语",
        "Katu": "卡图语",
        "Itelmen": "伊特尔门语",
        "Icelandic": "冰岛语",
        "Elfdalian": "埃尔夫达利亚语",
        "Deg Xinag": "德格辛纳格语",
        "Chukchi": "楚科奇语",
        "Chulym": "楚雷姆语",
        "Comanche": "科曼奇语",
        "Beothuk": "贝奥图克语",
        "Bashkir": "巴什基尔语",
        "Selkup": "塞尔库普语",
        "Djeoromitxí": "杰奥罗米特希语",
        "Yakut": "雅库特语",
        "Kokborok": "科克博罗克语",
        "Kabardian": "卡巴尔达语",
        "Quileute": "奎勒尤特语",
        "Tagalog": "他加禄语",
        "Pitjantjatjara": "皮坦贾塔贾拉语",
        "Djambarrpuyngu": "詹巴普因古语",
        "Siberian Yupik": "西伯利亚尤皮克语",
        "Jeju": "济州语",
        "Kikuyu": "基库尤语",
        "Kumeyaay": "库梅亚伊语",
        "Guugu Yimithirr": "古古依米蒂尔语",
        "Aleut": "阿留申语",
        "Maasai": "马赛语",
        "Nuu-Chah-Nulth": "努查努特语",
        "Nez Perce": "内兹珀斯语",
        "ǃKung": "!昆语",
        "Xavante": "沙万特语",
        "Uyghur": "维吾尔语",
        "Sumerian": "苏美尔语",
        "Rusyn": "卢森尼亚语",
        "Basque": "巴斯克语",
        "Welsh": "威尔士语",
        "Quapaw": "夸波语",
        "Tsez": "特塞兹语",
        "Tabasaran": "塔巴萨兰语",
        "Nenets": "涅涅茨语",
        "Ket": "克特语",
        "O'odham": "奥德汉语",
        "Hawaiian": "夏威夷语",
        "Kildin Sami": "基尔丁萨米语",
        "Tlingit": "特林吉特语",
        "Abkhaz": "阿布哈兹语",
        "Shoshone": "肖肖尼语",
        "Ainu": "阿伊努语",
        "Aymara": "艾马拉语",
        "Dënesųłiné": "德内苏林语",
        "Tsakhur": "察卡胡尔语",
        "Belarusian": "白俄罗斯语",
        "Kolyma Yukaghir": "科雷马尤卡吉尔语",
        "Yokuts": "约库特语",
        "Kutenai": "库特奈语",
        "Adyghe": "阿迪格语",
        "Arapaho": "阿拉帕霍语",
        "Blackfoot": "黑脚语",
        "Buryat": "布里亚特语",
        "Chamorro": "查莫罗语",
        "Dakota": "达科他语",
        "Evenki": "鄂温克语",
        "Fijian": "斐济语",
        "Gwich'in": "吉维钦语",
        "Hopi": "霍皮语",
        "Igbo": "伊博语",
        "Jingpo": "景颇语",
        "Kalaallisut": "格陵兰语",
        "Lakota": "拉科塔语",
        "Mansi": "曼西语",
        "Naxi": "纳西语",
        "Ojibwe": "奥吉布瓦语",
        "Pawnee": "波尼语",
        "Rapanui": "拉帕努伊语",
        "Sandawe": "桑达韦语",
        "Tuvan": "图瓦语",
        "Udmurt": "乌德穆尔特语",
        "Veps": "维普斯语",
        "Warlpiri": "沃尔皮里语",
        "Xhosa": "科萨语",
        "Yoruba": "约鲁巴语",
        "Zhuang": "壮语",
        "Zulu": "祖鲁语",
        "Hadza": "哈扎语",
        "Khanty": "汉特语",
        "Rohingya": "罗兴亚语",
        "Scots Gaelic": "苏格兰盖尔语",
        "Koryak": "科里亚克语",
        "Nganasan": "恩加纳桑语",
        "Kalmyk": "卡尔梅克语",
        "Komi": "科米语",
        "Yurok": "尤洛克语",
        "Chinook": "奇努克语",
        "Guarani": "瓜拉尼语",
        "Caddo": "卡多语",
        "Wichita": "威奇托语",
        "Keres": "克雷斯语",
        "Muscogee": "马斯科吉语",
        "Kiliwa": "基利瓦语",
        "Pirahã": "皮拉罕语",
        "Chechen": "车臣语",
        "Alyutor": "阿留托尔语",
        "Sirenik": "锡伦尼克语",
      },
      "Korean": {
        "Nahuatl": "나와틀어",
        "Quechua": "케추아어", 
        "Kwak'wala": "콰콰왈라어",
        "Navajo": "나바호어",
        "Yucatec Mayan": "유카탄 마야어",
        "Inuktitut": "이누크티투트어",
        "Mohawk": "모호크어",
        "Cree": "크리어",
        "Abenaki": "아베나키어",
        "Mi'kmaq": "미크맥어",
        "Zuni": "주니어",
        "Mapudungun": "마푸둔군어",
        "Nivkh": "니브흐어",
        "Haida": "하이다어",
        "Cherokee": "체로키어",
        "Nheengatu": "네엥가투어",
        "Powhatan": "포와탄어",
        "Samogitian": "사모기티아어",
        "Yaqui": "야키어",
        "Tsimshian": "침시안어",
        "Passamaquoddy": "파사마쿼디어",
        "Mohave": "모하비어",
        "Lushootseed": "루슈트시드어",
        "Maori": "마오리어",
        "Lhasa Tibetan": "라사 티베트어",
        "Khoekhoe": "코이코이어",
        "Katu": "카투어",
        "Itelmen": "이텔멘어",
        "Icelandic": "아이슬란드어",
        "Elfdalian": "엘브달리아어",
        "Deg Xinag": "데그 시나그어",
        "Chukchi": "추크치어",
        "Chulym": "출림어",
        "Comanche": "코만치어",
        "Beothuk": "베오투크어",
        "Bashkir": "바시키르어",
        "Selkup": "셀쿠프어",
        "Djeoromitxí": "제오로미치어",
        "Yakut": "야쿠트어",
        "Kokborok": "콕보록어",
        "Kabardian": "카바르디어",
        "Quileute": "퀼류트어",
        "Tagalog": "타갈로그어",
        "Pitjantjatjara": "피찬차차라어",
        "Djambarrpuyngu": "잠바르푸인구어",
        "Siberian Yupik": "시베리아 유피크어",
        "Jeju": "제주어",
        "Kikuyu": "키쿠유어",
        "Kumeyaay": "쿠메야이어",
        "Guugu Yimithirr": "구구 이미티르어",
        "Aleut": "알류트어",
        "Maasai": "마사이어",
        "Nuu-Chah-Nulth": "누차눌스어",
        "Nez Perce": "네즈퍼스어",
        "ǃKung": "!쿵어",
        "Xavante": "샤반테어",
        "Uyghur": "위구르어",
        "Sumerian": "수메르어",
        "Rusyn": "루신어",
        "Basque": "바스크어",
        "Welsh": "웨일스어",
        "Quapaw": "콰포어",
        "Tsez": "체즈어",
        "Tabasaran": "타바사란어",
        "Nenets": "네네츠어",
        "Ket": "케트어",
        "O'odham": "오오담어",
        "Hawaiian": "하와이어",
        "Kildin Sami": "킬딘 사미어",
        "Tlingit": "틀링깃어",
        "Abkhaz": "압하즈어",
        "Shoshone": "쇼숀어",
        "Ainu": "아이누어",
        "Aymara": "아이마라어",
        "Dënesųłiné": "데네수린어",
        "Tsakhur": "차쿠르어",
        "Belarusian": "벨라루스어",
        "Kolyma Yukaghir": "콜리마 유카기르어",
        "Yokuts": "요쿠츠어",
        "Kutenai": "쿠테나이어",
        "Adyghe": "아디게어",
        "Arapaho": "아라파호어",
        "Blackfoot": "블랙풋어",
        "Buryat": "부랴트어",
        "Chamorro": "차모로어",
        "Dakota": "다코타어",
        "Evenki": "에벤키어",
        "Fijian": "피지어",
        "Gwich'in": "그위친어",
        "Hopi": "호피어",
        "Igbo": "이그보어",
        "Jingpo": "징포어",
        "Kalaallisut": "칼랄리수트어",
        "Lakota": "라코타어",
        "Mansi": "만시어",
        "Naxi": "나시어",
        "Ojibwe": "오지브웨어",
        "Pawnee": "포니어",
        "Rapanui": "라파누이어",
        "Sandawe": "산다웨어",
        "Tuvan": "투바어",
        "Udmurt": "우드무르트어",
        "Veps": "벱스어",
        "Warlpiri": "왈피리어",
        "Xhosa": "코사어",
        "Yoruba": "요루바어",
        "Zhuang": "좡어",
        "Zulu": "줄루어",
        "Hadza": "하드자어",
        "Khanty": "한티어",
        "Rohingya": "로힝야어",
        "Scots Gaelic": "스코츠 게일어",
        "Koryak": "코랴크어",
        "Nganasan": "응가나산어",
        "Kalmyk": "칼미크어",
        "Komi": "코미어",
        "Yurok": "유록어",
        "Chinook": "치누크어",
        "Guarani": "과라니어",
        "Caddo": "캐도어",
        "Wichita": "위치타어",
        "Keres": "케레스어",
        "Muscogee": "머스코지어",
        "Kiliwa": "킬리와어",
        "Pirahã": "피라한어",
        "Chechen": "체첸어",
        "Alyutor": "알류토르어",
        "Sirenik": "시레니크어",
      },
    "German": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Quechua",
        "Kwak'wala": "Kwak'wala",
        "Navajo": "Navajo",
        "Yucatec Mayan": "Yukatekisches Maya",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Cree",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mi'kmaq",
        "Zuni": "Zuni",
        "Mapudungun": "Mapudungun",
        "Nivkh": "Niwchisch",
        "Haida": "Haida",
        "Cherokee": "Cherokee",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Samogitisch",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy",
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maori",
        "Lhasa Tibetan": "Lhasa-Tibetisch",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmenisch",
        "Icelandic": "Isländisch",
        "Elfdalian": "Älvdalisch",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Tschuktschisch",
        "Chulym": "Tschulymisch",
        "Comanche": "Komantschisch",
        "Beothuk": "Beothuk",
        "Bashkir": "Baschkirisch",
        "Selkup": "Selkupisch",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Jakutisch",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabardinisch",
        "Quileute": "Quileute",
        "Tagalog": "Tagalog",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Sibirisches Yupik",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuyu",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleutisch",
        "Maasai": "Massai",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez Perce",
        "ǃKung": "!Kung",
        "Xavante": "Xavante",
        "Uyghur": "Uigurisch",
        "Sumerian": "Sumerisch",
        "Rusyn": "Russinisch",
        "Basque": "Baskisch",
        "Welsh": "Walisisch",
        "Quapaw": "Quapaw",
        "Tsez": "Tsezisch",
        "Tabasaran": "Tabasaranisch",
        "Nenets": "Nenzisch",
        "Ket": "Ketisch",
        "O'odham": "O'odham",
        "Hawaiian": "Hawaiianisch",
        "Kildin Sami": "Kildinsamisch",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abchasisch",
        "Shoshone": "Schoschonisch",
        "Ainu": "Ainu",
        "Aymara": "Aymara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Zachurisch",
        "Belarusian": "Weißrussisch",
        "Kolyma Yukaghir": "Kolyma-Jukagirisch",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adygeisch",
        "Arapaho": "Arapaho",
        "Blackfoot": "Schwarzfuß-Indianisch",
        "Buryat": "Burjatisch",
        "Chamorro": "Chamorro",
        "Dakota": "Dakota",
        "Evenki": "Ewenkisch",
        "Fijian": "Fidschianisch",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Jingpo",
        "Kalaallisut": "Grönländisch",
        "Lakota": "Lakota",
        "Mansi": "Mansisch",
        "Naxi": "Naxi",
        "Ojibwe": "Ojibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuwinisch",
        "Udmurt": "Udmurtisch",
        "Veps": "Wepsisch",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Yoruba",
        "Zhuang": "Zhuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Chantisch",
        "Rohingya": "Rohingya",
        "Scots Gaelic": "Schottisch-Gälisch",
        "Koryak": "Korjakisch",
        "Nganasan": "Nganasanisch",
        "Kalmyk": "Kalmückisch",
        "Komi": "Komi",
        "Yurok": "Yurok",
        "Chinook": "Chinook",
        "Guarani": "Guaraní",
        "Caddo": "Caddo",
        "Wichita": "Wichita",
        "Keres": "Keres",
        "Muscogee": "Muskogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Chechen": "Tschetschenisch",
        "Alyutor": "Aljutorisch",
        "Sirenik": "Sirenikisch",
      },
    "Vietnamese": {
        "Nahuatl": "Tiếng Nahuatl",
        "Quechua": "Tiếng Quechua", 
        "Kwak'wala": "Tiếng Kwak'wala",
        "Navajo": "Tiếng Navajo",
        "Yucatec Mayan": "Tiếng Maya Yucatec",
        "Inuktitut": "Tiếng Inuktitut",
        "Mohawk": "Tiếng Mohawk",
        "Cree": "Tiếng Cree",
        "Abenaki": "Tiếng Abenaki",
        "Mi'kmaq": "Tiếng Mi'kmaq",
        "Zuni": "Tiếng Zuni",
        "Mapudungun": "Tiếng Mapudungun",
        "Nivkh": "Tiếng Nivkh",
        "Haida": "Tiếng Haida",
        "Cherokee": "Tiếng Cherokee",
        "Nheengatu": "Tiếng Nheengatu",
        "Powhatan": "Tiếng Powhatan",
        "Samogitian": "Tiếng Samogitia",
        "Yaqui": "Tiếng Yaqui",
        "Tsimshian": "Tiếng Tsimshian",
        "Passamaquoddy": "Tiếng Passamaquoddy",
        "Mohave": "Tiếng Mohave",
        "Lushootseed": "Tiếng Lushootseed",
        "Maori": "Tiếng Maori",
        "Lhasa Tibetan": "Tiếng Tây Tạng Lhasa",
        "Khoekhoe": "Tiếng Khoekhoe",
        "Katu": "Tiếng Katu",
        "Itelmen": "Tiếng Itelmen",
        "Icelandic": "Tiếng Iceland",
        "Elfdalian": "Tiếng Elfdalian",
        "Deg Xinag": "Tiếng Deg Xinag",
        "Chukchi": "Tiếng Chukchi",
        "Chulym": "Tiếng Chulym",
        "Comanche": "Tiếng Comanche",
        "Beothuk": "Tiếng Beothuk",
        "Bashkir": "Tiếng Bashkir",
        "Selkup": "Tiếng Selkup",
        "Djeoromitxí": "Tiếng Djeoromitxí",
        "Yakut": "Tiếng Yakut",
        "Kokborok": "Tiếng Kokborok",
        "Kabardian": "Tiếng Kabardian",
        "Quileute": "Tiếng Quileute",
        "Tagalog": "Tiếng Tagalog",
        "Pitjantjatjara": "Tiếng Pitjantjatjara",
        "Djambarrpuyngu": "Tiếng Djambarrpuyngu",
        "Siberian Yupik": "Tiếng Yupik Siberia",
        "Jeju": "Tiếng Jeju",
        "Kikuyu": "Tiếng Kikuyu",
        "Kumeyaay": "Tiếng Kumeyaay",
        "Guugu Yimithirr": "Tiếng Guugu Yimithirr",
        "Aleut": "Tiếng Aleut",
        "Maasai": "Tiếng Maasai",
        "Nuu-Chah-Nulth": "Tiếng Nuu-Chah-Nulth",
        "Nez Perce": "Tiếng Nez Perce",
        "ǃKung": "Tiếng ǃKung",
        "Xavante": "Tiếng Xavante",
        "Uyghur": "Tiếng Duy Ngô Nhĩ",
        "Sumerian": "Tiếng Sumer",
        "Rusyn": "Tiếng Rusyn",
        "Basque": "Tiếng Basque",
        "Welsh": "Tiếng Wales",
        "Quapaw": "Tiếng Quapaw",
        "Tsez": "Tiếng Tsez",
        "Tabasaran": "Tiếng Tabasaran",
        "Nenets": "Tiếng Nenets",
        "Ket": "Tiếng Ket",
        "O'odham": "Tiếng O'odham",
        "Hawaiian": "Tiếng Hawaii",
        "Kildin Sami": "Tiếng Kildin Sami",
        "Tlingit": "Tiếng Tlingit",
        "Abkhaz": "Tiếng Abkhaz",
        "Shoshone": "Tiếng Shoshone",
        "Ainu": "Tiếng Ainu",
        "Aymara": "Tiếng Aymara",
        "Dënesųłiné": "Tiếng Dënesųłiné",
        "Tsakhur": "Tiếng Tsakhur",
        "Belarusian": "Tiếng Belarus",
        "Kolyma Yukaghir": "Tiếng Yukaghir Kolyma",
        "Yokuts": "Tiếng Yokuts",
        "Kutenai": "Tiếng Kutenai",
        "Adyghe": "Tiếng Adyghe",
        "Arapaho": "Tiếng Arapaho",
        "Blackfoot": "Tiếng Blackfoot",
        "Buryat": "Tiếng Buryat",
        "Chamorro": "Tiếng Chamorro",
        "Dakota": "Tiếng Dakota",
        "Evenki": "Tiếng Evenki",
        "Fijian": "Tiếng Fiji",
        "Gwich'in": "Tiếng Gwich'in",
        "Hopi": "Tiếng Hopi",
        "Igbo": "Tiếng Igbo",
        "Jingpo": "Tiếng Jingpo",
        "Kalaallisut": "Tiếng Kalaallisut",
        "Lakota": "Tiếng Lakota",
        "Mansi": "Tiếng Mansi",
        "Naxi": "Tiếng Naxi",
        "Ojibwe": "Tiếng Ojibwe",
        "Pawnee": "Tiếng Pawnee",
        "Rapanui": "Tiếng Rapanui",
        "Sandawe": "Tiếng Sandawe",
        "Tuvan": "Tiếng Tuva",
        "Udmurt": "Tiếng Udmurt",
        "Veps": "Tiếng Veps",
        "Warlpiri": "Tiếng Warlpiri",
        "Xhosa": "Tiếng Xhosa",
        "Yoruba": "Tiếng Yoruba",
        "Zhuang": "Tiếng Choang",
        "Zulu": "Tiếng Zulu",
        "Hadza": "Tiếng Hadza",
        "Khanty": "Tiếng Khanty",
        "Rohingya": "Tiếng Rohingya",
        "Scots Gaelic": "Tiếng Gael Scotland",
        "Koryak": "Tiếng Koryak",
        "Nganasan": "Tiếng Nganasan",
        "Kalmyk": "Tiếng Kalmyk",
        "Komi": "Tiếng Komi",
        "Yurok": "Tiếng Yurok",
        "Chinook": "Tiếng Chinook",
        "Guarani": "Tiếng Guarani",
        "Caddo": "Tiếng Caddo",
        "Wichita": "Tiếng Wichita",
        "Keres": "Tiếng Keres",
        "Muscogee": "Tiếng Muscogee",
        "Kiliwa": "Tiếng Kiliwa",
        "Pirahã": "Tiếng Pirahã",
        "Alyutor": "Tiếng Alyutor",
        "Sirenik": "Tiếng Sirenik",
        "Chechen": "Tiếng Chechnya",
      },
    "Swedish": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Quechua",
        "Kwak'wala": "Kwak'wala",
        "Navajo": "Navajo",
        "Yucatec Mayan": "Yukatekiska maya",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Cree",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mi'kmaq",
        "Zuni": "Zuni",
        "Mapudungun": "Mapudungun",
        "Nivkh": "Nivkhiska",
        "Haida": "Haida",
        "Cherokee": "Cherokee",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Samogitiska",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy",
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maori",
        "Lhasa Tibetan": "Lhasa-tibetanska",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmenska",
        "Icelandic": "Isländska",
        "Elfdalian": "Älvdalska",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Tjuktjiska",
        "Chulym": "Tjulymiska",
        "Comanche": "Comanche",
        "Beothuk": "Beothuk",
        "Bashkir": "Basjkiriska",
        "Selkup": "Selkupiska",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Jakutiska",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabardinska",
        "Quileute": "Quileute",
        "Tagalog": "Tagalog",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Sibirisk yupik",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuyu",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleutiska",
        "Maasai": "Massajiska",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Uiguriska",
        "Sumerian": "Sumeriska",
        "Rusyn": "Rusinska",
        "Basque": "Baskiska",
        "Welsh": "Walesiska",
        "Quapaw": "Quapaw",
        "Tsez": "Tseziska",
        "Tabasaran": "Tabasaranska",
        "Nenets": "Nentsiska",
        "Ket": "Ketiska",
        "O'odham": "O'odham",
        "Hawaiian": "Hawaiiska",
        "Kildin Sami": "Kildinsamiska",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abchaziska",
        "Shoshone": "Shoshoniska",
        "Ainu": "Ainu",
        "Aymara": "Aymara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Tsachuriska",
        "Belarusian": "Belarusiska",
        "Kolyma Yukaghir": "Kolymajukagiriska",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adygeiska",
        "Arapaho": "Arapaho",
        "Blackfoot": "Svartfotska",
        "Buryat": "Burjatiska",
        "Chamorro": "Chamorro",
        "Dakota": "Dakota",
        "Evenki": "Evenkiska",
        "Fijian": "Fijianska",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Jingpo",
        "Kalaallisut": "Grönländska",
        "Lakota": "Lakota",
        "Mansi": "Mansiska",
        "Naxi": "Naxi",
        "Ojibwe": "Ojibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuvinska",
        "Udmurt": "Udmurtiska",
        "Veps": "Vepsiska",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Yoruba",
        "Zhuang": "Zhuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Chantiska",
        "Rohingya": "Rohingya",
        "Scots Gaelic": "Skotsk gäliska",
        "Koryak": "Korjakiska",
        "Nganasan": "Nganasanska",
        "Kalmyk": "Kalmuckiska",
        "Komi": "Komiska",
        "Yurok": "Yurok",
        "Chinook": "Chinook",
        "Guarani": "Guarani",
        "Caddo": "Caddo",
        "Wichita": "Wichita",
        "Keres": "Keres",
        "Muscogee": "Muscogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Alyutor": "Aljutoriska",
        "Sirenik": "Sirenikiska",
        "Chechen": "Tjetjenska",
      },
    "Danish": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Quechua",
        "Kwak'wala": "Kwak'wala",
        "Navajo": "Navajo",
        "Yucatec Mayan": "Yucatekisk maya",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Cree",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mi'kmaq",
        "Zuni": "Zuni",
        "Mapudungun": "Mapudungun",
        "Nivkh": "Nivkhisk",
        "Haida": "Haida",
        "Cherokee": "Cherokee",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Samogitisk",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy",
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maori",
        "Lhasa Tibetan": "Lhasa-tibetansk",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmen",
        "Icelandic": "Islandsk",
        "Elfdalian": "Älvdalsk",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Tjuktjisk",
        "Chulym": "Tjulymisk",
        "Comanche": "Comanche",
        "Beothuk": "Beothuk",
        "Bashkir": "Basjkirisk",
        "Selkup": "Selkupisk",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Jakutisk",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabardisk",
        "Quileute": "Quileute",
        "Tagalog": "Tagalog",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Sibirisk yupik",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuyu",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleutisk",
        "Maasai": "Masai",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Uigurisk",
        "Sumerian": "Sumerisk",
        "Rusyn": "Rusinsk",
        "Basque": "Baskisk",
        "Welsh": "Walisisk",
        "Quapaw": "Quapaw",
        "Tsez": "Tsezisk",
        "Tabasaran": "Tabasaransk",
        "Nenets": "Nenetsk",
        "Ket": "Ketisk",
        "O'odham": "O'odham",
        "Hawaiian": "Hawaiiansk",
        "Kildin Sami": "Kildinsamisk",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abkhazisk",
        "Shoshone": "Shoshonisk",
        "Ainu": "Ainu",
        "Aymara": "Aymara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Tsakhurisk",
        "Belarusian": "Hviderussisk",
        "Kolyma Yukaghir": "Kolymajukagirisk",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adygheisk",
        "Arapaho": "Arapaho",
        "Blackfoot": "Sortfodsindianisk",
        "Buryat": "Burjatisk",
        "Chamorro": "Chamorro",
        "Dakota": "Dakota",
        "Evenki": "Evenkisk",
        "Fijian": "Fijiansk",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Jingpo",
        "Kalaallisut": "Grønlandsk",
        "Lakota": "Lakota",
        "Mansi": "Mansisk",
        "Naxi": "Naxi",
        "Ojibwe": "Ojibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuvansk",
        "Udmurt": "Udmurtisk",
        "Veps": "Vepsisk",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Yoruba",
        "Zhuang": "Zhuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Khantisk",
        "Rohingya": "Rohingya",
        "Scots Gaelic": "Skotsk gælisk",
        "Koryak": "Korjakisk",
        "Nganasan": "Nganasansk",
        "Kalmyk": "Kalmykisk",
        "Komi": "Komisk",
        "Yurok": "Yurok",
        "Chinook": "Chinook",
        "Guarani": "Guarani",
        "Caddo": "Caddo",
        "Wichita": "Wichita",
        "Keres": "Keres",
        "Muscogee": "Muscogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Alyutor": "Aljutorisk",
        "Sirenik": "Sirenikisk",
        "Chechen": "Tjetjensk",
    },
    "Hungarian": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Kecsua",
        "Kwak'wala": "Kvakiutl",
        "Navajo": "Navahó",
        "Yucatec Mayan": "Yucatéki maja",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Krí",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mikmak",
        "Zuni": "Zuni",
        "Mapudungun": "Mapucse",
        "Nivkh": "Nivh",
        "Haida": "Haida",
        "Cherokee": "Cseroki",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Szamogit",
        "Yaqui": "Jaki",
        "Tsimshian": "Cimshian",
        "Passamaquoddy": "Passzamakvoddi",
        "Mohave": "Mohave",
        "Lushootseed": "Lusucíd",
        "Maori": "Maori",
        "Lhasa Tibetan": "Lhászai tibeti",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmen",
        "Icelandic": "Izlandi",
        "Elfdalian": "Älvdaleni",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Csukcs",
        "Chulym": "Csulyim",
        "Comanche": "Komancs",
        "Beothuk": "Beothuk",
        "Bashkir": "Baskír",
        "Selkup": "Szölkup",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Jakut",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabard",
        "Quileute": "Quileute",
        "Tagalog": "Tagalog",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Szibériai jupik",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuju",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleut",
        "Maasai": "Maszáj",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Ujgur",
        "Sumerian": "Sumér",
        "Rusyn": "Ruszin",
        "Basque": "Baszk",
        "Welsh": "Walesi",
        "Quapaw": "Quapaw",
        "Tsez": "Tsez",
        "Tabasaran": "Tabasarán",
        "Nenets": "Nyenyec",
        "Ket": "Ket",
        "O'odham": "O'odham",
        "Hawaiian": "Hawaii",
        "Kildin Sami": "Kildin számi",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abház",
        "Shoshone": "Sosón",
        "Ainu": "Ainu",
        "Aymara": "Ajmara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Cahur",
        "Belarusian": "Belarusz",
        "Kolyma Yukaghir": "Kolima jukagír",
        "Yokuts": "Jokuc",
        "Kutenai": "Kutenai",
        "Adyghe": "Adigé",
        "Arapaho": "Arapahó",
        "Blackfoot": "Feketeláb",
        "Buryat": "Burját",
        "Chamorro": "Csamorro",
        "Dakota": "Dakota",
        "Evenki": "Evenki",
        "Fijian": "Fidzsi",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbó",
        "Jingpo": "Csingpo",
        "Kalaallisut": "Grönlandi",
        "Lakota": "Lakota",
        "Mansi": "Manysi",
        "Naxi": "Naxi",
        "Ojibwe": "Odzsibve",
        "Pawnee": "Póni",
        "Rapanui": "Rapanui",
        "Sandawe": "Szandave",
        "Tuvan": "Tuvai",
        "Udmurt": "Udmurt",
        "Veps": "Vepsze",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosza",
        "Yoruba": "Joruba",
        "Zhuang": "Csuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Hanti",
        "Rohingya": "Rohingja",
        "Scots Gaelic": "Skót gael",
        "Koryak": "Korják",
        "Nganasan": "Nganaszan",
        "Kalmyk": "Kalmük",
        "Komi": "Komi",
        "Yurok": "Jurok",
        "Chinook": "Csinuk",
        "Guarani": "Guarani",
        "Caddo": "Kadó",
        "Wichita": "Vicsita",
        "Keres": "Keresz",
        "Muscogee": "Muszkogi",
        "Kiliwa": "Kiliva",
        "Pirahã": "Pirahã",
        "Alyutor": "Aljutor",
        "Sirenik": "Szirenik",
        "Chechen": "Csecsen",
    },
    "Finnish": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Ketšua",
        "Kwak'wala": "Kwak'wala",
        "Navajo": "Navajo",
        "Yucatec Mayan": "Jukatanin maya",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Cree",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mi'kmaq",
        "Zuni": "Zuni",
        "Mapudungun": "Mapudungun",
        "Nivkh": "Nivhi",
        "Haida": "Haida",
        "Cherokee": "Cherokee",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Samogiitti",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy",
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maori",
        "Lhasa Tibetan": "Lhasan tiibet",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmeni",
        "Icelandic": "Islanti",
        "Elfdalian": "Älvdalen",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Tšuktši",
        "Chulym": "Tšulym",
        "Comanche": "Komantši",
        "Beothuk": "Beothuk",
        "Bashkir": "Baškiiri",
        "Selkup": "Selkuppi",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Jakuutti",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabardiini",
        "Quileute": "Quileute",
        "Tagalog": "Tagalog",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Siperian jupikki",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuju",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleutti",
        "Maasai": "Maasai",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez Perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Uiguuri",
        "Sumerian": "Sumeri",
        "Rusyn": "Ruteeni",
        "Basque": "Baski",
        "Welsh": "Kymri",
        "Quapaw": "Quapaw",
        "Tsez": "Tsez",
        "Tabasaran": "Tabasaran",
        "Nenets": "Nenetsi",
        "Ket": "Ket",
        "O'odham": "O'odham",
        "Hawaiian": "Havaiji",
        "Kildin Sami": "Kildininsaame",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abhaasi",
        "Shoshone": "Šošoni",
        "Ainu": "Ainu",
        "Aymara": "Aymara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Tsahuri",
        "Belarusian": "Valkovenäjä",
        "Kolyma Yukaghir": "Kolymanjukagiri",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adyge",
        "Arapaho": "Arapaho",
        "Blackfoot": "Mustajalka",
        "Buryat": "Burjaatti",
        "Chamorro": "Tšamorro",
        "Dakota": "Dakota",
        "Evenki": "Evenki",
        "Fijian": "Fidži",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Tšingpo",
        "Kalaallisut": "Grönlanti",
        "Lakota": "Lakota",
        "Mansi": "Mansi",
        "Naxi": "Naxi",
        "Ojibwe": "Odžibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuva",
        "Udmurt": "Udmurtti",
        "Veps": "Vepsä",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Joruba",
        "Zhuang": "Zhuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Hanti",
        "Rohingya": "Rohingya",
        "Scots Gaelic": "Gaeli",
        "Koryak": "Korjakki",
        "Nganasan": "Nganasani",
        "Kalmyk": "Kalmykki",
        "Komi": "Komi",
        "Yurok": "Jurok",
        "Chinook": "Tšinuk",
        "Guarani": "Guarani",
        "Caddo": "Caddo",
        "Wichita": "Wichita",
        "Keres": "Keres",
        "Muscogee": "Muscogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Alyutor": "Aljutor",
        "Sirenik": "Sirenik",
        "Chechen": "Tšetšeeni",
      },
    "Italian": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Quechua",
        "Kwak'wala": "Kwak'wala",
        "Navajo": "Navajo",
        "Yucatec Mayan": "Maya Yucateco",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Cree",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mi'kmaq",
        "Zuni": "Zuni",
        "Mapudungun": "Mapudungun",
        "Nivkh": "Nivkh",
        "Haida": "Haida",
        "Cherokee": "Cherokee",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Samogitico",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy",
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maori",
        "Lhasa Tibetan": "Tibetano di Lhasa",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmeno",
        "Icelandic": "Islandese",
        "Elfdalian": "Elfdaliano",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Ciukcio",
        "Chulym": "Ciulimo",
        "Comanche": "Comanche",
        "Beothuk": "Beothuk",
        "Bashkir": "Baschiro",
        "Selkup": "Selkupo",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Yakuto",
        "Kokborok": "Kokborok",
        "Kabardian": "Cabardino",
        "Quileute": "Quileute",
        "Tagalog": "Tagalog",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Yupik Siberiano",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuyu",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleuto",
        "Maasai": "Masai",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez Perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Uiguro",
        "Sumerian": "Sumero",
        "Rusyn": "Ruteno",
        "Basque": "Basco",
        "Welsh": "Gallese",
        "Quapaw": "Quapaw",
        "Tsez": "Tsez",
        "Tabasaran": "Tabasarano",
        "Nenets": "Nenets",
        "Ket": "Ket",
        "O'odham": "O'odham",
        "Hawaiian": "Hawaiano",
        "Kildin Sami": "Sami di Kildin",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abcaso",
        "Shoshone": "Shoshone",
        "Ainu": "Ainu",
        "Aymara": "Aymara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Tsakhur",
        "Belarusian": "Bielorusso",
        "Kolyma Yukaghir": "Yukaghiro di Kolyma",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adyghe",
        "Arapaho": "Arapaho",
        "Blackfoot": "Piedi Neri",
        "Buryat": "Buriato",
        "Chamorro": "Chamorro",
        "Dakota": "Dakota",
        "Evenki": "Evenki",
        "Fijian": "Figiano",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Jingpo",
        "Kalaallisut": "Groenlandese",
        "Lakota": "Lakota",
        "Mansi": "Mansi",
        "Naxi": "Naxi",
        "Ojibwe": "Ojibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuvano",
        "Udmurt": "Udmurto",
        "Veps": "Vepso",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Yoruba",
        "Zhuang": "Zhuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Khanty",
        "Rohingya": "Rohingya",
        "Scots Gaelic": "Gaelico scozzese",
        "Koryak": "Coriaco",
        "Nganasan": "Nganasan",
        "Kalmyk": "Calmucco",
        "Komi": "Komi",
        "Yurok": "Yurok",
        "Chinook": "Chinook",
        "Guarani": "Guaraní",
        "Caddo": "Caddo",
        "Wichita": "Wichita",
        "Keres": "Keres",
        "Muscogee": "Muscogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Alyutor": "Aliutor",
        "Sirenik": "Sirenik",
        "Chechen": "Ceceno",
    },
    "Polish": {
        "Nahuatl": "Nahuatl",
        "Quechua": "Keczua",
        "Kwak'wala": "Kwakiutl",
        "Navajo": "Nawaho",
        "Yucatec Mayan": "Majański jukatański",
        "Inuktitut": "Inuktitut",
        "Mohawk": "Mohawk",
        "Cree": "Kri",
        "Abenaki": "Abenaki",
        "Mi'kmaq": "Mikmak",
        "Zuni": "Zuni",
        "Mapudungun": "Mapudungun",
        "Nivkh": "Niwchijski",
        "Haida": "Haida",
        "Cherokee": "Czirokeski",
        "Nheengatu": "Nheengatu",
        "Powhatan": "Powhatan",
        "Samogitian": "Żmudzki",
        "Yaqui": "Yaqui",
        "Tsimshian": "Tsimshian",
        "Passamaquoddy": "Passamaquoddy", 
        "Mohave": "Mohave",
        "Lushootseed": "Lushootseed",
        "Maori": "Maoryski",
        "Lhasa Tibetan": "Tybetański lhaski",
        "Khoekhoe": "Khoekhoe",
        "Katu": "Katu",
        "Itelmen": "Itelmeski",
        "Icelandic": "Islandzki",
        "Elfdalian": "Elfdalski",
        "Deg Xinag": "Deg Xinag",
        "Chukchi": "Czukocki",
        "Chulym": "Czułymski",
        "Comanche": "Komancze",
        "Beothuk": "Beothuk",
        "Bashkir": "Baszkirski",
        "Selkup": "Selkupski",
        "Djeoromitxí": "Djeoromitxí",
        "Yakut": "Jakucki",
        "Kokborok": "Kokborok",
        "Kabardian": "Kabardyjski",
        "Quileute": "Quileute",
        "Tagalog": "Tagalski",
        "Pitjantjatjara": "Pitjantjatjara",
        "Djambarrpuyngu": "Djambarrpuyngu",
        "Siberian Yupik": "Jupik syberyjski",
        "Jeju": "Jeju",
        "Kikuyu": "Kikuju",
        "Kumeyaay": "Kumeyaay",
        "Guugu Yimithirr": "Guugu Yimithirr",
        "Aleut": "Aleucki",
        "Maasai": "Masajski",
        "Nuu-Chah-Nulth": "Nuu-chah-nulth",
        "Nez Perce": "Nez Perce",
        "ǃKung": "ǃKung",
        "Xavante": "Xavante",
        "Uyghur": "Ujgurski",
        "Sumerian": "Sumeryjski",
        "Rusyn": "Rusiński",
        "Basque": "Baskijski",
        "Welsh": "Walijski",
        "Quapaw": "Quapaw",
        "Tsez": "Cezyjski",
        "Tabasaran": "Tabasarański",
        "Nenets": "Nieniecki",
        "Ket": "Ketyjski",
        "O'odham": "O'odham",
        "Hawaiian": "Hawajski",
        "Kildin Sami": "Saamski kildiński",
        "Tlingit": "Tlingit",
        "Abkhaz": "Abchaski",
        "Shoshone": "Szoszoński",
        "Ainu": "Ajnuski",
        "Aymara": "Ajmara",
        "Dënesųłiné": "Dënesųłiné",
        "Tsakhur": "Cachurski",
        "Belarusian": "Białoruski",
        "Kolyma Yukaghir": "Jukagirski kołymski",
        "Yokuts": "Yokuts",
        "Kutenai": "Kutenai",
        "Adyghe": "Adygejski",
        "Arapaho": "Arapaho",
        "Blackfoot": "Czarnostopy",
        "Buryat": "Buriacki",
        "Chamorro": "Czamorro",
        "Dakota": "Dakota",
        "Evenki": "Ewenkijski",
        "Fijian": "Fidżyjski",
        "Gwich'in": "Gwich'in",
        "Hopi": "Hopi",
        "Igbo": "Igbo",
        "Jingpo": "Jingpo",
        "Kalaallisut": "Grenlandzki",
        "Lakota": "Lakota",
        "Mansi": "Mansyjski",
        "Naxi": "Naxi",
        "Ojibwe": "Odżibwe",
        "Pawnee": "Pawnee",
        "Rapanui": "Rapanui",
        "Sandawe": "Sandawe",
        "Tuvan": "Tuwiński",
        "Udmurt": "Udmurcki",
        "Veps": "Wepski",
        "Warlpiri": "Warlpiri",
        "Xhosa": "Xhosa",
        "Yoruba": "Joruba",
        "Zhuang": "Czuang",
        "Zulu": "Zulu",
        "Hadza": "Hadza",
        "Khanty": "Chantyjski",
        "Rohingya": "Rohingya",
        "Scots Gaelic": "Gaelicki szkocki",
        "Koryak": "Koriacki",
        "Nganasan": "Nganasański",
        "Kalmyk": "Kałmucki",
        "Komi": "Komi",
        "Yurok": "Jurok",
        "Chinook": "Czynuk",
        "Guarani": "Guarani",
        "Caddo": "Kaddo",
        "Wichita": "Wiczita",
        "Keres": "Keres",
        "Muscogee": "Muskogee",
        "Kiliwa": "Kiliwa",
        "Pirahã": "Pirahã",
        "Chechen": "Czeczeński",
        "Alyutor": "Alutorski",
        "Sirenik": "Sirenicki",
      },
      "Hindi": {
        "Nahuatl": "नाहुआत्ल",
        "Quechua": "केचुआ",
        "Kwak'wala": "क्वाक्वाला",
        "Navajo": "नावाहो",
        "Yucatec Mayan": "युकाटेक माया",
        "Inuktitut": "इनुक्टिटुट",
        "Mohawk": "मोहॉक",
        "Cree": "क्री",
        "Abenaki": "अबेनाकी",
        "Mi'kmaq": "मिक्माक",
        "Zuni": "जुनी",
        "Mapudungun": "मापुदुंगुन",
        "Nivkh": "निवख",
        "Haida": "हैदा",
        "Cherokee": "चेरोकी",
        "Nheengatu": "न्हेंगातु",
        "Powhatan": "पोव्हाटन",
        "Samogitian": "समोगितियन",
        "Yaqui": "याकी",
        "Tsimshian": "त्सिम्शियन",
        "Passamaquoddy": "पासामाक्वोडी",
        "Mohave": "मोहावे",
        "Lushootseed": "लुशूत्सीड",
        "Maori": "माओरी",
        "Lhasa Tibetan": "ल्हासा तिब्बती",
        "Khoekhoe": "खोएखोए",
        "Katu": "कातु",
        "Itelmen": "इतेल्मेन",
        "Icelandic": "आइसलैंडिक",
        "Elfdalian": "एल्फडालियन",
        "Deg Xinag": "देग शिनाग",
        "Chukchi": "चुकची",
        "Chulym": "चुल्यम",
        "Comanche": "कोमांचे",
        "Beothuk": "बेओथुक",
        "Bashkir": "बशकीर",
        "Selkup": "सेल्कुप",
        "Djeoromitxí": "जेओरोमित्शी",
        "Yakut": "याकुत",
        "Kokborok": "कोकबोरोक",
        "Kabardian": "कबार्दियन",
        "Quileute": "क्विलेउते",
        "Tagalog": "तगालोग",
        "Pitjantjatjara": "पित्जन्त्जत्जरा",
        "Djambarrpuyngu": "जम्बर्रपुयन्गु",
        "Siberian Yupik": "साइबेरियन युपिक",
        "Jeju": "जेजू",
        "Kikuyu": "किकुयु",
        "Kumeyaay": "कुमेयाय",
        "Guugu Yimithirr": "गुगु यिमिथिर",
        "Aleut": "अलेउत",
        "Maasai": "मासाई",
        "Nuu-Chah-Nulth": "नू-चा-नुल्थ",
        "Nez Perce": "नेज़ पर्स",
        "ǃKung": "ǃकुंग",
        "Xavante": "शवांते",
        "Uyghur": "उइगुर",
        "Sumerian": "सुमेरियन",
        "Rusyn": "रुसिन",
        "Basque": "बास्क",
        "Welsh": "वेल्श",
        "Quapaw": "क्वापॉ",
        "Tsez": "त्सेज़",
        "Tabasaran": "तबसरन",
        "Nenets": "नेनेत्स",
        "Ket": "केत",
        "O'odham": "ओ'ओधम",
        "Hawaiian": "हवाई",
        "Kildin Sami": "किल्डिन सामी",
        "Tlingit": "त्लिंगित",
        "Abkhaz": "अब्खाज़",
        "Shoshone": "शोशोनी",
        "Ainu": "आइनू",
        "Aymara": "आयमारा",
        "Dënesųłiné": "देनेसुलिने",
        "Tsakhur": "त्सखुर",
        "Belarusian": "बेलारूसी",
        "Kolyma Yukaghir": "कोलीमा युकाघिर",
        "Yokuts": "योकुट्स",
        "Kutenai": "कुतेनाई",
        "Adyghe": "अदीगे",
        "Arapaho": "अरापाहो",
        "Blackfoot": "ब्लैकफुट",
        "Buryat": "बुर्यात",
        "Chamorro": "चमोरो",
        "Dakota": "डकोटा",
        "Evenki": "एवेंकी",
        "Fijian": "फिजियन",
        "Gwich'in": "ग्विचिन",
        "Hopi": "होपी",
        "Igbo": "इग्बो",
        "Jingpo": "जिंगपो",
        "Kalaallisut": "कलाल्लिसुत",
        "Lakota": "लकोटा",
        "Mansi": "मांसी",
        "Naxi": "नाक्सी",
        "Ojibwe": "ओजिब्वे",
        "Pawnee": "पॉनी",
        "Rapanui": "रापानुई",
        "Sandawe": "सांडावे",
        "Tuvan": "तुवान",
        "Udmurt": "उदमुर्त",
        "Veps": "वेप्स",
        "Warlpiri": "वार्लपिरी",
        "Xhosa": "खोसा",
        "Yoruba": "योरुबा",
        "Zhuang": "ज्वांग",
        "Zulu": "जुलु",
        "Hadza": "हाड्जा",
        "Khanty": "खांती",
        "Rohingya": "रोहिंग्या",
        "Scots Gaelic": "स्कॉट्स गैलिक",
        "Koryak": "कोर्याक",
        "Nganasan": "न्गानासान",
        "Kalmyk": "कल्मिक",
        "Komi": "कोमी",
        "Yurok": "युरोक",
        "Chinook": "चिनूक",
        "Guarani": "गुआरनी",
        "Caddo": "कैडो",
        "Wichita": "विचिता",
        "Keres": "केरेस",
        "Muscogee": "मस्कोगी",
        "Kiliwa": "किलिवा",
        "Pirahã": "पिराहा",
        "Chechen": "चेचन",
        "Alyutor": "अल्युतोर",
        "Sirenik": "सिरेनिक",
      },
    "Arabic": {
        "Nahuatl": "الناواتل",
        "Quechua": "الكيتشوا",
        "Kwak'wala": "الكواكوالا",
        "Navajo": "النافاخو",
        "Yucatec Mayan": "المايا اليوكاتيكية",
        "Inuktitut": "الإنكتيتوت",
        "Mohawk": "الموهوك",
        "Cree": "الكري",
        "Abenaki": "الأبيناكي",
        "Mi'kmaq": "الميكماك",
        "Zuni": "الزوني",
        "Mapudungun": "المابودونغون",
        "Nivkh": "النيفخ",
        "Haida": "الهايدا",
        "Cherokee": "الشيروكي",
        "Nheengatu": "النهينغاتو",
        "Powhatan": "البوهاتان",
        "Samogitian": "الساموجيتية",
        "Yaqui": "الياكي",
        "Tsimshian": "التسيمشيان",
        "Passamaquoddy": "الباساماكودي",
        "Mohave": "الموهافي",
        "Lushootseed": "اللوشوتسيد",
        "Maori": "الماوري",
        "Lhasa Tibetan": "التبتية اللهاسية",
        "Khoekhoe": "الخويخوي",
        "Katu": "الكاتو",
        "Itelmen": "الإيتلمن",
        "Icelandic": "الأيسلندية",
        "Elfdalian": "الألفدالية",
        "Deg Xinag": "ديغ كسيناغ",
        "Chukchi": "التشوكتشي",
        "Chulym": "تشوليم",
        "Comanche": "الكومانتشي",
        "Beothuk": "البيوثوك",
        "Bashkir": "الباشكير",
        "Selkup": "السلكوب",
        "Djeoromitxí": "الجيوروميتشي",
        "Yakut": "الياقوت",
        "Kokborok": "الكوكبوروك",
        "Kabardian": "القبردي",
        "Quileute": "الكويلوت",
        "Tagalog": "التاغالوغ",
        "Pitjantjatjara": "البيتجانتجاتجارا",
        "Djambarrpuyngu": "الدجامبارربوينغو",
        "Siberian Yupik": "اليوبيك السيبيري",
        "Jeju": "الجيجو",
        "Kikuyu": "الكيكويو",
        "Kumeyaay": "الكوميياي",
        "Guugu Yimithirr": "الغوغو يميثير",
        "Aleut": "الأليوت",
        "Maasai": "الماساي",
        "Nuu-Chah-Nulth": "النو-تشا-نولث",
        "Nez Perce": "النيز بيرس",
        "ǃKung": "!كونغ",
        "Xavante": "الشافانتي",
        "Uyghur": "الأويغور",
        "Sumerian": "السومري",
        "Rusyn": "الروسين",
        "Basque": "الباسك",
        "Welsh": "الويلزي",
        "Quapaw": "الكوابو",
        "Tsez": "التسيز",
        "Tabasaran": "الطبسران",
        "Nenets": "النينيتس",
        "Ket": "الكيت",
        "O'odham": "الأودهام",
        "Hawaiian": "الهاواي",
        "Kildin Sami": "السامي الكيلديني",
        "Tlingit": "التلينغيت",
        "Abkhaz": "الأبخاز",
        "Shoshone": "الشوشون",
        "Ainu": "الأينو",
        "Aymara": "الأيمارا",
        "Dënesųłiné": "الدينيسوليني",
        "Tsakhur": "التساخور",
        "Belarusian": "البيلاروسي",
        "Kolyma Yukaghir": "اليوكاغير الكوليمي",
        "Yokuts": "اليوكوتس",
        "Kutenai": "الكوتيناي",
        "Adyghe": "الأديغي",
        "Arapaho": "الأراباهو",
        "Blackfoot": "النيتسيتابية",
        "Buryat": "البوريات",
        "Chamorro": "الشامورو",
        "Dakota": "الداكوتا",
        "Evenki": "الإيفنكي",
        "Fijian": "الفيجي",
        "Gwich'in": "الغويتشين",
        "Hopi": "الهوبي",
        "Igbo": "الإيغبو",
        "Jingpo": "الجينغبو",
        "Kalaallisut": "الغرينلاندية",
        "Lakota": "اللاكوتا",
        "Mansi": "المانسي",
        "Naxi": "الناشي",
        "Ojibwe": "الأوجيبوي",
        "Pawnee": "الباوني",
        "Rapanui": "الرابانوي",
        "Sandawe": "السنداوي",
        "Tuvan": "التوفي",
        "Udmurt": "الأودمورت",
        "Veps": "الفيبسي",
        "Warlpiri": "الوارلبيري",
        "Xhosa": "الخوسا",
        "Yoruba": "اليوروبا",
        "Zhuang": "الجوانغ",
        "Zulu": "الزولو",
        "Hadza": "الهادزا",
        "Khanty": "الخانتي",
        "Rohingya": "الروهينغيا",
        "Scots Gaelic": "الغيلية الاسكتلندية",
        "Koryak": "الكورياك",
        "Nganasan": "النغاناسان",
        "Kalmyk": "الكالميك",
        "Komi": "الكومي",
        "Yurok": "اليوروك",
        "Chinook": "الشينوك",
        "Guarani": "الغواراني",
        "Caddo": "الكادو",
        "Wichita": "الويتشيتا",
        "Keres": "الكيريس",
        "Muscogee": "الموسكوجي",
        "Kiliwa": "الكيليوا",
        "Pirahã": "البيراها",
        "Chechen": "الشيشاني",
        "Alyutor": "الأليوتور",
        "Sirenik": "السيرينيك",
    },
      "Swahili": {
        "Nahuatl": "Kinahuatl",
        "Quechua": "Kikechua",
        "Kwak'wala": "Kikwakwala",
        "Navajo": "Kinavajo",
        "Yucatec Mayan": "Kimaya ya Yukatan",
        "Inuktitut": "Kiinuktitut",
        "Mohawk": "Kimohoki",
        "Cree": "Kikri",
        "Abenaki": "Kiabenaki",
        "Mi'kmaq": "Kimikmak",
        "Zuni": "Kizuni",
        "Mapudungun": "Kimapudungun",
        "Nivkh": "Kinivkh",
        "Haida": "Kihaida",
        "Cherokee": "Kicherokee",
        "Nheengatu": "Kinheengatu",
        "Powhatan": "Kipowhatan",
        "Samogitian": "Kisamogiti",
        "Yaqui": "Kiyaqui",
        "Tsimshian": "Kitsimshian",
        "Passamaquoddy": "Kipassamaquoddy",
        "Mohave": "Kimohave",
        "Lushootseed": "Kilushootseed",
        "Maori": "Kimaori",
        "Lhasa Tibetan": "Kitibeti ya Lhasa",
        "Khoekhoe": "Kikhoekhoe",
        "Katu": "Kikatu",
        "Itelmen": "Kiitelmen",
        "Icelandic": "Kiaisilandi",
        "Elfdalian": "Kielfdali",
        "Deg Xinag": "Kideg Xinag",
        "Chukchi": "Kichukchi",
        "Chulym": "Kichulym",
        "Comanche": "Kikomanche",
        "Beothuk": "Kibeothuk",
        "Bashkir": "Kibashkir",
        "Selkup": "Kiselkup",
        "Djeoromitxí": "Kidjeoromitxi",
        "Yakut": "Kiyakut",
        "Kokborok": "Kikokborok",
        "Kabardian": "Kikabardian",
        "Quileute": "Kiquileute",
        "Tagalog": "Kitagalog",
        "Pitjantjatjara": "Kipitjantjatjara",
        "Djambarrpuyngu": "Kidjambarrpuyngu",
        "Siberian Yupik": "Kiyupik ya Siberia",
        "Jeju": "Kijeju",
        "Kikuyu": "Kikikuyu",
        "Kumeyaay": "Kikumeyaay",
        "Guugu Yimithirr": "Kiguugu Yimithirr",
        "Aleut": "Kialeut",
        "Maasai": "Kimaasai",
        "Nuu-Chah-Nulth": "Kinuu-chah-nulth",
        "Nez Perce": "Kinez Perce",
        "ǃKung": "Kiǃkung",
        "Xavante": "Kixavante",
        "Uyghur": "Kiuyghur",
        "Sumerian": "Kisumerian",
        "Rusyn": "Kirusyn",
        "Basque": "Kibasque",
        "Welsh": "Kiwelsh",
        "Quapaw": "Kiquapaw",
        "Tsez": "Kitsez",
        "Tabasaran": "Kitabasaran",
        "Nenets": "Kinenets",
        "Ket": "Kiket",
        "O'odham": "Kiodham",
        "Hawaiian": "Kihawaii",
        "Kildin Sami": "Kisami ya Kildin",
        "Tlingit": "Kitlingit",
        "Abkhaz": "Kiabkhaz",
        "Shoshone": "Kishoshone",
        "Ainu": "Kiainu",
        "Aymara": "Kiaymara",
        "Dënesųłiné": "Kidenesulini",
        "Tsakhur": "Kitsakhur",
        "Belarusian": "Kibelarusi",
        "Kolyma Yukaghir": "Kiyukaghir ya Kolyma",
        "Yokuts": "Kiyokuts",
        "Kutenai": "Kikutenai",
        "Adyghe": "Kiadyghe",
        "Arapaho": "Kiarapaho",
        "Blackfoot": "Kiblackfoot",
        "Buryat": "Kiburyat",
        "Chamorro": "Kichamorro",
        "Dakota": "Kidakota",
        "Evenki": "Kievenki",
        "Fijian": "Kifiji",
        "Gwich'in": "Kigwichin",
        "Hopi": "Kihopi",
        "Igbo": "Kiigbo",
        "Jingpo": "Kijingpo",
        "Kalaallisut": "Kikalaallisut",
        "Lakota": "Kilakota",
        "Mansi": "Kimansi",
        "Naxi": "Kinaxi",
        "Ojibwe": "Kiojibwe",
        "Pawnee": "Kipawnee",
        "Rapanui": "Kirapanui",
        "Sandawe": "Kisandawe",
        "Tuvan": "Kituvan",
        "Udmurt": "Kiudmurt",
        "Veps": "Kiveps",
        "Warlpiri": "Kiwarlpiri",
        "Xhosa": "Kixhosa",
        "Yoruba": "Kiyoruba",
        "Zhuang": "Kizhuang",
        "Zulu": "Kizulu",
        "Hadza": "Kihadza",
        "Khanty": "Kikhanty",
        "Rohingya": "Kirohingya",
        "Scots Gaelic": "Kigaeli ya Skotlandi",
        "Koryak": "Kikoryak",
        "Nganasan": "Kinganasan",
        "Kalmyk": "Kikalmyk",
        "Komi": "Kikomi",
        "Yurok": "Kiyurok",
        "Chinook": "Kichinook",
        "Guarani": "Kiguarani",
        "Caddo": "Kicaddo",
        "Wichita": "Kiwichita",
        "Keres": "Kikeres",
        "Muscogee": "Kimuscogee",
        "Kiliwa": "Kikiliwa",
        "Pirahã": "Kipiraha",
        "Chechen": "Kichechen",
        "Alyutor": "Kialyutor",
        "Sirenik": "Kisirenik",
      },
    "Thai": {
        "Nahuatl": "นาวาตล์",
        "Quechua": "เกชัว",
        "Kwak'wala": "ควากวาลา",
        "Navajo": "นาวาโฮ",
        "Yucatec Maya": "มายายูคาเทก",
        "Inuktitut": "อินุกติตุต",
        "Mohawk": "โมฮอว์ก",
        "Cree": "ครี",
        "Abenaki": "อาเบนากิ",
        "Mi'kmaq": "มิกมัก",
        "Zuni": "ซูนิ",
        "Mapudungun": "มาปูดุงกุน",
        "Nivkh": "นิฟค์",
        "Haida": "ไฮดา",
        "Cherokee": "เชอโรกี",
        "Nheengatu": "เญนกาตู",
        "Powhatan": "โพวาตัน",
        "Samogitian": "ซาโมจิเทียน",
        "Yaqui": "ยากี",
        "Tsimshian": "ซิมเชียน",
        "Passamaquoddy": "พาซซามาควอดดี",
        "Mohave": "โมฮาเว",
        "Lushootseed": "ลูชูตซีด",
        "Maori": "เมารี",
        "Lhasa Tibetan": "ทิเบตลาซา",
        "Khoekhoe": "โคเคอ",
        "Katu": "กาตู",
        "Itelmen": "อิเทลเมน",
        "Icelandic": "ไอซ์แลนด์",
        "Elfdalian": "เอลฟ์ดาเลียน",
        "Deg Xinag": "เด็กซินาก",
        "Chukchi": "ชุกชี",
        "Chulym": "ชูลิม",
        "Comanche": "โคมันชี",
        "Beothuk": "เบโอธุก",
        "Bashkir": "บัชคีร์",
        "Selkup": "เซลคุป",
        "Djeoromitxí": "เจโอโรมิตซี",
        "Yakut": "ยาคุต",
        "Kokborok": "คกโบรก",
        "Kabardian": "คาบาร์เดียน",
        "Quileute": "ควิลิวต์",
        "Tagalog": "ตากาล็อก",
        "Pitjantjatjara": "พิตจันตจัตจารา",
        "Djambarrpuyngu": "จัมบาร์ปุยงู",
        "Siberian Yupik": "ยูพิกไซบีเรีย",
        "Jeju": "เชจู",
        "Kikuyu": "คิคูยู",
        "Kumeyaay": "คูมียาอาย",
        "Guugu Yimithirr": "กูกูยิมิเธอร์",
        "Aleut": "อะลิวต์",
        "Maasai": "มาไซ",
        "Nuu-Chah-Nulth": "นู-ชา-นุลธ์",
        "Nez Perce": "เนซเพิร์ซ",
        "ǃKung": "!คุง",
        "Xavante": "ชาวานเต",
        "Uyghur": "อุยกูร์",
        "Sumerian": "สุเมเรียน",
        "Rusyn": "รูซิน",
        "Basque": "บาสก์",
        "Welsh": "เวลส์",
        "Quapaw": "ควาพอว์",
        "Tsez": "เซซ",
        "Tabasaran": "ทาบาซารัน",
        "Nenets": "เนเนตส์",
        "Ket": "เคต",
        "O'odham": "โอ'อ็อดแฮม",
        "Hawaiian": "ฮาวาย",
        "Kildin Sami": "ซามิคิลดิน",
        "Tlingit": "ทลิงกิต",
        "Abkhaz": "อับคาซ",
        "Shoshone": "โชโชนี",
        "Ainu": "ไอนุ",
        "Aymara": "ไอมารา",
        "Dënesųłiné": "เดเนซูลิเน",
        "Tsakhur": "ซาคูร์",
        "Belarusian": "เบลารุส",
        "Kolyma Yukaghir": "ยูคากีร์โคลีมา",
        "Yokuts": "โยคุตส์",
        "Kutenai": "คูเทไน",
        "Adyghe": "อาดิเกะ",
        "Arapaho": "อาราปาโฮ",
        "Blackfoot": "แบล็กฟุต",
        "Buryat": "บูรยาต",
        "Chamorro": "ชามอร์โร",
        "Dakota": "ดาโคตา",
        "Evenki": "เอเวนกิ",
        "Fijian": "ฟิจิ",
        "Gwich'in": "กวิชิน",
        "Hopi": "โฮปี",
        "Igbo": "อิกโบ",
        "Jingpo": "จิงโป",
        "Kalaallisut": "คาลาลิซุต",
        "Lakota": "ลาโคตา",
        "Mansi": "มานซี",
        "Naxi": "นาซี",
        "Ojibwe": "โอจิบเว",
        "Pawnee": "พอนี",
        "Rapanui": "ราปานุย",
        "Sandawe": "ซันดาเว",
        "Tuvan": "ตูวัน",
        "Udmurt": "อุดมูรต์",
        "Veps": "เวปส์",
        "Warlpiri": "วาร์ลปิรี",
        "Xhosa": "โคซา",
        "Yoruba": "โยรูบา",
        "Zhuang": "จ้วง",
        "Zulu": "ซูลู",
        "Hadza": "ฮัดซา",
        "Khanty": "ฮันตี",
        "Rohingya": "โรฮิงยา",
        "Scots Gaelic": "สกอตส์เกลิก",
        "Koryak": "คอรยัก",
        "Nganasan": "งานาซัน",
        "Kalmyk": "คัลมืค",
        "Komi": "โคมิ",
        "Yurok": "ยูรอก",
        "Chinook": "ชินูก",
        "Guarani": "กวารานี",
        "Caddo": "แคดโด",
        "Wichita": "วิชิทอ",
        "Keres": "เคเรส",
        "Muscogee": "มัสโคกี",
        "Kiliwa": "กิลิวา",
        "Pirahã": "ปิราฮา",
        "Chechen": "เชเชน",
        "Alyutor": "อาลูเตอร์",
        "Sirenik": "ซิเรนิก",
    },
    "Hebrew": {
        "Nahuatl": "נאוואטל",
        "Quechua": "קצ'ואה",
        "Kwak'wala": "קוואקוואלה",
        "Navajo": "נאוואחו",
        "Yucatec Maya": "מאיה יוקטקית",
        "Inuktitut": "אינוקטיטוט",
        "Mohawk": "מוהוק",
        "Cree": "קרי",
        "Abenaki": "אבנאקי",
        "Mi'kmaq": "מיקמאק",
        "Zuni": "זוני",
        "Mapudungun": "מפודונגון",
        "Nivkh": "ניבחית",
        "Haida": "האידה",
        "Cherokee": "צ'ירוקי",
        "Nheengatu": "ניינגאטו",
        "Powhatan": "פוהאטן",
        "Samogitian": "סמוגיטית",
        "Yaqui": "יאקי",
        "Tsimshian": "צימשיאן",
        "Passamaquoddy": "פסמקוודי",
        "Mohave": "מוהאבי",
        "Lushootseed": "לושוטסיד",
        "Maori": "מאורית",
        "Lhasa Tibetan": "טיבטית להסה",
        "Khoekhoe": "חויחוי",
        "Katu": "קאטו",
        "Itelmen": "איטלמן",
        "Icelandic": "איסלנדית",
        "Elfdalian": "אלפדאלית",
        "Deg Xinag": "דג קסינאג",
        "Chukchi": "צ'וקצ'י",
        "Chulym": "צ'ולים",
        "Comanche": "קומאנצ'י",
        "Beothuk": "ביאות'וק",
        "Bashkir": "בשקירית",
        "Selkup": "סלקופית",
        "Djeoromitxí": "ג'אורומיצ'י",
        "Yakut": "יאקוטית",
        "Kokborok": "קוקבורוק",
        "Kabardian": "קברדינית",
        "Quileute": "קווילוט",
        "Tagalog": "טגאלוג",
        "Pitjantjatjara": "פיטג'נטג'טג'רה",
        "Djambarrpuyngu": "ג'מברפוינגו",
        "Siberian Yupik": "יופיק סיבירי",
        "Jeju": "ג'ג'ו",
        "Kikuyu": "קיקויו",
        "Kumeyaay": "קומיאיי",
        "Guugu Yimithirr": "גוגו יימית'יר",
        "Aleut": "אלאוטית",
        "Maasai": "מסאית",
        "Nuu-Chah-Nulth": "נו-צ'ה-נולת'",
        "Nez Perce": "נז פרס",
        "ǃKung": "!קונג",
        "Xavante": "שבנטה",
        "Uyghur": "אויגורית",
        "Sumerian": "שומרית",
        "Rusyn": "רוסינית",
        "Basque": "בסקית",
        "Welsh": "וולשית",
        "Quapaw": "קוואפו",
        "Tsez": "צזית",
        "Tabasaran": "טבסרנית",
        "Nenets": "ננצית",
        "Ket": "קטית",
        "O'odham": "או'ודהם",
        "Hawaiian": "הוואית",
        "Kildin Sami": "סאמי קילדין",
        "Tlingit": "טלינגיט",
        "Abkhaz": "אבחזית",
        "Shoshone": "שושונית",
        "Ainu": "איינו",
        "Aymara": "איימרה",
        "Dënesųłiné": "דנה-סות'לינה",
        "Tsakhur": "צחורית",
        "Yucatec Mayan": "מאיה יוקטקית",
        "Belarusian": "בלארוסית",
        "Kolyma Yukaghir": "יוקגירית קולימה",
        "Yokuts": "יוקוטס",
        "Kutenai": "קוטנאי",
        "Adyghe": "אדיגית",
        "Arapaho": "ארפהו",
        "Blackfoot": "בלקפוט",
        "Buryat": "בוריאטית",
        "Chamorro": "צ'מורו",
        "Dakota": "דקוטה",
        "Evenki": "אוונקית",
        "Fijian": "פיג'ית",
        "Gwich'in": "גוויצ'ין",
        "Hopi": "הופי",
        "Igbo": "איגבו",
        "Jingpo": "ג'ינגפו",
        "Kalaallisut": "קלאליסוט",
        "Lakota": "לקוטה",
        "Mansi": "מנסית",
        "Naxi": "נאשי",
        "Ojibwe": "אוג'יבווה",
        "Pawnee": "פוני",
        "Rapanui": "רפא נוי",
        "Sandawe": "סנדאווה",
        "Tuvan": "טובית",
        "Udmurt": "אודמורטית",
        "Veps": "וֶפְּסית",
        "Warlpiri": "וורלפירי",
        "Xhosa": "קוסה",
        "Yoruba": "יורובה",
        "Zhuang": "ג'ואנג",
        "Zulu": "זולו",
        "Hadza": "הדזה",
        "Khanty": "חנטית",
        "Rohingya": "רוהינגה",
        "Scots Gaelic": "גאלית סקוטית",
        "Koryak": "קוריאקית",
        "Nganasan": "נגנסנית",
        "Kalmyk": "קלמיקית",
        "Komi": "קומית",
        "Yurok": "יורוק",
        "Chinook": "צ'ינוק",
        "Guarani": "גוארני",
        "Caddo": "קאדו",
        "Wichita": "ויצ'יטה",
        "Keres": "קרס",
        "Muscogee": "מוסקוגי",
        "Kiliwa": "קיליווה",
        "Pirahã": "פיראהן",
        "Chechen": "צ'צ'נית",
        "Alyutor": "אליוטורית",
        "Sirenik": "סירניקית",
    },
    "Kazakh": {
        "Nahuatl": "Науатль тілі",
        "Quechua": "Кечуа тілі",
        "Kwak'wala": "Квак'вала тілі",
        "Navajo": "Навахо тілі",
        "Yucatec Mayan": "Юкатан майя тілі",
        "Inuktitut": "Инуит тілі",
        "Mohawk": "Мохок тілі",
        "Cree": "Кри тілі",
        "Abenaki": "Абенаки тілі",
        "Mi'kmaq": "Микмак тілі",
        "Zuni": "Зуни тілі",
        "Mapudungun": "Мапудунгун тілі",
        "Nivkh": "Нивх тілі",
        "Haida": "Хайда тілі",
        "Cherokee": "Чероки тілі",
        "Nheengatu": "Ньенгату тілі",
        "Powhatan": "Поухатан тілі",
        "Samogitian": "Жемайт тілі",
        "Yaqui": "Яки тілі",
        "Tsimshian": "Цимшиан тілі",
        "Passamaquoddy": "Пассамакводди тілі",
        "Mohave": "Мохаве тілі",
        "Lushootseed": "Лушуцид тілі",
        "Maori": "Маори тілі",
        "Lhasa Tibetan": "Лхаса тибет тілі",
        "Khoekhoe": "Кхойкхой тілі",
        "Katu": "Кату тілі",
        "Itelmen": "Ительмен тілі",
        "Icelandic": "Исланд тілі",
        "Elfdalian": "Эльвдален тілі",
        "Deg Xinag": "Дег-Хинаг тілі",
        "Chukchi": "Чукча тілі",
        "Chulym": "Чулым тілі",
        "Comanche": "Команч тілі",
        "Beothuk": "Беотук тілі",
        "Bashkir": "Башқұрт тілі",
        "Selkup": "Селькуп тілі",
        "Djeoromitxí": "Джеоромитши тілі",
        "Yakut": "Саха тілі",
        "Kokborok": "Кокборок тілі",
        "Kabardian": "Кабардин тілі",
        "Quileute": "Квилеут тілі",
        "Tagalog": "Тагалог тілі",
        "Pitjantjatjara": "Питжантжатжара тілі",
        "Djambarrpuyngu": "Джамбарпуйнгу тілі",
        "Siberian Yupik": "Сібір юпик тілі",
        "Jeju": "Чеджу тілі",
        "Kikuyu": "Кикуйю тілі",
        "Kumeyaay": "Кумеяай тілі",
        "Guugu Yimithirr": "Гугу-Йимитир тілі",
        "Aleut": "Алеут тілі",
        "Maasai": "Масай тілі",
        "Nuu-Chah-Nulth": "Нуу-ча-нулт тілі",
        "Nez Perce": "Нез-Перс тілі",
        "ǃKung": "ǃКунг тілі",
        "Xavante": "Шаванте тілі",
        "Uyghur": "Ұйғыр тілі",
        "Sumerian": "Шумер тілі",
        "Rusyn": "Русин тілі",
        "Basque": "Баск тілі",
        "Welsh": "Валлий тілі",
        "Quapaw": "Квапо тілі",
        "Tsez": "Цез тілі",
        "Tabasaran": "Табасаран тілі",
        "Nenets": "Ненец тілі",
        "Ket": "Кет тілі",
        "O'odham": "О'одхам тілі",
        "Hawaiian": "Гавай тілі",
        "Kildin Sami": "Кильдин саам тілі",
        "Tlingit": "Тлинкит тілі",
        "Abkhaz": "Абхаз тілі",
        "Shoshone": "Шошон тілі",
        "Ainu": "Айну тілі",
        "Aymara": "Аймара тілі",
        "Dënesųłiné": "Денесулине тілі",
        "Tsakhur": "Цахур тілі",
        "Belarusian": "Беларус тілі",
        "Kolyma Yukaghir": "Колыма юкагир тілі",
        "Yokuts": "Йокутс тілі",
        "Kutenai": "Кутенай тілі",
        "Adyghe": "Адыгэ тілі",
        "Arapaho": "Арапахо тілі",
        "Blackfoot": "Қара Бояу тілі",
        "Buryat": "Бурят тілі",
        "Chamorro": "Чаморро тілі",
        "Dakota": "Дакота тілі",
        "Evenki": "Эвенк тілі",
        "Fijian": "Фиджи тілі",
        "Gwich'in": "Гвичин тілі",
        "Hopi": "Хопи тілі",
        "Igbo": "Игбо тілі",
        "Jingpo": "Цзинпо тілі",
        "Kalaallisut": "Калааллисут тілі",
        "Lakota": "Лакота тілі",
        "Mansi": "Манси тілі",
        "Naxi": "Наси тілі",
        "Ojibwe": "Оджибве тілі",
        "Pawnee": "Пауни тілі",
        "Rapanui": "Рапануи тілі",
        "Sandawe": "Сандаве тілі",
        "Tuvan": "Тыва тілі",
        "Udmurt": "Удмурт тілі",
        "Veps": "Вепс тілі",
        "Warlpiri": "Варлпири тілі",
        "Xhosa": "Коса тілі",
        "Yoruba": "Йоруба тілі",
        "Zhuang": "Чжуан тілі",
        "Zulu": "Зулу тілі",
        "Hadza": "Хадза тілі",
        "Khanty": "Ханты тілі",
        "Rohingya": "Рохинджа тілі",
        "Scots Gaelic": "Шотланд гэль тілі",
        "Koryak": "Коряк тілі",
        "Nganasan": "Нганасан тілі",
        "Kalmyk": "Қалмақ тілі",
        "Komi": "Коми тілі",
        "Yurok": "Юрок тілі",
        "Chinook": "Чинук тілі",
        "Guarani": "Гуарани тілі",
        "Caddo": "Кэддо тілі",
        "Wichita": "Уичита тілі",
        "Keres": "Керес тілі",
        "Muscogee": "Маскоги тілі",
        "Kiliwa": "Килива тілі",
        "Pirahã": "Пираха тілі",
        "Chechen": "Шешен тілі",
        "Alyutor": "Алютор тілі",
        "Sirenik": "Сиреник тілі",
    },
    "Czech": {
      "Nahuatl": "Nahuatl",
      "Quechua": "Kečuánština",
      "Kwak'wala": "Kwak'wala",
      "Navajo": "Navažština", 
      "Yucatec Mayan": "Yucatécká mayština",
      "Nivkh": "Nivchština",
      "Tagalog": "Tagalog",
      "Cherokee": "Čerokézština", 
      "Mohawk": "Mohawkština",
      "Mapudungun": "Mapudungun",
      "Hawaiian": "Havajština",
      "Kildin Sami": "Kildinská sámština",
      "Tlingit": "Tlingit",
      "Abkhaz": "Abcházština",
      "Tsez": "Cezština",
      "Tabasaran": "Tabasaranština", 
      "Nenets": "Něnečtina",
      "Ket": "Ketština",
      "Abenaki": "Abenačtina",
      "Ainu": "Ainština",
      "Aymara": "Aymarština",
      "Shoshone": "Šošonština",
      "O'odham": "O'odham",
      "Siberian Yupik": "Sibiřská jupikština",
      "Kikuyu": "Kikujština",
      "Kumeyaay": "Kumeyaay",
      "Mi'kmaq": "Mi'kmaq",
      "Aleut": "Aleutština",
      "Maasai": "Masajština",
      "Nez Perce": "Nez Perce",
      "Xavante": "Šavantština",
      "Uyghur": "Ujgurština",
      "Sumerian": "Sumerština",
      "Rusyn": "Rusínština",
      "Zuni": "Zuni",
      "Basque": "Baskičtina",
      "Welsh": "Velština",
      "Nheengatu": "Nheengatu",
      "Samogitian": "Žemaitština",
      "Yaqui": "Yaqui",
      "Tsimshian": "Tsimshian",
      "Maori": "Maorština",
      "Lhasa Tibetan": "Lhaská tibetština",
      "Khoekhoe": "Khoekhoe",
      "Icelandic": "Islandština",
      "Haida": "Haida",
      "Elfdalian": "Elfdalština",
      "Chukchi": "Čukčtina",
      "Comanche": "Komančština",
      "Bashkir": "Baškirština",
      "Selkup": "Selkupština",
      "Yakut": "Jakutština",
      "Kokborok": "Kokborok",
      "Kabardian": "Kabardština",
      "Quileute": "Quileute",
      "Pitjantjatjara": "Pitjantjatjara",
      "Djambarrpuyngu": "Djambarrpuyngu",
      "Jeju": "Jeju",
      "Guugu Yimithirr": "Guugu Yimithirr",
      "Djeoromitxí": "Djeoromitxí",
      "Katu": "Katu",
      "Itelmen": "Itelmenština",
      "Deg Xinag": "Deg Xinag",
      "Dënesųłiné": "Dënesųłiné",
      "Tsakhur": "Cachurština",
      "Belarusian": "Běloruština",
      "Kolyma Yukaghir": "Kolymská jukagirština",
      "Yokuts": "Yokuts",
      "Kutenai": "Kutenai",
      "Adyghe": "Adygejština",
      "Arapaho": "Arapaho",
      "Blackfoot": "Černonožština",
      "Buryat": "Burjatština",
      "Chamorro": "Chamorro",
      "Dakota": "Dakota",
      "Evenki": "Evenština",
      "Fijian": "Fidžijština",
      "Gwich'in": "Gwich'in",
      "Hopi": "Hopi",
      "Igbo": "Igbo",
      "Jingpo": "Jingpo",
      "Kalaallisut": "Kalaallisut",
      "Lakota": "Lakota",
      "Mansi": "Mansijština",
      "Naxi": "Naxi",
      "Ojibwe": "Ojibwe",
      "Pawnee": "Pawnee",
      "Rapanui": "Rapanui",
      "Sandawe": "Sandawe",
      "Tuvan": "Tuvinština",
      "Udmurt": "Udmurtština",
      "Veps": "Vepština",
      "Warlpiri": "Warlpiri",
      "Xhosa": "Xhosa",
      "Yoruba": "Yoruba",
      "Zhuang": "Zhuang",
      "Zulu": "Zulu",
      "Hadza": "Hadza",
      "Khanty": "Chantyjština",
      "Rohingya": "Rohingya",
      "Scots Gaelic": "Skotská gaelština",
      "Koryak": "Korjačtina",
      "Nganasan": "Nganasan",
      "Inuktitut": "Inuitština",
      "Cree": "Cree",
      "Powhatan": "Powhatan",
      "Passamaquoddy": "Passamaquoddy",
      "Mohave": "Mohave",
      "Lushootseed": "Lushootseed",
      "Chulym": "Chulym",
      "Beothuk": "Beothuk",
      "Nuu-Chah-Nulth": "Nuu-chah-nulth",
      "ǃKung": "ǃKung",
      "Quapaw": "Quapaw",
      "Kalmyk": "Kalmykština",
      "Komi": "Komiština",
      "Yurok": "Yurok",
      "Chinook": "Chinook",
      "Guarani": "Guarani",
      "Caddo": "Caddo",
      "Wichita": "Wichita",
      "Keres": "Keres",
      "Muscogee": "Muscogee",
      "Kiliwa": "Kiliwa",
      "Pirahã": "Pirahã",
      "Chechen": "Čečenština",
      "Alyutor": "Alyutor",
      "Sirenik": "Sirenik",
    },
    "Georgian": {
      "Nahuatl": "ნაუატლი",
      "Quechua": "კეჩუა",
      "Kwak'wala": "კვაკვალა",
      "Navajo": "ნავახო",
      "Yucatec Mayan": "იუკატეკური მაია",
      "Nivkh": "ნივხური",
      "Tagalog": "ტაგალური",
      "Cherokee": "ჩეროკი",
      "Mohawk": "მოჰავკური",
      "Mapudungun": "მაპუდუნგუნი",
      "Hawaiian": "ჰავაიური",
      "Kildin Sami": "კილდინ-საამური",
      "Tlingit": "ტლინგიტური",
      "Abkhaz": "აფხაზური",
      "Tsez": "წეზური",
      "Tabasaran": "თაბასარანული",
      "Nenets": "ნენეცური",
      "Ket": "კეტური",
      "Abenaki": "აბენაკური",
      "Ainu": "აინური",
      "Aymara": "აიმარა",
      "Shoshone": "შოშონური",
      "O'odham": "ოდჰამური",
      "Siberian Yupik": "ციმბირული იუპიკური",
      "Kikuyu": "კიკუიუ",
      "Kumeyaay": "კუმეიაი",
      "Mi'kmaq": "მიკმაკური",
      "Aleut": "ალეუტური",
      "Maasai": "მასაი",
      "Nez Perce": "ნეზ-პერსი",
      "Xavante": "შავანტე",
      "Uyghur": "უიღურული",
      "Sumerian": "შუმერული",
      "Rusyn": "რუსინული",
      "Zuni": "ზუნი",
      "Basque": "ბასკური",
      "Welsh": "უელსური",
      "Nheengatu": "ნეენგატუ",
      "Samogitian": "ჟემაიტური",
      "Yaqui": "იაკური",
      "Tsimshian": "ცმიშიანური",
      "Maori": "მაორი",
      "Lhasa Tibetan": "ლჰასური ტიბეტური",
      "Khoekhoe": "კჰოეკჰოე",
      "Icelandic": "ისლანდიური",
      "Haida": "ჰაიდა",
      "Elfdalian": "ელვდალური",
      "Chukchi": "ჩუკჩური",
      "Comanche": "კომანჩური",
      "Bashkir": "ბაშკირული",
      "Selkup": "სელკუპური",
      "Yakut": "იაკუტური",
      "Kokborok": "კოკბოროკი",
      "Kabardian": "ყაბარდოული",
      "Quileute": "კვილეუტე",
      "Pitjantjatjara": "პიტჯანტჯატჯარა",
      "Djambarrpuyngu": "ჯამბარპუინგუ",
      "Jeju": "ჯეჯუ",
      "Guugu Yimithirr": "გუუგუ-იმითირი",
      "Katu": "კატუ",
      "Itelmen": "იტელმენური",
      "Deg Xinag": "დეგ-ხინაგი",
      "Dënesųłiné": "დენესულინე",
      "Tsakhur": "წახური",
      "Belarusian": "ბელარუსული",
      "Kolyma Yukaghir": "კოლიმური იუკაგირული",
      "Yokuts": "იოკუტსი",
      "Kutenai": "კუტენაი",
      "Adyghe": "ადიღეური",
      "Arapaho": "არაპაჰო",
      "Blackfoot": "ბლექფუტი",
      "Buryat": "ბურიატული",
      "Chamorro": "ჩამორო",
      "Dakota": "დაკოტური",
      "Evenki": "ევენკური",
      "Fijian": "ფიჯიური",
      "Gwich'in": "გვიჩინი",
      "Hopi": "ჰოპი",
      "Igbo": "იგბო",
      "Jingpo": "ჯინგპო",
      "Kalaallisut": "კალაალისუტი",
      "Lakota": "ლაკოტა",
      "Mansi": "მანსიური",
      "Naxi": "ნაქსი",
      "Ojibwe": "ოჯიბვე",
      "Pawnee": "პონი",
      "Rapanui": "რაპანუი",
      "Sandawe": "სანდავე",
      "Tuvan": "თუვური",
      "Udmurt": "უდმურტული",
      "Veps": "ვეფსური",
      "Warlpiri": "ვარლპირი",
      "Xhosa": "ქჰოსა",
      "Yoruba": "იორუბა",
      "Zhuang": "ჯუანური",
      "Zulu": "ზულუ",
      "Hadza": "ჰაძა",
      "Khanty": "ხანტური",
      "Rohingya": "როჰინჯა",
      "Scots Gaelic": "შოტლანდიური გელური",
      "Koryak": "კორიაკული",
      "Nganasan": "ნგანასანური",
      "Kalmyk": "კალმუხური",
      "Komi": "კომიური",
      "Yurok": "იუროკი",
      "Chinook": "ჩინუკი",
      "Guarani": "გუარანი",
      "Caddo": "კადო",
      "Wichita": "ვიჩიტა",
      "Keres": "კერესი",
      "Muscogee": "მასკოგი",
      "Kiliwa": "კილივა",
      "Inuktitut": "ინუიტური",
      "Cree": "კრი",
      "Powhatan": "პოვაჰატანური",
      "Passamaquoddy": "პასამაკოდდი",
      "Mohave": "მოჰავი",
      "Lushootseed": "ლუშუციდი",
      "Chulym": "ჩულიმური",
      "Beothuk": "ბეიოთუკი",
      "Nuu-Chah-Nulth": "ნუ-ჭაჰ-ნულთი",
      "ǃKung": "კუნგური",
      "Quapaw": "კუაპავი",
      "Djeoromitxí": "ჯორომიტხი",
      "Pirahã": "პირაჰან",
      "Chechen": "ჩეჩნური",
      "Alyutor": "ალიუტორული",
      "Sirenik": "სირენიკული"
    },
    "Armenian": {
      "Nahuatl": "Նահուատլ",
      "Quechua": "Կեչուա",
      "Kwak'wala": "Կվակվալա",
      "Navajo": "Նավախո",
      "Yucatec Mayan": "Յուկատեկ Մայա",
      "Nivkh": "Նիվխ",
      "Tagalog": "Տագալոգ",
      "Cherokee": "Չերոկի",
      "Mohawk": "Մոհավկ",
      "Mapudungun": "Մապուդունգուն",
      "Hawaiian": "Հավայերեն",
      "Kildin Sami": "Կիլդին Սամի",
      "Tlingit": "Տլինգիտ",
      "Abkhaz": "Աբխազերեն",
      "Tsez": "Ցեզ",
      "Tabasaran": "Տաբասարան",
      "Nenets": "Նենեց",
      "Ket": "Կետ",
      "Abenaki": "Աբենակի",
      "Ainu": "Այնու",
      "Aymara": "Այմարա",
      "Shoshone": "Շոշոն",
      "O'odham": "Օդհամ",
      "Siberian Yupik": "Սիբիրյան Յուպիկ",
      "Kikuyu": "Կիկույու",
      "Kumeyaay": "Կումեյայ",
      "Mi'kmaq": "Միկմակ",
      "Aleut": "Ալեուտ",
      "Maasai": "Մասաի",
      "Nez Perce": "Նեզ Պերս",
      "Xavante": "Խավանտե",
      "Uyghur": "Ույղուրերեն",
      "Sumerian": "Շումերերեն",
      "Rusyn": "Ռուսիներեն",
      "Zuni": "Զունի",
      "Basque": "Բասկերեն",
      "Welsh": "Ուելսերեն",
      "Nheengatu": "Նհեենգատու",
      "Samogitian": "Սամոգիտերեն",
      "Yaqui": "Յակի",
      "Tsimshian": "Ցիմշիան",
      "Maori": "Մաորի",
      "Lhasa Tibetan": "Լհասա Տիբեթերեն",
      "Khoekhoe": "Կհոեկհոե",
      "Icelandic": "Իսլանդերեն",
      "Haida": "Հայդա",
      "Elfdalian": "Էլֆդալերեն",
      "Chukchi": "Չուկչի",
      "Comanche": "Կոմանչի",
      "Bashkir": "Բաշկիրերեն",
      "Selkup": "Սելկուպերեն",
      "Yakut": "Յակուտերեն",
      "Kokborok": "Կոկբորոկ",
      "Kabardian": "Կաբարդիներեն",
      "Quileute": "Կվիլեուտե",
      "Pitjantjatjara": "Պիտջանտջատջարա",
      "Djambarrpuyngu": "Ջամբարպույնգու",
      "Jeju": "Ջեջու",
      "Guugu Yimithirr": "Գուուգու Յիմիթիր",
      "Katu": "Կատու",
      "Itelmen": "Իտելմեն",
      "Deg Xinag": "Դեգ Խինագ",
      "Dënesųłiné": "Դենեսուլինե",
      "Tsakhur": "Ցախուր",
      "Belarusian": "Բելառուսերեն",
      "Kolyma Yukaghir": "Կոլիմա Յուկագիր",
      "Yokuts": "Յոկուտս",
      "Kutenai": "Կուտենայ",
      "Adyghe": "Ադիղերեն",
      "Arapaho": "Արապահո",
      "Blackfoot": "Բլեկֆուտ",
      "Buryat": "Բուրյատերեն",
      "Chamorro": "Չամոռո",
      "Dakota": "Դակոտա",
      "Evenki": "Էվենկի",
      "Fijian": "Ֆիջիերեն",
      "Gwich'in": "Գվիչին",
      "Hopi": "Հոպի",
      "Igbo": "Իգբո",
      "Jingpo": "Ջինգպո",
      "Kalaallisut": "Կալաալիսուտ",
      "Lakota": "Լակոտա",
      "Mansi": "Մանսի",
      "Naxi": "Նաքսի",
      "Ojibwe": "Օջիբվե",
      "Pawnee": "Պոնի",
      "Rapanui": "Ռապանուի",
      "Sandawe": "Սանդավե",
      "Tuvan": "Թուվերեն",
      "Udmurt": "Ուդմուրտերեն",
      "Veps": "Վեպսերեն",
      "Warlpiri": "Վարլպիրի",
      "Xhosa": "Քհոսա",
      "Yoruba": "Յորուբա",
      "Zhuang": "Ջուաներեն",
      "Zulu": "Զուլու",
      "Hadza": "Հաձա",
      "Khanty": "Խանտի",
      "Rohingya": "Ռոհինջա",
      "Scots Gaelic": "Շոտլանդական Գելերեն",
      "Koryak": "Կորյակերեն",
      "Nganasan": "Նգանասաներեն",
      "Kalmyk": "Կալմիկերեն",
      "Komi": "Կոմիերեն",
      "Yurok": "Յուրոկ",
      "Chinook": "Չինուկ",
      "Guarani": "Գուարանի",
      "Caddo": "Կադո",
      "Wichita": "Վիչիտա",
      "Keres": "Կերես",
      "Muscogee": "Մասկոգի",
      "Kiliwa": "Կիլիվա",
      "Inuktitut": "Ինուիտերեն",
      "Cree": "Կրի",
      "Powhatan": "Պոուհատան",
      "Passamaquoddy": "Պասամակուոդի",
      "Mohave": "Մոհավե",
      "Lushootseed": "Լուշուցիդ",
      "Chulym": "Չուլիմերեն",
      "Beothuk": "Բեոթուկ",
      "Nuu-Chah-Nulth": "Նու-Չահ-Նուլթ",
      "ǃKung": "ǃԿունգ",
      "Djeoromitxí": "Ջեորոմիտշի",
      "Quapaw": "Կուապավ",
      "Pirahã": "Պիրահան",
      "Chechen": "Չեչեներեն",
      "Alyutor": "Ալյուտորերեն",
      "Sirenik": "Սիրենիկ",
    }
  }