const uiTranslations = {
  "English": {
    appTitle: "Indigenous Language Learning",
    welcome: "Welcome to the Indigenous Language Learning App",
    welcomeMessage: "Discover the Beauty of Indigenous Languages",
    welcomeSubtext: "Embark on a journey to preserve and learn languages that connect us to our heritage",
    selectLanguage: "Select a language to learn:",
    start: "Start Learning",
    lesson: "Lesson",
    exercise: "Exercise",
    check: "Check Answer",
    correct: "Correct!",
    incorrect: "Try again",
    next: "Next",
    back: "Back",
    settings: "Settings",
    interfaceLanguage: "Interface Language:",
    about: "About",
    progress: "Progress",
    vocabulary: "Vocabulary",
    phrases: "Common Phrases",
    grammar: "Grammar",
    quiz: "Quiz",
    home: "Home",
    matching: "Matching",
    multipleChoice: "Multiple Choice",
    completed: "Completed",
    pronunciation: "Pronunciation",
    cultural: "Cultural Notes",
    flashcards: "Flashcards",
    speakingPractice: "Speaking Practice",
    listeningPractice: "Listening Practice",
    dictionary: "Dictionary",
    favoriteWords: "Favorite Words",
    communityForum: "Community Forum",
    communityForumHero: "Join Our Language Community",
    communityForumSubtext: "Connect with fellow learners, share resources, and discuss indigenous languages",
    profile: "Profile",
    achievements: "Achievements",
    review: "Review",
    searchPlaceholder: "Search words or phrases...",
    lessonTitle: "Language Lesson",
    topicViewTitle: "Topic - Indigenous Language Learning",
    loadingTopic: "Loading topic...",
    orSignInWith: "Or sign in with:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Sign In",
    signInTitle: "Sign In - Indigenous Language Learning",
    register: "Register",
    registerTitle: "Register - Indigenous Language Learning",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    username: "Username",
    signInButton: "Sign In",
    registerButton: "Register",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    profile: "Profile",
    logout: "Logout",
    
    // Forum
    forum: "Forum",
    forumTitle: "Community Forum - Indigenous Language Learning",
    communityForum: "Community Forum",
    newTopic: "New Topic",
    categories: "Categories",
    generalDiscussion: "General Discussion",
    generalDiscussionDesc: "Discuss anything related to indigenous languages",
    learningTips: "Learning Tips",
    learningTipsDesc: "Share and discover language learning strategies",
    resources: "Resources",
    resourcesDesc: "Share books, websites, and other learning materials",
    events: "Events",
    eventsDesc: "Upcoming language events and gatherings",
    recentTopics: "Recent Topics",
    noTopicsYet: "No topics yet. Be the first to create one!",
    createNewTopic: "Create New Topic",
    topicTitle: "Title",
    category: "Category",
    content: "Content",
    createTopic: "Create Topic",
    backToForum: "← Back to Forum",
    replies: "Replies",
    noRepliesYet: "No replies yet. Be the first to reply!",
    postReply: "Post a Reply",
    submitReply: "Submit Reply",
    signInToReply: "Please sign in to post a reply."
  },
  "French": {
    appTitle: "Apprentissage des Langues Autochtones",
    welcome: "Bienvenue dans l'application d'apprentissage des langues autochtones",
    welcomeMessage: "Découvrez la beauté des langues autochtones",
    welcomeSubtext: "Embarquez pour un voyage pour préserver et apprendre les langues qui nous relient à notre patrimoine",
    selectLanguage: "Sélectionnez une langue à apprendre :",
    start: "Commencer l'apprentissage",
    lesson: "Leçon",
    exercise: "Exercice",
    check: "Vérifier la réponse",
    correct: "Correct !",
    incorrect: "Essayez encore",
    next: "Suivant",
    back: "Retour",
    settings: "Paramètres",
    interfaceLanguage: "Langue de l'interface :",
    about: "À propos",
    progress: "Progrès",
    vocabulary: "Vocabulaire",
    phrases: "Phrases courantes",
    grammar: "Grammaire",
    quiz: "Quiz",
    home: "Accueil",
    matching: "Association",
    multipleChoice: "Choix multiple",
    completed: "Terminé",
    pronunciation: "Prononciation",
    cultural: "Notes culturelles",
    flashcards: "Cartes mémoire",
    speakingPractice: "Pratique orale",
    listeningPractice: "Pratique d'écoute",
    dictionary: "Dictionnaire",
    favoriteWords: "Mots favoris",
    communityForum: "Forum communautaire",
    communityForumHero: "Rejoignez notre communauté linguistique",
    communityForumSubtext: "Connectez-vous avec d'autres apprenants, partagez des ressources et discutez des langues autochtones",
    profile: "Profil",
    achievements: "Réalisations",
    review: "Révision",
    searchPlaceholder: "Rechercher des mots ou des phrases...",
    lessonTitle: "Leçon de langue",
    topicViewTitle: "Sujet - Apprentissage des Langues Autochtones",
    loadingTopic: "Chargement du sujet...",
    orSignInWith: "Ou connectez-vous avec :",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Se connecter",
    signInTitle: "Se connecter - Apprentissage des Langues Autochtones",
    register: "S'inscrire",
    registerTitle: "S'inscrire - Apprentissage des Langues Autochtones",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    username: "Nom d'utilisateur",
    signInButton: "Se connecter",
    registerButton: "S'inscrire",
    noAccount: "Pas encore de compte ?",
    haveAccount: "Déjà un compte ?",
    profile: "Profil",
    logout: "Se déconnecter",
    
    // Forum
    forum: "Forum",
    forumTitle: "Forum communautaire - Apprentissage des Langues Autochtones",
    communityForum: "Forum communautaire",
    newTopic: "Nouveau sujet",
    categories: "Catégories",
    generalDiscussion: "Discussions générales",
    generalDiscussionDesc: "Discutez de tout ce qui concerne les langues autochtones",
    learningTips: "Conseils d'apprentissage",
    learningTipsDesc: "Partagez et découvrez des stratégies d'apprentissage de la langue",
    resources: "Ressources",
    resourcesDesc: "Partagez des livres, des sites Web et d'autres matériaux d'apprentissage",
    events: "Événements",
    eventsDesc: "Événements à venir et rassemblements linguistiques",
    recentTopics: "Sujets récents",
    noTopicsYet: "Aucun sujet pour le moment. Soyez le premier à en créer un !",
    createNewTopic: "Créer un nouveau sujet",
    topicTitle: "Titre",
    category: "Catégorie",
    content: "Contenu",
    createTopic: "Créer un sujet",
    backToForum: "← Retour au forum",
    replies: "Réponses",
    noRepliesYet: "Aucune réponse pour le moment. Soyez le premier à répondre !",
    postReply: "Poster une réponse",
    submitReply: "Soumettre la réponse",
    signInToReply: "Veuillez vous connecter pour poster une réponse."
  },
  "Ukrainian": {
    appTitle: "Вивчення корінних мов",
    welcome: "Ласкаво просимо до додатку вивчення корінних мов",
    welcomeMessage: "Відкрийте для себе красу корінних мов",
    welcomeSubtext: "Вирушайте в подорож, щоб зберегти та вивчити мови, які з'єднують нас з нашою спадщиною",
    selectLanguage: "Виберіть мову для вивчення:",
    start: "Почати навчання",
    lesson: "Урок",
    exercise: "Вправа",
    check: "Перевірити відповідь",
    correct: "Правильно!",
    incorrect: "Спробуйте ще раз",
    next: "Далі",
    back: "Назад",
    settings: "Налаштування",
    interfaceLanguage: "Мова інтерфейсу:",
    about: "Про додаток",
    progress: "Прогрес",
    vocabulary: "Словник",
    phrases: "Поширені фрази",
    grammar: "Граматика",
    quiz: "Тест",
    home: "Головна",
    matching: "Відповідність",
    multipleChoice: "Вибір з варіантів",
    completed: "Завершено",
    pronunciation: "Вимова",
    cultural: "Культурні примітки",
    flashcards: "Картки для запам'ятовування",
    speakingPractice: "Практика розмови",
    listeningPractice: "Практика слухання",
    dictionary: "Словник",
    favoriteWords: "Улюблені слова",
    communityForum: "Форум спільноти",
    communityForumHero: "Приєднуйтесь до нашої мовної спільноти",
    communityForumSubtext: "Спілкуйтеся з іншими учнями, діліться ресурсами та обговорюйте корінні мови",
    profile: "Профіль",
    achievements: "Досягнення",
    review: "Перегляд",
    searchPlaceholder: "Шукати слова або фрази...",
    lessonTitle: "Урок мови",
    topicViewTitle: "Тема - Вивчення корінних мов",
    loadingTopic: "Завантаження теми...",
    orSignInWith: "Або увійдіть за допомогою:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Увійти",
    signInTitle: "Увійти - Вивчення корінних мов",
    register: "Зареєструватися",
    registerTitle: "Зареєструватися - Вивчення корінних мов",
    email: "Електронна пошта",
    password: "Пароль",
    confirmPassword: "Підтвердіть пароль",
    username: "Ім'я користувача",
    signInButton: "Увійти",
    registerButton: "Зареєструватися",
    noAccount: "Не маєте облікового запису?",
    haveAccount: "Вже маєте обліковий запис?",
    profile: "Профіль",
    logout: "Вийти",
    
    // Forum
    forum: "Форум",
    forumTitle: "Форум спільноти - Вивчення корінних мов",
    communityForum: "Форум спільноти",
    newTopic: "Нова тема",
    categories: "Категорії",
    generalDiscussion: "Загальна дискусія",
    generalDiscussionDesc: "Обговорюйте все, що стосується корінних мов",
    learningTips: "Поради з навчання",
    learningTipsDesc: "Поділіться та дізнайтеся про стратегії навчання мови",
    resources: "Ресурси",
    resourcesDesc: "Поділіться книгами, веб-сайтами та іншими навчальними матеріалами",
    events: "Події",
    eventsDesc: "Майбутні події та зустрічі з мовою",
    recentTopics: "Недавні теми",
    noTopicsYet: "Поки що немає тем. Будьте першим, хто створить тему!",
    createNewTopic: "Створити нову тему",
    topicTitle: "Заголовок",
    category: "Категорія",
    content: "Вміст",
    createTopic: "Створити тему",
    backToForum: "← Повернутися до форуму",
    replies: "Відповіді",
    noRepliesYet: "Поки що немає відповідей. Будьте першим, хто відповість!",
    postReply: "Опублікувати відповідь",
    submitReply: "Надіслати відповідь",
    signInToReply: "Будь ласка, увійдіть, щоб опублікувати відповідь."
  },
  "Spanish": {
    appTitle: "Aprendizaje de Lenguas Indígenas",
    welcome: "Bienvenido a la aplicación de aprendizaje de lenguas indígenas",
    welcomeMessage: "Descubre la belleza de las lenguas indígenas",
    welcomeSubtext: "Embárcate en un viaje para preservar y aprender idiomas que nos conectan con nuestro patrimonio",
    selectLanguage: "Selecciona un idioma para aprender:",
    start: "Comenzar a aprender",
    lesson: "Lección",
    exercise: "Ejercicio",
    check: "Verificar respuesta",
    correct: "¡Correcto!",
    incorrect: "Inténtalo de nuevo",
    next: "Siguiente",
    back: "Atrás",
    settings: "Configuración",
    interfaceLanguage: "Idioma de la interfaz:",
    about: "Acerca de",
    progress: "Progreso",
    vocabulary: "Vocabulario",
    phrases: "Frases comunes",
    grammar: "Gramática",
    quiz: "Cuestionario",
    home: "Inicio",
    matching: "Emparejamiento",
    multipleChoice: "Opción múltiple",
    completed: "Completado",
    pronunciation: "Pronunciación",
    cultural: "Notas culturales",
    flashcards: "Tarjetas de memoria",
    speakingPractice: "Práctica de habla",
    listeningPractice: "Práctica de escucha",
    dictionary: "Diccionario",
    favoriteWords: "Palabras favoritas",
    communityForum: "Foro comunitario",
    communityForumHero: "Únete a nuestra comunidad lingüística",
    communityForumSubtext: "Conéctate con otros estudiantes, comparte recursos y discute sobre lenguas indígenas",
    profile: "Perfil",
    achievements: "Logros",
    review: "Revisión",
    searchPlaceholder: "Buscar palabras o frases...",
    lessonTitle: "Lección de idioma",
    topicViewTitle: "Tema - Aprendizaje de Lenguas Indígenas",
    loadingTopic: "Cargando tema...",
    orSignInWith: "O inicia sesión con:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "Iniciar sesión",
    signInTitle: "Iniciar sesión - Aprendizaje de Lenguas Indígenas",
    register: "Registrarse",
    registerTitle: "Registrarse - Aprendizaje de Lenguas Indígenas",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    username: "Nombre de usuario",
    signInButton: "Iniciar sesión",
    registerButton: "Registrarse",
    noAccount: "¿No tienes una cuenta?",
    haveAccount: "¿Ya tienes una cuenta?",
    profile: "Perfil",
    logout: "Cerrar sesión",
    // Forum
    forum: "Foro",
    forumTitle: "Foro comunitario - Aprendizaje de Lenguas Indígenas",
    communityForum: "Foro comunitario",
    newTopic: "Nuevo tema",
    categories: "Categorías",
    generalDiscussion: "Discusión general",
    generalDiscussionDesc: "Discute cualquier tema relacionado con las lenguas indígenas",
    learningTips: "Consejos de aprendizaje",
    learningTipsDesc: "Comparte y descubre estrategias de aprendizaje de idiomas",
    resources: "Recursos",
    resourcesDesc: "Comparte libros, sitios web y otros materiales de aprendizaje",
    events: "Eventos",
    eventsDesc: "Próximos eventos y reuniones lingüísticas",
    recentTopics: "Temas recientes",
    noTopicsYet: "Aún no hay temas. ¡Sé el primero en crear uno!",
    createNewTopic: "Crear nuevo tema",
    topicTitle: "Título",
    category: "Categoría",
    content: "Contenido",
    createTopic: "Crear tema",
    backToForum: "← Volver al foro",
    replies: "Respuestas",
    noRepliesYet: "Aún no hay respuestas. ¡Sé el primero en responder!",
    postReply: "Publicar una respuesta",
    submitReply: "Enviar respuesta",
    signInToReply: "Por favor inicia sesión para publicar una respuesta."
  },
  "German": {
    appTitle: "Lernen indigener Sprachen",
    welcome: "Willkommen bei der App zum Erlernen indigener Sprachen",
    welcomeMessage: "Entdecken Sie die Schönheit indigener Sprachen",
    welcomeSubtext: "Begeben Sie sich auf eine Reise, um Sprachen zu bewahren und zu erlernen, die uns mit unserem Erbe verbinden",
    selectLanguage: "Wählen Sie eine Sprache zum Lernen:",
    start: "Mit dem Lernen beginnen",
    lesson: "Lektion",
    exercise: "Übung",
    check: "Antwort überprüfen",
    correct: "Richtig!",
    incorrect: "Versuchen Sie es erneut",
    next: "Weiter",
    back: "Zurück",
    settings: "Einstellungen",
    interfaceLanguage: "Oberflächensprache:",
    about: "Über",
    progress: "Fortschritt",
    vocabulary: "Vokabular",
    phrases: "Häufige Redewendungen",
    grammar: "Grammatik",
    quiz: "Quiz",
    home: "Startseite",
    matching: "Zuordnung",
    multipleChoice: "Multiple Choice",
    completed: "Abgeschlossen",
    pronunciation: "Aussprache",
    cultural: "Kulturelle Hinweise",
    flashcards: "Karteikarten",
    speakingPractice: "Sprechübung",
    listeningPractice: "Hörübung",
    dictionary: "Wörterbuch",
    favoriteWords: "Lieblingswörter",
    communityForum: "Community-Forum",
    communityForumHero: "Treten Sie unserer Sprachgemeinschaft bei",
    communityForumSubtext: "Verbinden Sie sich mit anderen Lernenden, teilen Sie Ressourcen und diskutieren Sie über indigene Sprachen",
    profile: "Profil",
    achievements: "Erfolge",
    review: "Überprüfung",
    searchPlaceholder: "Wörter oder Phrasen suchen...",
    lessonTitle: "Sprachlektion",
    topicViewTitle: "Thema - Lernen indigener Sprachen",
    loadingTopic: "Thema wird geladen...",
    orSignInWith: "Oder melden Sie sich an mit:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "Anmelden",
    signInTitle: "Anmelden - Lernen indigener Sprachen",
    register: "Registrieren",
    registerTitle: "Registrieren - Lernen indigener Sprachen",
    email: "E-Mail",
    password: "Passwort",
    confirmPassword: "Passwort bestätigen",
    username: "Benutzername",
    signInButton: "Anmelden",
    registerButton: "Registrieren",
    noAccount: "Noch kein Konto?",
    haveAccount: "Haben Sie bereits ein Konto?",
    profile: "Profil",
    logout: "Abmelden",
    // Forum
    forum: "Forum",
    forumTitle: "Community-Forum - Lernen indigener Sprachen",
    communityForum: "Community-Forum",
    newTopic: "Neues Thema",
    categories: "Kategorien",
    generalDiscussion: "Allgemeine Diskussion",
    generalDiscussionDesc: "Diskutieren Sie alles, was mit indigenen Sprachen zu tun hat",
    learningTips: "Lerntipps",
    learningTipsDesc: "Teilen und entdecken Sie Strategien zum Sprachenlernen",
    resources: "Ressourcen",
    resourcesDesc: "Teilen Sie Bücher, Websites und andere Lernmaterialien",
    events: "Veranstaltungen",
    eventsDesc: "Kommende Sprachveranstaltungen und Treffen",
    recentTopics: "Aktuelle Themen",
    noTopicsYet: "Noch keine Themen. Seien Sie der Erste, der eines erstellt!",
    createNewTopic: "Neues Thema erstellen",
    topicTitle: "Titel",
    category: "Kategorie",
    content: "Inhalt",
    createTopic: "Thema erstellen",
    backToForum: "← Zurück zum Forum",
    replies: "Antworten",
    noRepliesYet: "Noch keine Antworten. Seien Sie der Erste, der antwortet!",
    postReply: "Antwort veröffentlichen",
    submitReply: "Antwort absenden",
    signInToReply: "Bitte melden Sie sich an, um eine Antwort zu veröffentlichen."
  },
  // Japanese translations
  "Japanese": {
    appTitle: "先住民族言語学習",
    welcome: "先住民族言語学習アプリへようこそ",
    welcomeMessage: "先住民族言語の美しさを発見しよう",
    welcomeSubtext: "私たちの遺産とつながる言語を保存し、学ぶ旅に出かけましょう",
    selectLanguage: "学習する言語を選択してください：",
    start: "学習を始める",
    lesson: "レッスン",
    exercise: "練習",
    check: "答えを確認",
    correct: "正解！",
    incorrect: "もう一度試してください",
    next: "次へ",
    back: "戻る",
    settings: "設定",
    interfaceLanguage: "インターフェース言語：",
    about: "について",
    progress: "進捗",
    vocabulary: "語彙",
    phrases: "一般的なフレーズ",
    grammar: "文法",
    quiz: "クイズ",
    home: "ホーム",
    matching: "マッチング",
    multipleChoice: "多肢選択",
    completed: "完了",
    pronunciation: "発音",
    cultural: "文化的メモ",
    flashcards: "フラッシュカード",
    speakingPractice: "会話練習",
    listeningPractice: "リスニング練習",
    dictionary: "辞書",
    favoriteWords: "お気に入りの単語",
    communityForum: "コミュニティフォーラム",
    communityForumHero: "言語コミュニティに参加しよう",
    communityForumSubtext: "他の学習者とつながり、リソースを共有し、先住民族言語について議論しましょう",
    profile: "プロフィール",
    achievements: "実績",
    review: "レビュー",
    searchPlaceholder: "単語やフレーズを検索...",
    lessonTitle: "言語レッスン",
    topicViewTitle: "トピック - 先住民族言語学習",
    loadingTopic: "トピックを読み込んでいます...",
    orSignInWith: "または次でサインイン：",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "サインイン",
    signInTitle: "サインイン - 先住民族言語学習",
    register: "登録",
    registerTitle: "登録 - 先住民族言語学習",
    email: "メールアドレス",
    password: "パスワード",
    confirmPassword: "パスワードを確認",
    username: "ユーザー名",
    signInButton: "サインイン",
    registerButton: "登録",
    noAccount: "アカウントをお持ちでないですか？",
    haveAccount: "すでにアカウントをお持ちですか？",
    profile: "プロフィール",
    logout: "ログアウト",
    // Forum
    forum: "フォーラム",
    forumTitle: "コミュニティフォーラム - 先住民族言語学習",
    communityForum: "コミュニティフォーラム",
    newTopic: "新しいトピック",
    categories: "カテゴリー",
    generalDiscussion: "一般的な議論",
    generalDiscussionDesc: "先住民族言語に関連するあらゆることについて議論する",
    learningTips: "学習のヒント",
    learningTipsDesc: "言語学習戦略を共有し発見する",
    resources: "リソース",
    resourcesDesc: "書籍、ウェブサイト、その他の学習教材を共有する",
    events: "イベント",
    eventsDesc: "今後の言語イベントや集まり",
    recentTopics: "最近のトピック",
    noTopicsYet: "まだトピックがありません。最初に作成しましょう！",
    createNewTopic: "新しいトピックを作成",
    topicTitle: "タイトル",
    category: "カテゴリー",
    content: "内容",
    createTopic: "トピックを作成",
    backToForum: "← フォーラムに戻る",
    replies: "返信",
    noRepliesYet: "まだ返信がありません。最初に返信しましょう！",
    postReply: "返信を投稿",
    submitReply: "返信を送信",
    signInToReply: "返信を投稿するにはサインインしてください。"
  },
  "Chinese": {
    appTitle: "原住民语言学习",
    welcome: "欢迎使用原住民语言学习应用",
    welcomeMessage: "探索原住民语言的美丽",
    welcomeSubtext: "踏上保护和学习连接我们与传统的语言之旅",
    selectLanguage: "选择要学习的语言：",
    start: "开始学习",
    lesson: "课程",
    exercise: "练习",
    check: "检查答案",
    correct: "正确！",
    incorrect: "再试一次",
    next: "下一个",
    back: "返回",
    settings: "设置",
    interfaceLanguage: "界面语言：",
    about: "关于",
    progress: "进度",
    vocabulary: "词汇",
    phrases: "常用短语",
    grammar: "语法",
    quiz: "测验",
    home: "首页",
    matching: "匹配",
    multipleChoice: "多项选择",
    completed: "已完成",
    pronunciation: "发音",
    cultural: "文化笔记",
    flashcards: "抽认卡",
    speakingPractice: "口语练习",
    listeningPractice: "听力练习",
    dictionary: "词典",
    favoriteWords: "收藏词汇",
    communityForum: "社区论坛",
    communityForumHero: "加入我们的语言社区",
    communityForumSubtext: "与其他学习者联系，分享资源，讨论原住民语言",
    profile: "个人资料",
    achievements: "成就",
    review: "复习",
    searchPlaceholder: "搜索单词或短语...",
    lessonTitle: "语言课程",
    topicViewTitle: "主题 - 原住民语言学习",
    loadingTopic: "正在加载主题...",
    orSignInWith: "或使用以下方式登录：",
    signInWithGoogle: "谷歌",
    signInWithDiscord: "Discord",
    signInWithFacebook: "脸书",
    // Authentication
    signIn: "登录",
    signInTitle: "登录 - 原住民语言学习",
    register: "注册",
    registerTitle: "注册 - 原住民语言学习",
    email: "电子邮件",
    password: "密码",
    confirmPassword: "确认密码",
    username: "用户名",
    signInButton: "登录",
    registerButton: "注册",
    noAccount: "还没有账号？",
    haveAccount: "已有账号？",
    profile: "个人资料",
    logout: "退出登录",
    // Forum
    forum: "论坛",
    forumTitle: "社区论坛 - 原住民语言学习",
    communityForum: "社区论坛",
    newTopic: "新主题",
    categories: "分类",
    generalDiscussion: "一般讨论",
    generalDiscussionDesc: "讨论与原住民语言相关的任何内容",
    learningTips: "学习技巧",
    learningTipsDesc: "分享和发现语言学习策略",
    resources: "资源",
    resourcesDesc: "分享书籍、网站和其他学习材料",
    events: "活动",
    eventsDesc: "即将举行的语言活动和聚会",
    recentTopics: "最近的主题",
    noTopicsYet: "暂无主题。成为第一个创建主题的人！",
    createNewTopic: "创建新主题",
    topicTitle: "标题",
    category: "分类",
    content: "内容",
    createTopic: "创建主题",
    backToForum: "← 返回论坛",
    replies: "回复",
    noRepliesYet: "暂无回复。成为第一个回复的人！",
    postReply: "发表回复",
    submitReply: "提交回复",
    signInToReply: "请登录后发表回复。"
  },
  // Mongolian translations
  "Mongolian": {
    appTitle: "Уугуул хэл сурах",
    welcome: "Уугуул хэл сурах аппликейшнд тавтай морил",
    welcomeMessage: "Уугуул хэлний гоо сайхныг нээ",
    welcomeSubtext: "Бидний өвийг холбосон хэлийг хадгалж, сурах аялалд гарцгаая",
    selectLanguage: "Сурах хэлээ сонгоно уу:",
    start: "Суралцаж эхлэх",
    lesson: "Хичээл",
    exercise: "Дасгал",
    check: "Хариултыг шалгах",
    correct: "Зөв!",
    incorrect: "Дахин оролдоно уу",
    next: "Дараах",
    back: "Буцах",
    settings: "Тохиргоо",
    interfaceLanguage: "Интерфейсийн хэл:",
    about: "Тухай",
    progress: "Ахиц",
    vocabulary: "Үгсийн сан",
    phrases: "Түгээмэл хэллэгүүд",
    grammar: "Хэл зүй",
    quiz: "Асуулт",
    home: "Нүүр хуудас",
    matching: "Тохируулах",
    multipleChoice: "Олон сонголт",
    completed: "Дууссан",
    pronunciation: "Дуудлага",
    cultural: "Соёлын тэмдэглэл",
    flashcards: "Флаш карт",
    speakingPractice: "Ярих дадлага",
    listeningPractice: "Сонсох дадлага",
    dictionary: "Толь бичиг",
    favoriteWords: "Дуртай үгс",
    communityForum: "Нийгэмлэгийн форум",
    communityForumHero: "Бидний хэлний нийгэмлэгт нэгдээрэй",
    communityForumSubtext: "Бусад суралцагчидтай холбогдож, нөөцөө хуваалцаж, уугуул хэлний талаар ярилцаарай",
    profile: "Профайл",
    achievements: "Амжилтууд",
    review: "Дүгнэлт",
    searchPlaceholder: "Үг эсвэл хэллэг хайх...",
    lessonTitle: "Хэлний хичээл",
    topicViewTitle: "Сэдэв - Уугуул хэл сурах",
    loadingTopic: "Сэдэв ачаалж байна...",
    orSignInWith: "Эсвэл дараахаар нэвтрэх:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "Нэвтрэх",
    signInTitle: "Нэвтрэх - Уугуул хэл сурах",
    register: "Бүртгүүлэх",
    registerTitle: "Бүртгүүлэх - Уугуул хэл сурах",
    email: "Имэйл",
    password: "Нууц үг",
    confirmPassword: "Нууц үгээ баталгаажуулах",
    username: "Хэрэглэгчийн нэр",
    signInButton: "Нэвтрэх",
    registerButton: "Бүртгүүлэх",
    noAccount: "Бүртгэл байхгүй юу?",
    haveAccount: "Аль хэдийн бүртгэлтэй юу?",
    profile: "Профайл",
    logout: "Гарах",
    // Forum
    forum: "Форум",
    forumTitle: "Нийгэмлэгийн форум - Уугуул хэл сурах",
    communityForum: "Нийгэмлэгийн форум",
    newTopic: "Шинэ сэдэв",
    categories: "Ангиллууд",
    generalDiscussion: "Ерөнхий хэлэлцүүлэг",
    generalDiscussionDesc: "Уугуул хэлтэй холбоотой аливаа зүйлийг хэлэлцэх",
    learningTips: "Суралцах зөвлөмжүүд",
    learningTipsDesc: "Хэл сурах стратегиудыг хуваалцаж, нээх",
    resources: "Нөөц",
    resourcesDesc: "Ном, вэбсайт болон бусад сургалтын материалуудыг хуваалцах",
    events: "Үйл явдлууд",
    eventsDesc: "Ирээдүйн хэлний үйл явдлууд болон цугларалтууд",
    recentTopics: "Сүүлийн үеийн сэдвүүд",
    noTopicsYet: "Одоогоор сэдэв байхгүй байна. Анхны сэдэв үүсгэгч болоорой!",
    createNewTopic: "Шинэ сэдэв үүсгэх",
    topicTitle: "Гарчиг",
    category: "Ангилал",
    content: "Агуулга",
    createTopic: "Сэдэв үүсгэх",
    backToForum: "← Форум руу буцах",
    replies: "Хариултууд",
    noRepliesYet: "Одоогоор хариулт байхгүй байна. Анхны хариулт өгөгч болоорой!",
    postReply: "Хариулт нийтлэх",
    submitReply: "Хариулт илгээх",
    signInToReply: "Хариулт нийтлэхийн тулд нэвтэрнэ үү."
  },
  // Korean translations
  "Korean": {
    appTitle: "원주민 언어 학습",
    welcome: "원주민 언어 학습 앱에 오신 것을 환영합니다",
    welcomeMessage: "원주민 언어의 아름다움을 발견하세요",
    welcomeSubtext: "우리의 유산과 연결되는 언어를 보존하고 배우는 여정을 시작하세요",
    selectLanguage: "학습할 언어 선택:",
    start: "학습 시작",
    lesson: "수업",
    exercise: "연습",
    check: "답변 확인",
    correct: "정답!",
    incorrect: "다시 시도하세요",
    next: "다음",
    back: "뒤로",
    settings: "설정",
    interfaceLanguage: "인터페이스 언어:",
    about: "소개",
    progress: "진행 상황",
    vocabulary: "어휘",
    phrases: "일반 문구",
    grammar: "문법",
    quiz: "퀴즈",
    home: "홈",
    matching: "짝 맞추기",
    multipleChoice: "객관식",
    completed: "완료됨",
    pronunciation: "발음",
    cultural: "문화 노트",
    flashcards: "플래시카드",
    speakingPractice: "말하기 연습",
    listeningPractice: "듣기 연습",
    dictionary: "사전",
    favoriteWords: "즐겨찾는 단어",
    communityForum: "커뮤니티 포럼",
    communityForumHero: "우리 언어 커뮤니티에 참여하세요",
    communityForumSubtext: "다른 학습자와 연결하고, 자원을 공유하고, 원주민 언어에 대해 토론하세요",
    profile: "프로필",
    achievements: "성취",
    review: "복습",
    searchPlaceholder: "단어나 문구 검색...",
    lessonTitle: "언어 수업",
    topicViewTitle: "주제 - 원주민 언어 학습",
    loadingTopic: "주제 로딩 중...",
    orSignInWith: "또는 다음으로 로그인:",
    signInWithGoogle: "구글",
    signInWithDiscord: "디스코드",
    signInWithFacebook: "페이스북",
    // Authentication
    signIn: "로그인",
    signInTitle: "로그인 - 원주민 언어 학습",
    register: "회원가입",
    registerTitle: "회원가입 - 원주민 언어 학습",
    email: "이메일",
    password: "비밀번호",
    confirmPassword: "비밀번호 확인",
    username: "사용자 이름",
    signInButton: "로그인",
    registerButton: "회원가입",
    noAccount: "계정이 없으신가요?",
    haveAccount: "이미 계정이 있으신가요?",
    profile: "프로필",
    logout: "로그아웃",
    // Forum
    forum: "포럼",
    forumTitle: "커뮤니티 포럼 - 원주민 언어 학습",
    communityForum: "커뮤니티 포럼",
    newTopic: "새 주제",
    categories: "카테고리",
    generalDiscussion: "일반 토론",
    generalDiscussionDesc: "원주민 언어와 관련된 모든 것에 대해 토론하세요",
    learningTips: "학습 팁",
    learningTipsDesc: "학습 전략을 공유하고 토론하세요",
    resources: "자원",
    resourcesDesc: "책, 웹사이트 및 기타 학습 자료 공유",
    events: "이벤트",
    eventsDesc: "원주민 언어와 관련된 이벤트 및 행사",
    recentTopics: "최근 주제",
    noTopicsYet: "아직 주제가 없습니다. 첫 번째 주제 작성자가 되세요!",
    createNewTopic: "새 주제 만들기",
    topicTitle: "제목",
    category: "카테고리",
    content: "내용",
    createTopic: "주제 만들기",
    backToForum: "← 포럼으로 돌아가기",
    replies: "답글",
    noRepliesYet: "아직 답글이 없습니다. 첫 번째 답글 작성자가 되세요!",
    postReply: "답글 작성",
    submitReply: "답글 제출",
    signInToReply: "답글을 작성하려면 로그인하세요."
  },
  "Italian": {
    appTitle: "Apprendimento delle Lingue Indigene",
    welcome: "Benvenuto nell'app di apprendimento delle lingue indigene",
    welcomeMessage: "Scopri la bellezza delle lingue indigene",
    welcomeSubtext: "Intraprendi un viaggio per preservare e imparare le lingue che ci collegano al nostro patrimonio",
    selectLanguage: "Seleziona una lingua da imparare:",
    start: "Inizia ad imparare",
    lesson: "Lezione",
    exercise: "Esercizio",
    check: "Controlla risposta",
    correct: "Corretto!",
    incorrect: "Riprova",
    next: "Avanti",
    back: "Indietro",
    settings: "Impostazioni",
    interfaceLanguage: "Lingua dell'interfaccia:",
    about: "Informazioni",
    progress: "Progressi",
    vocabulary: "Vocabolario",
    phrases: "Frasi comuni",
    grammar: "Grammatica",
    quiz: "Quiz",
    home: "Home",
    matching: "Abbinamento",
    multipleChoice: "Scelta multipla",
    completed: "Completato",
    pronunciation: "Pronuncia",
    cultural: "Note culturali",
    flashcards: "Flashcard",
    speakingPractice: "Pratica di conversazione",
    listeningPractice: "Pratica di ascolto",
    dictionary: "Dizionario",
    favoriteWords: "Parole preferite",
    communityForum: "Forum della comunità",
    communityForumHero: "Unisciti alla nostra comunità linguistica",
    communityForumSubtext: "Connettiti con altri studenti, condividi risorse e discuti delle lingue indigene",
    profile: "Profilo",
    achievements: "Risultati",
    review: "Revisione",
    searchPlaceholder: "Cerca parole o frasi...",
    lessonTitle: "Lezione di lingua",
    topicViewTitle: "Argomento - Apprendimento delle Lingue Indigene",
    loadingTopic: "Caricamento argomento...",
    orSignInWith: "Oppure accedi con:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "Accedi",
    signInTitle: "Accedi - Apprendimento delle Lingue Indigene",
    register: "Registrati",
    registerTitle: "Registrati - Apprendimento delle Lingue Indigene",
    email: "Email",
    password: "Password",
    confirmPassword: "Conferma password",
    username: "Nome utente",
    signInButton: "Accedi",
    registerButton: "Registrati",
    noAccount: "Non hai un account?",
    haveAccount: "Hai già un account?",
    profile: "Profilo",
    logout: "Esci",
    // Forum
    forum: "Forum",
    forumTitle: "Forum della comunità - Apprendimento delle Lingue Indigene",
    communityForum: "Forum della comunità",
    newTopic: "Nuovo argomento",
    categories: "Categorie",
    generalDiscussion: "Discussione generale",
    generalDiscussionDesc: "Discuti di qualsiasi cosa relativa alle lingue indigene",
    learningTips: "Consigli di apprendimento",
    learningTipsDesc: "Condividi e scopri strategie di apprendimento linguistico",
    resources: "Risorse",
    resourcesDesc: "Condividi libri, siti web e altri materiali didattici",
    events: "Eventi",
    eventsDesc: "Prossimi eventi linguistici e incontri",
    recentTopics: "Argomenti recenti",
    noTopicsYet: "Ancora nessun argomento. Sii il primo a crearne uno!",
    createNewTopic: "Crea nuovo argomento",
    topicTitle: "Titolo",
    category: "Categoria",
    content: "Contenuto",
    createTopic: "Crea argomento",
    backToForum: "← Torna al forum",
    replies: "Risposte",
    noRepliesYet: "Ancora nessuna risposta. Sii il primo a rispondere!",
    postReply: "Pubblica una risposta",
    submitReply: "Invia risposta",
    signInToReply: "Accedi per pubblicare una risposta."
  },
  // Danish translations
  "Danish": {
    appTitle: "Indfødt Sprogindlæring",
    welcome: "Velkommen til appen for indfødt sprogindlæring",
    welcomeMessage: "Opdag skønheden i indfødte sprog",
    welcomeSubtext: "Begiv dig ud på en rejse for at bevare og lære sprog, der forbinder os med vores arv",
    selectLanguage: "Vælg et sprog at lære:",
    start: "Start læring",
    lesson: "Lektion",
    exercise: "Øvelse",
    check: "Tjek svar",
    correct: "Korrekt!",
    incorrect: "Prøv igen",
    next: "Næste",
    back: "Tilbage",
    settings: "Indstillinger",
    interfaceLanguage: "Grænsefladesprog:",
    about: "Om",
    progress: "Fremskridt",
    vocabulary: "Ordforråd",
    phrases: "Almindelige sætninger",
    grammar: "Grammatik",
    quiz: "Quiz",
    home: "Hjem",
    matching: "Matching",
    multipleChoice: "Multiple choice",
    completed: "Fuldført",
    pronunciation: "Udtale",
    cultural: "Kulturelle noter",
    flashcards: "Flashcards",
    speakingPractice: "Taleøvelse",
    listeningPractice: "Lytteøvelse",
    dictionary: "Ordbog",
    favoriteWords: "Favoritord",
    communityForum: "Fællesskabsforum",
    communityForumHero: "Bliv en del af vores sprogfællesskab",
    communityForumSubtext: "Forbind med andre elever, del ressourcer og diskuter indfødte sprog",
    profile: "Profil",
    achievements: "Præstationer",
    review: "Gennemgang",
    searchPlaceholder: "Søg efter ord eller sætninger...",
    lessonTitle: "Sprogundervisning",
    topicViewTitle: "Emne - Indfødt Sprogindlæring",
    loadingTopic: "Indlæser emne...",
    orSignInWith: "Eller log ind med:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "Log ind",
    signInTitle: "Log ind - Indfødt Sprogindlæring",
    register: "Registrer",
    registerTitle: "Registrer - Indfødt Sprogindlæring",
    email: "Email",
    password: "Adgangskode",
    confirmPassword: "Bekræft adgangskode",
    username: "Brugernavn",
    signInButton: "Log ind",
    registerButton: "Registrer",
    noAccount: "Har du ikke en konto?",
    haveAccount: "Har du allerede en konto?",
    profile: "Profil",
    logout: "Log ud",
    // Forum
    forum: "Forum",
    forumTitle: "Fællesskabsforum - Indfødt Sprogindlæring",
    communityForum: "Fællesskabsforum",
    newTopic: "Nyt emne",
    categories: "Kategorier",
    generalDiscussion: "Generel diskussion",
    generalDiscussionDesc: "Diskuter alt relateret til indfødte sprog",
    learningTips: "Læringstips",
    learningTipsDesc: "Del og opdag strategier for sprogindlæring",
    resources: "Ressourcer",
    resourcesDesc: "Del bøger, hjemmesider og andre læringsmaterialer",
    events: "Begivenheder",
    eventsDesc: "Kommende sprogbegivenheder og sammenkomster",
    recentTopics: "Seneste emner",
    noTopicsYet: "Endnu ingen emner. Vær den første til at oprette et!",
    createNewTopic: "Opret nyt emne",
    topicTitle: "Titel",
    category: "Kategori",
    content: "Indhold",
    createTopic: "Opret emne",
    backToForum: "← Tilbage til forum",
    replies: "Svar",
    noRepliesYet: "Endnu ingen svar. Vær den første til at svare!",
    postReply: "Skriv et svar",
    submitReply: "Send svar",
    signInToReply: "Log venligst ind for at skrive et svar."
  },
  "Swedish": {
    appTitle: "Infödd Språkinlärning",
    welcome: "Välkommen till appen för infödd språkinlärning",
    welcomeMessage: "Upptäck skönheten i infödda språk",
    welcomeSubtext: "Ge dig ut på en resa för att bevara och lära dig språk som kopplar oss till vårt arv",
    selectLanguage: "Välj ett språk att lära dig:",
    start: "Börja lära dig",
    lesson: "Lektion",
    exercise: "Övning",
    check: "Kontrollera svar",
    correct: "Rätt!",
    incorrect: "Försök igen",
    next: "Nästa",
    back: "Tillbaka",
    settings: "Inställningar",
    interfaceLanguage: "Gränssnittsspråk:",
    about: "Om",
    progress: "Framsteg",
    vocabulary: "Ordförråd",
    phrases: "Vanliga fraser",
    grammar: "Grammatik",
    quiz: "Quiz",
    home: "Hem",
    matching: "Matchning",
    multipleChoice: "Flerval",
    completed: "Slutförd",
    pronunciation: "Uttal",
    cultural: "Kulturella anteckningar",
    flashcards: "Flashkort",
    speakingPractice: "Talövning",
    listeningPractice: "Lyssningsövning",
    dictionary: "Ordbok",
    favoriteWords: "Favoritord",
    communityForum: "Gemenskapsforum",
    communityForumHero: "Gå med i vår språkgemenskap",
    communityForumSubtext: "Anslut med andra elever, dela resurser och diskutera infödda språk",
    profile: "Profil",
    achievements: "Prestationer",
    review: "Granska",
    searchPlaceholder: "Sök efter ord eller fraser...",
    lessonTitle: "Språklektion",
    topicViewTitle: "Ämne - Infödd Språkinlärning",
    loadingTopic: "Laddar ämne...",
    orSignInWith: "Eller logga in med:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    // Authentication
    signIn: "Logga in",
    signInTitle: "Logga in - Infödd Språkinlärning",
    register: "Registrera",
    registerTitle: "Registrera - Infödd Språkinlärning",
    email: "E-post",
    password: "Lösenord",
    confirmPassword: "Bekräfta lösenord",
    username: "Användarnamn",
    signInButton: "Logga in",
    registerButton: "Registrera",
    noAccount: "Har du inget konto?",
    haveAccount: "Har du redan ett konto?",
    profile: "Profil",
    logout: "Logga ut",
    // Forum
    forum: "Forum",
    forumTitle: "Gemenskapsforum - Infödd Språkinlärning",
    communityForum: "Gemenskapsforum",
    newTopic: "Nytt ämne",
    categories: "Kategorier",
    generalDiscussion: "Allmän diskussion",
    generalDiscussionDesc: "Diskutera allt relaterat till infödda språk",
    learningTips: "Inlärningstips",
    learningTipsDesc: "Dela och upptäck strategier för språkinlärning",
    resources: "Resurser",
    resourcesDesc: "Dela böcker, webbplatser och annat läromaterial",
    events: "Evenemang",
    eventsDesc: "Kommande språkevenemang och sammankomster",
    recentTopics: "Senaste ämnen",
    noTopicsYet: "Inga ämnen ännu. Var först med att skapa ett!",
    createNewTopic: "Skapa nytt ämne",
    topicTitle: "Titel",
    category: "Kategori",
    content: "Innehåll",
    createTopic: "Skapa ämne",
    backToForum: "← Tillbaka till forum",
    replies: "Svar",
    noRepliesYet: "Inga svar ännu. Var först med att svara!",
    postReply: "Skriv ett svar",
    submitReply: "Skicka svar",
    signInToReply: "Logga in för att skriva ett svar."
  },
  "Polish": {
    appTitle: "Nauka Języków Rdzennych",
    welcome: "Witamy w aplikacji do nauki języków rdzennych",
    welcomeMessage: "Odkryj piękno języków rdzennych",
    welcomeSubtext: "Wyrusz w podróż, aby zachować i nauczyć się języków, które łączą nas z naszym dziedzictwem",
    selectLanguage: "Wybierz język do nauki:",
    start: "Rozpocznij naukę",
    lesson: "Lekcja",
    exercise: "Ćwiczenie",
    check: "Sprawdź odpowiedź",
    correct: "Poprawnie!",
    incorrect: "Spróbuj ponownie",
    next: "Dalej",
    back: "Wstecz",
    settings: "Ustawienia",
    interfaceLanguage: "Język interfejsu:",
    about: "O nas",
    progress: "Postęp",
    vocabulary: "Słownictwo",
    phrases: "Popularne zwroty",
    grammar: "Gramatyka",
    quiz: "Quiz",
    home: "Strona główna",
    matching: "Dopasowywanie",
    multipleChoice: "Wielokrotny wybór",
    completed: "Ukończone",
    pronunciation: "Wymowa",
    cultural: "Notatki kulturowe",
    flashcards: "Fiszki",
    speakingPractice: "Ćwiczenie mówienia",
    listeningPractice: "Ćwiczenie słuchania",
    dictionary: "Słownik",
    favoriteWords: "Ulubione słowa",
    communityForum: "Forum społeczności",
    communityForumHero: "Dołącz do naszej społeczności językowej",
    communityForumSubtext: "Połącz się z innymi uczącymi się, udostępniaj zasoby i dyskutuj o językach rdzennych",
    profile: "Profil",
    achievements: "Osiągnięcia",
    review: "Powtórka",
    searchPlaceholder: "Szukaj słów lub zwrotów...",
    lessonTitle: "Lekcja językowa",
    topicViewTitle: "Temat - Nauka Języków Rdzennych",
    loadingTopic: "Ładowanie tematu...",
    orSignInWith: "Lub zaloguj się przez:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Zaloguj się",
    signInTitle: "Logowanie - Nauka Języków Rdzennych",
    register: "Zarejestruj się",
    registerTitle: "Rejestracja - Nauka Języków Rdzennych",
    email: "Email",
    password: "Hasło",
    confirmPassword: "Potwierdź hasło",
    username: "Nazwa użytkownika",
    signInButton: "Zaloguj się",
    registerButton: "Zarejestruj się",
    noAccount: "Nie masz konta?",
    haveAccount: "Masz już konto?",
    profile: "Profil",
    logout: "Wyloguj się",
    
    // Forum
    forum: "Forum",
    forumTitle: "Forum społeczności - Nauka Języków Rdzennych",
    communityForum: "Forum społeczności",
    newTopic: "Nowy temat",
    categories: "Kategorie",
    generalDiscussion: "Dyskusja ogólna",
    generalDiscussionDesc: "Dyskutuj o wszystkim związanym z językami rdzennymi",
    learningTips: "Wskazówki do nauki",
    learningTipsDesc: "Udostępniaj i odkrywaj strategie nauki języka",
    resources: "Zasoby",
    resourcesDesc: "Udostępniaj książki, strony internetowe i inne materiały edukacyjne",
    events: "Wydarzenia",
    eventsDesc: "Nadchodzące wydarzenia językowe i spotkania",
    recentTopics: "Ostatnie tematy",
    noTopicsYet: "Brak tematów. Bądź pierwszym, który utworzy temat!",
    createNewTopic: "Utwórz nowy temat",
    topicTitle: "Tytuł",
    category: "Kategoria",
    content: "Treść",
    createTopic: "Utwórz temat",
    backToForum: "← Powrót do forum",
    replies: "Odpowiedzi",
    noRepliesYet: "Brak odpowiedzi. Bądź pierwszym, który odpowie!",
    postReply: "Opublikuj odpowiedź",
    submitReply: "Wyślij odpowiedź",
    signInToReply: "Zaloguj się, aby opublikować odpowiedź."
  },
  "Finnish": {
    appTitle: "Alkuperäiskielten Oppiminen",
    welcome: "Tervetuloa alkuperäiskielten oppimissovellukseen",
    welcomeMessage: "Löydä alkuperäiskielten kauneus",
    welcomeSubtext: "Lähde matkalle säilyttämään ja oppimaan kieliä, jotka yhdistävät meidät perintöömme",
    selectLanguage: "Valitse opittava kieli:",
    start: "Aloita oppiminen",
    lesson: "Oppitunti",
    exercise: "Harjoitus",
    check: "Tarkista vastaus",
    correct: "Oikein!",
    incorrect: "Yritä uudelleen",
    next: "Seuraava",
    back: "Takaisin",
    settings: "Asetukset",
    interfaceLanguage: "Käyttöliittymän kieli:",
    about: "Tietoa",
    progress: "Edistyminen",
    vocabulary: "Sanasto",
    phrases: "Yleiset fraasit",
    grammar: "Kielioppi",
    quiz: "Tietovisa",
    home: "Koti",
    matching: "Yhdistäminen",
    multipleChoice: "Monivalinta",
    completed: "Suoritettu",
    pronunciation: "Ääntäminen",
    cultural: "Kulttuuriset huomautukset",
    flashcards: "Muistikortit",
    speakingPractice: "Puheharjoitus",
    listeningPractice: "Kuunteluharjoitus",
    dictionary: "Sanakirja",
    favoriteWords: "Suosikkisanat",
    communityForum: "Yhteisöfoorumi",
    communityForumHero: "Liity kieliyhteisöömme",
    communityForumSubtext: "Verkostoidu muiden oppijoiden kanssa, jaa resursseja ja keskustele alkuperäiskielistä",
    profile: "Profiili",
    achievements: "Saavutukset",
    review: "Kertaus",
    searchPlaceholder: "Etsi sanoja tai fraaseja...",
    lessonTitle: "Kielitunti",
    topicViewTitle: "Aihe - Alkuperäiskielten Oppiminen",
    loadingTopic: "Ladataan aihetta...",
    orSignInWith: "Tai kirjaudu sisään:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Kirjaudu sisään",
    signInTitle: "Kirjaudu sisään - Alkuperäiskielten Oppiminen",
    register: "Rekisteröidy",
    registerTitle: "Rekisteröidy - Alkuperäiskielten Oppiminen",
    email: "Sähköposti",
    password: "Salasana",
    confirmPassword: "Vahvista salasana",
    username: "Käyttäjänimi",
    signInButton: "Kirjaudu sisään",
    registerButton: "Rekisteröidy",
    noAccount: "Eikö sinulla ole tiliä?",
    haveAccount: "Onko sinulla jo tili?",
    profile: "Profiili",
    logout: "Kirjaudu ulos",
    
    // Forum
    forum: "Foorumi",
    forumTitle: "Yhteisöfoorumi - Alkuperäiskielten Oppiminen",
    communityForum: "Yhteisöfoorumi",
    newTopic: "Uusi aihe",
    categories: "Kategoriat",
    generalDiscussion: "Yleinen keskustelu",
    generalDiscussionDesc: "Keskustele mistä tahansa alkuperäiskieliin liittyvästä",
    learningTips: "Oppimisvinkit",
    learningTipsDesc: "Jaa ja löydä kielenoppimisstrategioita",
    resources: "Resurssit",
    resourcesDesc: "Jaa kirjoja, verkkosivustoja ja muita oppimismateriaaleja",
    events: "Tapahtumat",
    eventsDesc: "Tulevat kielitapahtumat ja kokoontumiset",
    recentTopics: "Viimeisimmät aiheet",
    noTopicsYet: "Ei vielä aiheita. Ole ensimmäinen, joka luo aiheen!",
    createNewTopic: "Luo uusi aihe",
    topicTitle: "Otsikko",
    category: "Kategoria",
    content: "Sisältö",
    createTopic: "Luo aihe",
    backToForum: "← Takaisin foorumille",
    replies: "Vastaukset",
    noRepliesYet: "Ei vielä vastauksia. Ole ensimmäinen, joka vastaa!",
    postReply: "Lähetä vastaus",
    submitReply: "Lähetä vastaus",
    signInToReply: "Kirjaudu sisään lähettääksesi vastauksen."
  },
  "Hungarian": {
    appTitle: "Őshonos Nyelvek Tanulása",
    welcome: "Üdvözöljük az őshonos nyelvek tanulása alkalmazásban",
    welcomeMessage: "Fedezze fel az őshonos nyelvek szépségét",
    welcomeSubtext: "Induljon el egy utazásra, hogy megőrizze és megtanulja azokat a nyelveket, amelyek összekapcsolnak minket örökségünkkel",
    selectLanguage: "Válasszon egy nyelvet a tanuláshoz:",
    start: "Tanulás kezdése",
    lesson: "Lecke",
    exercise: "Gyakorlat",
    check: "Válasz ellenőrzése",
    correct: "Helyes!",
    incorrect: "Próbálja újra",
    next: "Következő",
    back: "Vissza",
    settings: "Beállítások",
    interfaceLanguage: "Felület nyelve:",
    about: "Rólunk",
    progress: "Haladás",
    vocabulary: "Szókincs",
    phrases: "Gyakori kifejezések",
    grammar: "Nyelvtan",
    quiz: "Kvíz",
    home: "Kezdőlap",
    matching: "Párosítás",
    multipleChoice: "Feleletválasztós",
    completed: "Befejezve",
    pronunciation: "Kiejtés",
    cultural: "Kulturális jegyzetek",
    flashcards: "Tanulókártyák",
    speakingPractice: "Beszédgyakorlat",
    listeningPractice: "Hallásgyakorlat",
    dictionary: "Szótár",
    favoriteWords: "Kedvenc szavak",
    communityForum: "Közösségi fórum",
    communityForumHero: "Csatlakozzon nyelvi közösségünkhöz",
    communityForumSubtext: "Kapcsolódjon más tanulókkal, osszon meg forrásokat és vitasson meg őshonos nyelveket",
    profile: "Profil",
    achievements: "Eredmények",
    review: "Áttekintés",
    searchPlaceholder: "Keressen szavakat vagy kifejezéseket...",
    lessonTitle: "Nyelvi lecke",
    topicViewTitle: "Téma - Őshonos Nyelvek Tanulása",
    loadingTopic: "Téma betöltése...",
    orSignInWith: "Vagy jelentkezzen be ezzel:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Bejelentkezés",
    signInTitle: "Bejelentkezés - Őshonos Nyelvek Tanulása",
    register: "Regisztráció",
    registerTitle: "Regisztráció - Őshonos Nyelvek Tanulása",
    email: "E-mail",
    password: "Jelszó",
    confirmPassword: "Jelszó megerősítése",
    username: "Felhasználónév",
    signInButton: "Bejelentkezés",
    registerButton: "Regisztráció",
    noAccount: "Nincs még fiókja?",
    haveAccount: "Már van fiókja?",
    profile: "Profil",
    logout: "Kijelentkezés",
    
    // Forum
    forum: "Fórum",
    forumTitle: "Közösségi fórum - Őshonos Nyelvek Tanulása",
    communityForum: "Közösségi fórum",
    newTopic: "Új téma",
    categories: "Kategóriák",
    generalDiscussion: "Általános megbeszélés",
    generalDiscussionDesc: "Vitasson meg bármit, ami az őshonos nyelvekkel kapcsolatos",
    learningTips: "Tanulási tippek",
    learningTipsDesc: "Osszon meg és fedezzen fel nyelvtanulási stratégiákat",
    resources: "Források",
    resourcesDesc: "Osszon meg könyveket, weboldalakat és egyéb tanulási anyagokat",
    events: "Események",
    eventsDesc: "Közelgő nyelvi események és találkozók",
    recentTopics: "Legutóbbi témák",
    noTopicsYet: "Még nincsenek témák. Legyen Ön az első, aki létrehoz egyet!",
    createNewTopic: "Új téma létrehozása",
    topicTitle: "Cím",
    category: "Kategória",
    content: "Tartalom",
    createTopic: "Téma létrehozása",
    backToForum: "← Vissza a fórumra",
    replies: "Válaszok",
    noRepliesYet: "Még nincsenek válaszok. Legyen Ön az első, aki válaszol!",
    postReply: "Válasz közzététele",
    submitReply: "Válasz közzététele",
    signInToReply: "Jelentkezzen be, hogy válaszoljon."
  },
  "Vietnamese": {
    appTitle: "Học Ngôn Ngữ Bản Địa",
    welcome: "Chào mừng đến với ứng dụng học ngôn ngữ bản địa",
    welcomeMessage: "Khám phá vẻ đẹp của các ngôn ngữ bản địa",
    welcomeSubtext: "Bắt đầu hành trình để bảo tồn và học những ngôn ngữ kết nối chúng ta với di sản của mình",
    selectLanguage: "Chọn một ngôn ngữ để học:",
    start: "Bắt đầu học",
    lesson: "Bài học",
    exercise: "Bài tập",
    check: "Kiểm tra câu trả lời",
    correct: "Đúng!",
    incorrect: "Hãy thử lại",
    next: "Tiếp theo",
    back: "Quay lại",
    settings: "Cài đặt",
    interfaceLanguage: "Ngôn ngữ giao diện:",
    about: "Giới thiệu",
    progress: "Tiến độ",
    vocabulary: "Từ vựng",
    phrases: "Cụm từ thông dụng",
    grammar: "Ngữ pháp",
    quiz: "Câu đố",
    home: "Trang chủ",
    matching: "Ghép cặp",
    multipleChoice: "Trắc nghiệm",
    completed: "Đã hoàn thành",
    pronunciation: "Phát âm",
    cultural: "Ghi chú văn hóa",
    flashcards: "Thẻ ghi nhớ",
    speakingPractice: "Luyện nói",
    listeningPractice: "Luyện nghe",
    dictionary: "Từ điển",
    favoriteWords: "Từ yêu thích",
    communityForum: "Diễn đàn cộng đồng",
    communityForumHero: "Tham gia cộng đồng ngôn ngữ của chúng tôi",
    communityForumSubtext: "Kết nối với những người học khác, chia sẻ tài nguyên và thảo luận về ngôn ngữ bản địa",
    profile: "Hồ sơ",
    achievements: "Thành tích",
    review: "Ôn tập",
    searchPlaceholder: "Tìm kiếm từ hoặc cụm từ...",
    lessonTitle: "Bài học ngôn ngữ",
    topicViewTitle: "Chủ đề - Học Ngôn Ngữ Bản Địa",
    loadingTopic: "Đang tải chủ đề...",
    orSignInWith: "Hoặc đăng nhập bằng:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Đăng nhập",
    signInTitle: "Đăng nhập - Học Ngôn Ngữ Bản Địa",
    register: "Đăng ký",
    registerTitle: "Đăng ký - Học Ngôn Ngữ Bản Địa",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    username: "Tên người dùng",
    signInButton: "Đăng nhập",
    registerButton: "Đăng ký",
    noAccount: "Chưa có tài khoản?",
    haveAccount: "Đã có tài khoản?",
    profile: "Hồ sơ",
    logout: "Đăng xuất",
    
    // Forum
    forum: "Diễn đàn",
    forumTitle: "Diễn đàn cộng đồng - Học Ngôn Ngữ Bản Địa",
    communityForum: "Diễn đàn cộng đồng",
    newTopic: "Chủ đề mới",
    categories: "Danh mục",
    generalDiscussion: "Thảo luận chung",
    generalDiscussionDesc: "Thảo luận về bất kỳ điều gì liên quan đến ngôn ngữ bản địa",
    learningTips: "Mẹo học tập",
    learningTipsDesc: "Chia sẻ và khám phá chiến lược học ngôn ngữ",
    resources: "Tài nguyên",
    resourcesDesc: "Chia sẻ sách, trang web và các tài liệu học tập khác",
    events: "Sự kiện",
    eventsDesc: "Sự kiện ngôn ngữ và gặp gỡ sắp tới",
    recentTopics: "Chủ đề gần đây",
    noTopicsYet: "Chưa có chủ đề nào. Hãy là người đầu tiên tạo chủ đề!",
    createNewTopic: "Tạo chủ đề mới",
    topicTitle: "Tiêu đề",
    category: "Danh mục",
    content: "Nội dung",
    createTopic: "Tạo chủ đề",
    backToForum: "← Quay lại diễn đàn",
    replies: "Trả lời",
    noRepliesYet: "Chưa có trả lời nào. Hãy là người đầu tiên trả lời!",
    postReply: "Đăng trả lời",
    submitReply: "Gửi trả lời",
    signInToReply: "Vui lòng đăng nhập để đăng trả lời."
  },
  "Hindi": {
    appTitle: "देशी भाषा सीखना",
    welcome: "देशी भाषा सीखने के ऐप में आपका स्वागत है",
    welcomeMessage: "देशी भाषाओं की सुंदरता की खोज करें",
    welcomeSubtext: "हमारी विरासत से जुड़ने वाली भाषाओं को संरक्षित करने और सीखने की यात्रा पर निकलें",
    selectLanguage: "सीखने के लिए एक भाषा चुनें:",
    start: "सीखना शुरू करें",
    lesson: "पाठ",
    exercise: "अभ्यास",
    check: "उत्तर जांचें",
    correct: "सही!",
    incorrect: "फिर से प्रयास करें",
    next: "अगला",
    back: "वापस",
    settings: "सेटिंग्स",
    interfaceLanguage: "इंटरफेस भाषा:",
    about: "हमारे बारे में",
    progress: "प्रगति",
    vocabulary: "शब्दावली",
    phrases: "आम वाक्यांश",
    grammar: "व्याकरण",
    quiz: "प्रश्नोत्तरी",
    home: "होम",
    matching: "मिलान",
    multipleChoice: "बहुविकल्पी",
    completed: "पूरा किया गया",
    pronunciation: "उच्चारण",
    cultural: "सांस्कृतिक नोट्स",
    flashcards: "फ्लैशकार्ड",
    speakingPractice: "बोलने का अभ्यास",
    listeningPractice: "सुनने का अभ्यास",
    dictionary: "शब्दकोश",
    favoriteWords: "पसंदीदा शब्द",
    communityForum: "समुदाय मंच",
    communityForumHero: "हमारे भाषा समुदाय में शामिल हों",
    communityForumSubtext: "अन्य सीखने वालों से जुड़ें, संसाधन साझा करें और देशी भाषाओं पर चर्चा करें",
    profile: "प्रोफाइल",
    achievements: "उपलब्धियां",
    review: "समीक्षा",
    searchPlaceholder: "शब्द या वाक्यांश खोजें...",
    lessonTitle: "भाषा पाठ",
    topicViewTitle: "विषय - देशी भाषा सीखना",
    loadingTopic: "विषय लोड हो रहा है...",
    orSignInWith: "या इससे साइन इन करें:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "साइन इन",
    signInTitle: "साइन इन - देशी भाषा सीखना",
    register: "पंजीकरण",
    registerTitle: "पंजीकरण - देशी भाषा सीखना",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    username: "उपयोगकर्ता नाम",
    signInButton: "साइन इन",
    registerButton: "पंजीकरण",
    noAccount: "खाता नहीं है?",
    haveAccount: "पहले से ही खाता है?",
    profile: "प्रोफाइल",
    logout: "लॉग आउट",
    
    // Forum
    forum: "मंच",
    forumTitle: "समुदाय मंच - देशी भाषा सीखना",
    communityForum: "समुदाय मंच",
    newTopic: "नया विषय",
    categories: "श्रेणियाँ",
    generalDiscussion: "सामान्य चर्चा",
    generalDiscussionDesc: "देशी भाषाओं से संबंधित किसी भी चीज पर चर्चा करें",
    learningTips: "सीखने के टिप्स",
    learningTipsDesc: "भाषा सीखने की रणनीतियों को साझा करें और खोजें",
    resources: "संसाधन",
    resourcesDesc: "किताबें, वेबसाइटें और अन्य शिक्षण सामग्री साझा करें",
    events: "कार्यक्रम",
    eventsDesc: "आगामी भाषा कार्यक्रम और सभाएँ",
    recentTopics: "हाल के विषय",
    noTopicsYet: "अभी तक कोई विषय नहीं। पहला विषय बनाने वाले बनें!",
    createNewTopic: "नया विषय बनाएं",
    topicTitle: "शीर्षक",
    category: "श्रेणी",
    content: "सामग्री",
    createTopic: "विषय बनाएं",
    backToForum: "← मंच पर वापस जाएं",
    replies: "जवाब",
    noRepliesYet: "अभी तक कोई जवाब नहीं। पहला जवाब देने वाले बनें!",
    postReply: "जवाब पोस्ट करें",
    submitReply: "जवाब सबमिट करें",
    signInToReply: "जवाब पोस्ट करने के लिए कृपया साइन इन करें।"
  },
  "Arabic": {
    appTitle: "تعلم اللغات الأصلية",
    welcome: "مرحبًا بك في تطبيق تعلم اللغات الأصلية",
    welcomeMessage: "اكتشف جمال اللغات الأصلية",
    welcomeSubtext: "انطلق في رحلة للحفاظ على اللغات التي تربطنا بتراثنا وتعلمها",
    selectLanguage: "اختر لغة للتعلم:",
    start: "ابدأ التعلم",
    lesson: "درس",
    exercise: "تمرين",
    check: "تحقق من الإجابة",
    correct: "صحيح!",
    incorrect: "حاول مرة أخرى",
    next: "التالي",
    back: "رجوع",
    settings: "الإعدادات",
    interfaceLanguage: "لغة الواجهة:",
    about: "حول",
    progress: "التقدم",
    vocabulary: "المفردات",
    phrases: "العبارات الشائعة",
    grammar: "القواعد",
    quiz: "اختبار",
    home: "الرئيسية",
    matching: "المطابقة",
    multipleChoice: "اختيار من متعدد",
    completed: "مكتمل",
    pronunciation: "النطق",
    cultural: "ملاحظات ثقافية",
    flashcards: "بطاقات تعليمية",
    speakingPractice: "ممارسة المحادثة",
    listeningPractice: "ممارسة الاستماع",
    dictionary: "قاموس",
    favoriteWords: "الكلمات المفضلة",
    communityForum: "منتدى المجتمع",
    communityForumHero: "انضم إلى مجتمع اللغة لدينا",
    communityForumSubtext: "تواصل مع متعلمين آخرين، شارك الموارد، وناقش اللغات الأصلية",
    profile: "الملف الشخصي",
    achievements: "الإنجازات",
    review: "مراجعة",
    searchPlaceholder: "ابحث عن كلمات أو عبارات...",
    lessonTitle: "درس لغة",
    topicViewTitle: "موضوع - تعلم اللغات الأصلية",
    loadingTopic: "جاري تحميل الموضوع...",
    orSignInWith: "أو سجل الدخول باستخدام:",
    signInWithGoogle: "جوجل",
    signInWithDiscord: "ديسكورد",
    signInWithFacebook: "فيسبوك",
    
    // Authentication
    signIn: "تسجيل الدخول",
    signInTitle: "تسجيل الدخول - تعلم اللغات الأصلية",
    register: "التسجيل",
    registerTitle: "التسجيل - تعلم اللغات الأصلية",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    username: "اسم المستخدم",
    signInButton: "تسجيل الدخول",
    registerButton: "التسجيل",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "هل لديك حساب بالفعل؟",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    
    // Forum
    forum: "المنتدى",
    forumTitle: "منتدى المجتمع - تعلم اللغات الأصلية",
    communityForum: "منتدى المجتمع",
    newTopic: "موضوع جديد",
    categories: "الفئات",
    generalDiscussion: "نقاش عام",
    generalDiscussionDesc: "ناقش أي شيء متعلق باللغات الأصلية",
    learningTips: "نصائح التعلم",
    learningTipsDesc: "شارك واكتشف استراتيجيات تعلم اللغة",
    resources: "الموارد",
    resourcesDesc: "شارك الكتب والمواقع الإلكترونية وغيرها من المواد التعليمية",
    events: "الفعاليات",
    eventsDesc: "فعاليات ولقاءات لغوية قادمة",
    recentTopics: "المواضيع الأخيرة",
    noTopicsYet: "لا توجد مواضيع بعد. كن أول من ينشئ موضوعًا!",
    createNewTopic: "إنشاء موضوع جديد",
    topicTitle: "العنوان",
    category: "الفئة",
    content: "المحتوى",
    createTopic: "إنشاء موضوع",
    backToForum: "← العودة إلى المنتدى",
    replies: "الردود",
    noRepliesYet: "لا توجد ردود بعد. كن أول من يرد!",
    postReply: "نشر رد",
    submitReply: "إرسال الرد",
    signInToReply: "الرجاء تسجيل الدخول لنشر رد."
  },
  "Swahili": {
    appTitle: "Kujifunza Lugha za Asili",
    welcome: "Karibu kwenye programu ya kujifunza lugha za asili",
    welcomeMessage: "Gundua uzuri wa lugha za asili",
    welcomeSubtext: "Anza safari ya kuhifadhi na kujifunza lugha zinazotunganisha na urithi wetu",
    selectLanguage: "Chagua lugha ya kujifunza:",
    start: "Anza kujifunza",
    lesson: "Somo",
    exercise: "Zoezi",
    check: "Angalia jibu",
    correct: "Sahihi!",
    incorrect: "Jaribu tena",
    next: "Inayofuata",
    back: "Rudi nyuma",
    settings: "Mipangilio",
    interfaceLanguage: "Lugha ya kiolesura:",
    about: "Kuhusu",
    progress: "Maendeleo",
    vocabulary: "Msamiati",
    phrases: "Misemo ya kawaida",
    grammar: "Sarufi",
    quiz: "Jaribio",
    home: "Nyumbani",
    matching: "Kulinganisha",
    multipleChoice: "Chaguo nyingi",
    completed: "Imekamilika",
    pronunciation: "Matamshi",
    cultural: "Maelezo ya kitamaduni",
    flashcards: "Kadi za kujifunza",
    speakingPractice: "Mazoezi ya kuzungumza",
    listeningPractice: "Mazoezi ya kusikiliza",
    dictionary: "Kamusi",
    favoriteWords: "Maneno yanayopendwa",
    communityForum: "Jukwaa la jamii",
    communityForumHero: "Jiunge na jamii yetu ya lugha",
    communityForumSubtext: "Unganisha na wanafunzi wengine, shiriki rasilimali, na jadili lugha za asili",
    profile: "Wasifu",
    achievements: "Mafanikio",
    review: "Mapitio",
    searchPlaceholder: "Tafuta maneno au misemo...",
    lessonTitle: "Somo la Lugha",
    topicViewTitle: "Mada - Kujifunza Lugha za Asili",
    loadingTopic: "Inapakia mada...",
    orSignInWith: "Au ingia na:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Ingia",
    signInTitle: "Ingia - Kujifunza Lugha za Asili",
    register: "Jisajili",
    registerTitle: "Jisajili - Kujifunza Lugha za Asili",
    email: "Barua pepe",
    password: "Nenosiri",
    confirmPassword: "Thibitisha nenosiri",
    username: "Jina la mtumiaji",
    signInButton: "Ingia",
    registerButton: "Jisajili",
    noAccount: "Huna akaunti?",
    haveAccount: "Una akaunti tayari?",
    profile: "Wasifu",
    logout: "Toka",
    
    // Forum
    forum: "Jukwaa",
    forumTitle: "Jukwaa la Jamii - Kujifunza Lugha za Asili",
    communityForum: "Jukwaa la Jamii",
    newTopic: "Mada mpya",
    categories: "Vikundi",
    generalDiscussion: "Majadiliano ya jumla",
    generalDiscussionDesc: "Jadili chochote kinachohusiana na lugha za asili",
    learningTips: "Vidokezo vya kujifunza",
    learningTipsDesc: "Shiriki na gundua mikakati ya kujifunza lugha",
    resources: "Rasilimali",
    resourcesDesc: "Shiriki vitabu, tovuti na nyenzo nyingine za kujifunza",
    events: "Matukio",
    eventsDesc: "Matukio ya lugha na mikutano ijayo",
    recentTopics: "Mada za hivi karibuni",
    noTopicsYet: "Hakuna mada bado. Kuwa wa kwanza kuunda moja!",
    createNewTopic: "Unda mada mpya",
    topicTitle: "Kichwa",
    category: "Kikundi",
    content: "Maudhui",
    createTopic: "Unda mada",
    backToForum: "← Rudi kwenye jukwaa",
    replies: "Majibu",
    noRepliesYet: "Hakuna majibu bado. Kuwa wa kwanza kujibu!",
    postReply: "Tuma jibu",
    submitReply: "Wasilisha jibu",
    signInToReply: "Tafadhali ingia ili kutuma jibu."
  },
  "Thai": {
    appTitle: "การเรียนรู้ภาษาพื้นเมือง",
    welcome: "ยินดีต้อนรับสู่แอปการเรียนรู้ภาษาพื้นเมือง",
    welcomeMessage: "ค้นพบความงดงามของภาษาพื้นเมือง",
    welcomeSubtext: "เริ่มต้นการเดินทางเพื่ออนุรักษ์และเรียนรู้ภาษาที่เชื่อมโยงเรากับมรดกของเรา",
    selectLanguage: "เลือกภาษาที่ต้องการเรียนรู้:",
    start: "เริ่มเรียนรู้",
    lesson: "บทเรียน",
    exercise: "แบบฝึกหัด",
    check: "ตรวจสอบคำตอบ",
    correct: "ถูกต้อง!",
    incorrect: "ลองอีกครั้ง",
    next: "ถัดไป",
    back: "ย้อนกลับ",
    settings: "การตั้งค่า",
    interfaceLanguage: "ภาษาส่วนติดต่อผู้ใช้:",
    about: "เกี่ยวกับ",
    progress: "ความคืบหน้า",
    vocabulary: "คำศัพท์",
    phrases: "วลีทั่วไป",
    grammar: "ไวยากรณ์",
    quiz: "แบบทดสอบ",
    home: "หน้าหลัก",
    matching: "จับคู่",
    multipleChoice: "หลายตัวเลือก",
    completed: "เสร็จสิ้น",
    pronunciation: "การออกเสียง",
    cultural: "หมายเหตุทางวัฒนธรรม",
    flashcards: "บัตรคำ",
    speakingPractice: "ฝึกพูด",
    listeningPractice: "ฝึกฟัง",
    dictionary: "พจนานุกรม",
    favoriteWords: "คำโปรด",
    communityForum: "ฟอรัมชุมชน",
    communityForumHero: "เข้าร่วมชุมชนภาษาของเรา",
    communityForumSubtext: "เชื่อมต่อกับผู้เรียนคนอื่น แบ่งปันทรัพยากร และพูดคุยเกี่ยวกับภาษาพื้นเมือง",
    profile: "โปรไฟล์",
    achievements: "ความสำเร็จ",
    review: "ทบทวน",
    searchPlaceholder: "ค้นหาคำหรือวลี...",
    lessonTitle: "บทเรียนภาษา",
    topicViewTitle: "หัวข้อ - การเรียนรู้ภาษาพื้นเมือง",
    loadingTopic: "กำลังโหลดหัวข้อ...",
    orSignInWith: "หรือเข้าสู่ระบบด้วย:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "เข้าสู่ระบบ",
    signInTitle: "เข้าสู่ระบบ - การเรียนรู้ภาษาพื้นเมือง",
    register: "ลงทะเบียน",
    registerTitle: "ลงทะเบียน - การเรียนรู้ภาษาพื้นเมือง",
    email: "อีเมล",
    password: "รหัสผ่าน",
    confirmPassword: "ยืนยันรหัสผ่าน",
    username: "ชื่อผู้ใช้",
    signInButton: "เข้าสู่ระบบ",
    registerButton: "ลงทะเบียน",
    noAccount: "ยังไม่มีบัญชี?",
    haveAccount: "มีบัญชีอยู่แล้ว?",
    profile: "โปรไฟล์",
    logout: "ออกจากระบบ",
    
    // Forum
    forum: "ฟอรัม",
    forumTitle: "ฟอรัมชุมชน - การเรียนรู้ภาษาพื้นเมือง",
    communityForum: "ฟอรัมชุมชน",
    newTopic: "หัวข้อใหม่",
    categories: "หมวดหมู่",
    generalDiscussion: "การสนทนาทั่วไป",
    generalDiscussionDesc: "พูดคุยเกี่ยวกับสิ่งต่างๆ ที่เกี่ยวข้องกับภาษาพื้นเมือง",
    learningTips: "เคล็ดลับการเรียนรู้",
    learningTipsDesc: "แบ่งปันและค้นพบกลยุทธ์การเรียนรู้ภาษา",
    resources: "ทรัพยากร",
    resourcesDesc: "แบ่งปันหนังสือ เว็บไซต์ และสื่อการเรียนรู้อื่นๆ",
    events: "กิจกรรม",
    eventsDesc: "กิจกรรมภาษาและการรวมตัวที่กำลังจะมาถึง",
    recentTopics: "หัวข้อล่าสุด",
    noTopicsYet: "ยังไม่มีหัวข้อ เป็นคนแรกที่สร้างหัวข้อ!",
    createNewTopic: "สร้างหัวข้อใหม่",
    topicTitle: "ชื่อเรื่อง",
    category: "หมวดหมู่",
    content: "เนื้อหา",
    createTopic: "สร้างหัวข้อ",
    backToForum: "← กลับไปยังฟอรัม",
    replies: "การตอบกลับ",
    noRepliesYet: "ยังไม่มีการตอบกลับ เป็นคนแรกที่ตอบกลับ!",
    postReply: "โพสต์การตอบกลับ",
    submitReply: "ส่งการตอบกลับ",
    signInToReply: "กรุณาเข้าสู่ระบบเพื่อโพสต์การตอบกลับ"
  },// Hebrew translations
  "Hebrew": {
    appTitle: "לימוד שפות ילידיות",
    welcome: "ברוכים הבאים לאפליקציית לימוד שפות ילידיות",
    welcomeMessage: "גלו את יופיין של השפות הילידיות",
    welcomeSubtext: "צאו למסע לשימור ולימוד שפות המחברות אותנו למורשת שלנו",
    selectLanguage: "בחרו שפה ללמוד:",
    start: "התחילו ללמוד",
    lesson: "שיעור",
    exercise: "תרגיל",
    check: "בדקו תשובה",
    correct: "נכון!",
    incorrect: "נסו שוב",
    next: "הבא",
    back: "חזרה",
    settings: "הגדרות",
    interfaceLanguage: "שפת ממשק:",
    about: "אודות",
    progress: "התקדמות",
    vocabulary: "אוצר מילים",
    phrases: "ביטויים נפוצים",
    grammar: "דקדוק",
    quiz: "חידון",
    home: "דף הבית",
    matching: "התאמה",
    multipleChoice: "רב-ברירה",
    completed: "הושלם",
    pronunciation: "הגייה",
    cultural: "הערות תרבותיות",
    flashcards: "כרטיסיות לימוד",
    speakingPractice: "תרגול דיבור",
    listeningPractice: "תרגול האזנה",
    dictionary: "מילון",
    favoriteWords: "מילים מועדפות",
    communityForum: "פורום קהילתי",
    communityForumHero: "הצטרפו לקהילת השפה שלנו",
    communityForumSubtext: "התחברו עם לומדים אחרים, שתפו משאבים ודונו בשפות ילידיות",
    profile: "פרופיל",
    achievements: "הישגים",
    review: "חזרה",
    searchPlaceholder: "חפשו מילים או ביטויים...",
    lessonTitle: "שיעור שפה",
    topicViewTitle: "נושא - לימוד שפות ילידיות",
    loadingTopic: "טוען נושא...",
    orSignInWith: "או התחברו באמצעות:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "התחברות",
    signInTitle: "התחברות - לימוד שפות ילידיות",
    register: "הרשמה",
    registerTitle: "הרשמה - לימוד שפות ילידיות",
    email: "דוא\"ל",
    password: "סיסמה",
    confirmPassword: "אימות סיסמה",
    username: "שם משתמש",
    signInButton: "התחברות",
    registerButton: "הרשמה",
    noAccount: "אין לכם חשבון?",
    haveAccount: "כבר יש לכם חשבון?",
    profile: "פרופיל",
    logout: "התנתקות",
    
    // Forum
    forum: "פורום",
    forumTitle: "פורום קהילתי - לימוד שפות ילידיות",
    communityForum: "פורום קהילתי",
    newTopic: "נושא חדש",
    categories: "קטגוריות",
    generalDiscussion: "דיון כללי",
    generalDiscussionDesc: "דונו בכל דבר הקשור לשפות ילידיות",
    learningTips: "טיפים ללמידה",
    learningTipsDesc: "שתפו וגלו אסטרטגיות ללימוד שפות",
    resources: "משאבים",
    resourcesDesc: "שתפו ספרים, אתרים וחומרי לימוד אחרים",
    events: "אירועים",
    eventsDesc: "אירועי שפה ומפגשים קרובים",
    recentTopics: "נושאים אחרונים",
    noTopicsYet: "אין עדיין נושאים. היו הראשונים ליצור אחד!",
    createNewTopic: "צרו נושא חדש",
    topicTitle: "כותרת",
    category: "קטגוריה",
    content: "תוכן",
    createTopic: "צרו נושא",
    backToForum: "← חזרה לפורום",
    replies: "תגובות",
    noRepliesYet: "אין עדיין תגובות. היו הראשונים להגיב!",
    postReply: "פרסמו תגובה",
    submitReply: "שלחו תגובה",
    signInToReply: "אנא התחברו כדי לפרסם תגובה."
  },
  "Kazakh": {
    appTitle: "Байырғы тілдерді үйрену",
    welcome: "Байырғы тілдерді үйрену қолданбасына қош келдіңіз",
    welcomeMessage: "Байырғы тілдердің сұлулығын ашыңыз",
    welcomeSubtext: "Бізді мұрамызбен байланыстыратын тілдерді сақтау және үйрену сапарына шығыңыз",
    selectLanguage: "Үйренетін тілді таңдаңыз:",
    start: "Үйренуді бастау",
    lesson: "Сабақ",
    exercise: "Жаттығу",
    check: "Жауапты тексеру",
    correct: "Дұрыс!",
    incorrect: "Қайталап көріңіз",
    next: "Келесі",
    back: "Артқа",
    settings: "Параметрлер",
    interfaceLanguage: "Интерфейс тілі:",
    about: "Біз туралы",
    progress: "Прогресс",
    vocabulary: "Сөздік қор",
    phrases: "Жиі қолданылатын сөз тіркестері",
    grammar: "Грамматика",
    quiz: "Викторина",
    home: "Басты бет",
    matching: "Сәйкестендіру",
    multipleChoice: "Бірнеше таңдау",
    completed: "Аяқталды",
    pronunciation: "Айтылым",
    cultural: "Мәдени жазбалар",
    flashcards: "Флэш-карталар",
    speakingPractice: "Сөйлеу тәжірибесі",
    listeningPractice: "Тыңдау тәжірибесі",
    dictionary: "Сөздік",
    favoriteWords: "Таңдаулы сөздер",
    communityForum: "Қоғамдастық форумы",
    communityForumHero: "Біздің тіл қоғамдастығымызға қосылыңыз",
    communityForumSubtext: "Басқа оқушылармен байланысыңыз, ресурстарды бөлісіңіз және байырғы тілдер туралы талқылаңыз",
    profile: "Профиль",
    achievements: "Жетістіктер",
    review: "Шолу",
    searchPlaceholder: "Сөздер немесе сөз тіркестерін іздеу...",
    lessonTitle: "Тіл сабағы",
    topicViewTitle: "Тақырып - Байырғы тілдерді үйрену",
    loadingTopic: "Тақырып жүктелуде...",
    orSignInWith: "Немесе мынамен кіріңіз:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Кіру",
    signInTitle: "Кіру - Байырғы тілдерді үйрену",
    register: "Тіркелу",
    registerTitle: "Тіркелу - Байырғы тілдерді үйрену",
    email: "Электрондық пошта",
    password: "Құпия сөз",
    confirmPassword: "Құпия сөзді растау",
    username: "Пайдаланушы аты",
    signInButton: "Кіру",
    registerButton: "Тіркелу",
    noAccount: "Тіркелгіңіз жоқ па?",
    haveAccount: "Тіркелгіңіз бар ма?",
    profile: "Профиль",
    logout: "Шығу",
    
    // Forum
    forum: "Форум",
    forumTitle: "Қоғамдастық форумы - Байырғы тілдерді үйрену",
    communityForum: "Қоғамдастық форумы",
    newTopic: "Жаңа тақырып",
    categories: "Санаттар",
    generalDiscussion: "Жалпы талқылау",
    generalDiscussionDesc: "Байырғы тілдерге қатысты кез келген нәрсені талқылаңыз",
    learningTips: "Үйрену кеңестері",
    learningTipsDesc: "Тіл үйрену стратегияларын бөлісіңіз және ашыңыз",
    resources: "Ресурстар",
    resourcesDesc: "Кітаптар, веб-сайттар және басқа оқу материалдарын бөлісіңіз",
    events: "Іс-шаралар",
    eventsDesc: "Алдағы тіл іс-шаралары мен жиындар",
    recentTopics: "Соңғы тақырыптар",
    noTopicsYet: "Әлі тақырыптар жоқ. Бірінші болып жасаңыз!",
    createNewTopic: "Жаңа тақырып жасау",
    topicTitle: "Тақырып",
    category: "Санат",
    content: "Мазмұн",
    createTopic: "Тақырып жасау",
    backToForum: "← Форумға оралу",
    replies: "Жауаптар",
    noRepliesYet: "Әлі жауаптар жоқ. Бірінші болып жауап беріңіз!",
    postReply: "Жауап жазу",
    submitReply: "Жауапты жіберу",
    signInToReply: "Жауап жазу үшін кіріңіз."
  },
  
  // Czech translations
  "Czech": {
    appTitle: "Výuka domorodých jazyků",
    welcome: "Vítejte v aplikaci pro výuku domorodých jazyků",
    welcomeMessage: "Objevte krásu domorodých jazyků",
    welcomeSubtext: "Vydejte se na cestu k zachování a učení se jazyků, které nás spojují s naším dědictvím",
    selectLanguage: "Vyberte jazyk k učení:",
    start: "Začít se učit",
    lesson: "Lekce",
    exercise: "Cvičení",
    check: "Zkontrolovat odpověď",
    correct: "Správně!",
    incorrect: "Zkuste to znovu",
    next: "Další",
    back: "Zpět",
    settings: "Nastavení",
    interfaceLanguage: "Jazyk rozhraní:",
    about: "O nás",
    progress: "Pokrok",
    vocabulary: "Slovní zásoba",
    phrases: "Běžné fráze",
    grammar: "Gramatika",
    quiz: "Kvíz",
    home: "Domů",
    matching: "Párování",
    multipleChoice: "Výběr z možností",
    completed: "Dokončeno",
    pronunciation: "Výslovnost",
    cultural: "Kulturní poznámky",
    flashcards: "Kartičky",
    speakingPractice: "Procvičování mluvení",
    listeningPractice: "Procvičování poslechu",
    dictionary: "Slovník",
    favoriteWords: "Oblíbená slova",
    communityForum: "Komunitní fórum",
    communityForumHero: "Připojte se k naší jazykové komunitě",
    communityForumSubtext: "Spojte se s dalšími studenty, sdílejte zdroje a diskutujte o domorodých jazycích",
    profile: "Profil",
    achievements: "Úspěchy",
    review: "Opakování",
    searchPlaceholder: "Hledat slova nebo fráze...",
    lessonTitle: "Jazyková lekce",
    topicViewTitle: "Téma - Výuka domorodých jazyků",
    loadingTopic: "Načítání tématu...",
    orSignInWith: "Nebo se přihlaste pomocí:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Přihlásit se",
    signInTitle: "Přihlášení - Výuka domorodých jazyků",
    register: "Registrovat se",
    registerTitle: "Registrace - Výuka domorodých jazyků",
    email: "E-mail",
    password: "Heslo",
    confirmPassword: "Potvrdit heslo",
    username: "Uživatelské jméno",
    signInButton: "Přihlásit se",
    registerButton: "Registrovat se",
    noAccount: "Nemáte účet?",
    haveAccount: "Již máte účet?",
    profile: "Profil",
    logout: "Odhlásit se",
    
    // Forum
    forum: "Fórum",
    forumTitle: "Komunitní fórum - Výuka domorodých jazyků",
    communityForum: "Komunitní fórum",
    newTopic: "Nové téma",
    categories: "Kategorie",
    generalDiscussion: "Obecná diskuze",
    generalDiscussionDesc: "Diskutujte o čemkoli souvisejícím s domorodými jazyky",
    learningTips: "Tipy k učení",
    learningTipsDesc: "Sdílejte a objevujte strategie učení jazyků",
    resources: "Zdroje",
    resourcesDesc: "Sdílejte knihy, webové stránky a další učební materiály",
    events: "Události",
    eventsDesc: "Nadcházející jazykové události a setkání",
    recentTopics: "Nedávná témata",
    noTopicsYet: "Zatím žádná témata. Buďte první, kdo vytvoří téma!",
    createNewTopic: "Vytvořit nové téma",
    topicTitle: "Název",
    category: "Kategorie",
    content: "Obsah",
    createTopic: "Vytvořit téma",
    backToForum: "← Zpět na fórum",
    replies: "Odpovědi",
    noRepliesYet: "Zatím žádné odpovědi. Buďte první, kdo odpoví!",
    postReply: "Přidat odpověď",
    submitReply: "Odeslat odpověď",
    signInToReply: "Pro přidání odpovědi se prosím přihlaste."
  },
  "Georgian": {
    appTitle: "მკვიდრი ენების შესწავლა",
    welcome: "მოგესალმებით მკვიდრი ენების შესწავლის აპლიკაციაში",
    welcomeMessage: "აღმოაჩინეთ მკვიდრი ენების სილამაზე",
    welcomeSubtext: "დაიწყეთ მოგზაურობა იმ ენების შესანარჩუნებლად და შესასწავლად, რომლებიც გვაკავშირებს ჩვენს მემკვიდრეობასთან",
    selectLanguage: "აირჩიეთ შესასწავლი ენა:",
    start: "დაიწყეთ სწავლა",
    lesson: "გაკვეთილი",
    exercise: "სავარჯიშო",
    check: "პასუხის შემოწმება",
    correct: "სწორია!",
    incorrect: "სცადეთ ხელახლა",
    next: "შემდეგი",
    back: "უკან",
    settings: "პარამეტრები",
    interfaceLanguage: "ინტერფეისის ენა:",
    about: "შესახებ",
    progress: "პროგრესი",
    vocabulary: "ლექსიკა",
    phrases: "გავრცელებული ფრაზები",
    grammar: "გრამატიკა",
    quiz: "ვიქტორინა",
    home: "მთავარი",
    matching: "შესაბამისობა",
    multipleChoice: "მრავალი არჩევანი",
    completed: "დასრულებული",
    pronunciation: "გამოთქმა",
    cultural: "კულტურული შენიშვნები",
    flashcards: "ბარათები",
    speakingPractice: "საუბრის პრაქტიკა",
    listeningPractice: "მოსმენის პრაქტიკა",
    dictionary: "ლექსიკონი",
    favoriteWords: "საყვარელი სიტყვები",
    communityForum: "საზოგადოების ფორუმი",
    communityForumHero: "შეუერთდით ჩვენს ენობრივ საზოგადოებას",
    communityForumSubtext: "დაუკავშირდით სხვა შემსწავლელებს, გააზიარეთ რესურსები და განიხილეთ მკვიდრი ენები",
    profile: "პროფილი",
    achievements: "მიღწევები",
    review: "გადახედვა",
    searchPlaceholder: "მოძებნეთ სიტყვები ან ფრაზები...",
    lessonTitle: "ენის გაკვეთილი",
    topicViewTitle: "თემა - მკვიდრი ენების შესწავლა",
    loadingTopic: "თემის ჩატვირთვა...",
    orSignInWith: "ან შედით:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "შესვლა",
    signInTitle: "შესვლა - მკვიდრი ენების შესწავლა",
    register: "რეგისტრაცია",
    registerTitle: "რეგისტრაცია - მკვიდრი ენების შესწავლა",
    email: "ელფოსტა",
    password: "პაროლი",
    confirmPassword: "პაროლის დადასტურება",
    username: "მომხმარებლის სახელი",
    signInButton: "შესვლა",
    registerButton: "რეგისტრაცია",
    noAccount: "არ გაქვთ ანგარიში?",
    haveAccount: "უკვე გაქვთ ანგარიში?",
    profile: "პროფილი",
    logout: "გასვლა",
    
    // Forum
    forum: "ფორუმი",
    forumTitle: "საზოგადოების ფორუმი - მკვიდრი ენების შესწავლა",
    communityForum: "საზოგადოების ფორუმი",
    newTopic: "ახალი თემა",
    categories: "კატეგორიები",
    generalDiscussion: "ზოგადი განხილვა",
    generalDiscussionDesc: "განიხილეთ ნებისმიერი რამ, რაც დაკავშირებულია მკვიდრ ენებთან",
    learningTips: "სწავლის რჩევები",
    learningTipsDesc: "გააზიარეთ და აღმოაჩინეთ ენის შესწავლის სტრატეგიები",
    resources: "რესურსები",
    resourcesDesc: "გააზიარეთ წიგნები, ვებგვერდები და სხვა სასწავლო მასალები",
    events: "ღონისძიებები",
    eventsDesc: "მომავალი ენობრივი ღონისძიებები და შეხვედრები",
    recentTopics: "ბოლო თემები",
    noTopicsYet: "ჯერ თემები არ არის. იყავით პირველი, ვინც შექმნის!",
    createNewTopic: "შექმენით ახალი თემა",
    topicTitle: "სათაური",
    category: "კატეგორია",
    content: "შინაარსი",
    createTopic: "თემის შექმნა",
    backToForum: "← ფორუმზე დაბრუნება",
    replies: "პასუხები",
    noRepliesYet: "ჯერ პასუხები არ არის. იყავით პირველი, ვინც უპასუხებს!",
    postReply: "პასუხის გაგზავნა",
    submitReply: "პასუხის გაგზავნა",
    signInToReply: "გთხოვთ, შეხვიდეთ პასუხის გასაგზავნად."
  },
  
  // Armenian translations
  "Armenian": {
    appTitle: "Բնիկ լեզուների ուսուցում",
    welcome: "Բարի գալուստ բնիկ լեզուների ուսուցման հավելված",
    welcomeMessage: "Բացահայտեք բնիկ լեզուների գեղեցկությունը",
    welcomeSubtext: "Սկսեք ճանապարհորդություն՝ պահպանելու և սովորելու այն լեզուները, որոնք մեզ կապում են մեր ժառանգության հետ",
    selectLanguage: "Ընտրեք լեզու սովորելու համար:",
    start: "Սկսել սովորել",
    lesson: "Դաս",
    exercise: "Վարժություն",
    check: "Ստուգել պատասխանը",
    correct: "Ճիշտ է!",
    incorrect: "Փորձեք կրկին",
    next: "Հաջորդը",
    back: "Հետ",
    settings: "Կարգավորումներ",
    interfaceLanguage: "Ինտերֆեյսի լեզուն:",
    about: "Մեր մասին",
    progress: "Առաջընթաց",
    vocabulary: "Բառապաշար",
    phrases: "Հաճախակի արտահայտություններ",
    grammar: "Քերականություն",
    quiz: "Վիկտորինա",
    home: "Գլխավոր",
    matching: "Համապատասխանեցում",
    multipleChoice: "Բազմակի ընտրություն",
    completed: "Ավարտված",
    pronunciation: "Արտասանություն",
    cultural: "Մշակութային նշումներ",
    flashcards: "Ֆլեշ քարտեր",
    speakingPractice: "Խոսելու պրակտիկա",
    listeningPractice: "Լսելու պրակտիկա",
    dictionary: "Բառարան",
    favoriteWords: "Սիրելի բառեր",
    communityForum: "Համայնքի ֆորում",
    communityForumHero: "Միացեք մեր լեզվական համայնքին",
    communityForumSubtext: "Կապվեք այլ սովորողների հետ, կիսվեք ռեսուրսներով և քննարկեք բնիկ լեզուները",
    profile: "Պրոֆիլ",
    achievements: "Ձեռքբերումներ",
    review: "Վերանայում",
    searchPlaceholder: "Որոնել բառեր կամ արտահայտություններ...",
    lessonTitle: "Լեզվի դաս",
    topicViewTitle: "Թեմա - Բնիկ լեզուների ուսուցում",
    loadingTopic: "Թեման բեռնվում է...",
    orSignInWith: "Կամ մուտք գործեք:",
    signInWithGoogle: "Google",
    signInWithDiscord: "Discord",
    signInWithFacebook: "Facebook",
    
    // Authentication
    signIn: "Մուտք",
    signInTitle: "Մուտք - Բնիկ լեզուների ուսուցում",
    register: "Գրանցվել",
    registerTitle: "Գրանցում - Բնիկ լեզուների ուսուցում",
    email: "Էլ. փոստ",
    password: "Գաղտնաբառ",
    confirmPassword: "Հաստատել գաղտնաբառը",
    username: "Օգտանուն",
    signInButton: "Մուտք",
    registerButton: "Գրանցվել",
    noAccount: "Չունե՞ք հաշիվ:",
    haveAccount: "Արդեն ունե՞ք հաշիվ:",
    profile: "Պրոֆիլ",
    logout: "Դուրս գալ",
    
    // Forum
    forum: "Ֆորում",
    forumTitle: "Համայնքի ֆորում - Բնիկ լեզուների ուսուցում",
    communityForum: "Համայնքի ֆորում",
    newTopic: "Նոր թեմա",
    categories: "Կատեգորիաներ",
    generalDiscussion: "Ընդհանուր քննարկում",
    generalDiscussionDesc: "Քննարկեք ցանկացած բան, որը կապված է բնիկ լեզուների հետ",
    learningTips: "Սովորելու խորհուրդներ",
    learningTipsDesc: "Կիսվեք և բացահայտեք լեզվի ուսուցման ռազմավարություններ",
    resources: "Ռեսուրսներ",
    resourcesDesc: "Կիսվեք գրքերով, կայքերով և այլ ուսումնական նյութերով",
    events: "Միջոցառումներ",
    eventsDesc: "Առաջիկա լեզվական միջոցառումներ և հանդիպումներ",
    recentTopics: "Վերջին թեմաները",
    noTopicsYet: "Դեռ թեմաներ չկան: Եղեք առաջինը, ով կստեղծի մեկը!",
    createNewTopic: "Ստեղծել նոր թեմա",
    topicTitle: "Վերնագիր",
    category: "Կատեգորիա",
    content: "Բովանդակություն",
    createTopic: "Ստեղծել թեմա",
    backToForum: "← Վերադառնալ ֆորում",
    replies: "Պատասխաններ",
    noRepliesYet: "Դեռ պատասխաններ չկան: Եղեք առաջինը, ով կպատասխանի!",
    postReply: "Տեղադրել պատասխան",
    submitReply: "Ուղարկել պատասխանը",
    signInToReply: "Խնդրում ենք մուտք գործել պատասխան տեղադրելու համար:"
  }
}